/* eslint-disable */

export const AllTypesProps: Record<string,any> = {
	AcceptChildOrderInput:{
		document:"AssetContributionStatementSignedDocumentInput"
	},
	AccountType: "enum" as const,
	ActionFiltersInput:{

	},
	AddAuthorInput:{

	},
	AddParticipantInput:{
		entrepreneur_data:"CreateEntrepreneurDataInput",
		individual_data:"CreateIndividualDataInput",
		organization_data:"CreateOrganizationDataInput",
		type:"AccountType"
	},
	AddPaymentMethodInput:{
		bank_transfer_data:"BankAccountInput",
		sbp_data:"SbpDataInput"
	},
	AddTrustedAccountInput:{

	},
	AgendaGeneralMeetPointInput:{

	},
	AgendaGeneralMeetQuestion:{

	},
	AgendaMeet:{

	},
	AgreementFilter:{
		created_from:"DateTime",
		created_to:"DateTime",
		statuses:"AgreementStatus"
	},
	AgreementInput:{

	},
	AgreementStatus: "enum" as const,
	AgreementVarInput:{

	},
	AnnualGeneralMeetingAgendaGenerateDocumentInput:{
		meet:"AgendaMeet",
		questions:"AgendaGeneralMeetQuestion"
	},
	AnnualGeneralMeetingAgendaSignedDocumentInput:{
		meta:"AnnualGeneralMeetingAgendaSignedMetaDocumentInput",
		signatures:"SignatureInfoInput"
	},
	AnnualGeneralMeetingAgendaSignedMetaDocumentInput:{
		meet:"AgendaMeet",
		questions:"AgendaGeneralMeetQuestion"
	},
	AnnualGeneralMeetingDecisionGenerateDocumentInput:{

	},
	AnnualGeneralMeetingDecisionSignedDocumentInput:{
		meta:"AnnualGeneralMeetingDecisionSignedMetaDocumentInput",
		signatures:"SignatureInfoInput"
	},
	AnnualGeneralMeetingDecisionSignedMetaDocumentInput:{

	},
	AnnualGeneralMeetingNotificationGenerateDocumentInput:{

	},
	AnnualGeneralMeetingNotificationSignedDocumentInput:{
		meta:"AnnualGeneralMeetingNotificationSignedMetaDocumentInput",
		signatures:"SignatureInfoInput"
	},
	AnnualGeneralMeetingNotificationSignedMetaDocumentInput:{

	},
	AnnualGeneralMeetingSovietDecisionGenerateDocumentInput:{

	},
	AnnualGeneralMeetingVotingBallotGenerateDocumentInput:{
		answers:"AnswerInput"
	},
	AnnualGeneralMeetingVotingBallotSignedDocumentInput:{
		meta:"AnnualGeneralMeetingVotingBallotSignedMetaDocumentInput",
		signatures:"SignatureInfoInput"
	},
	AnnualGeneralMeetingVotingBallotSignedMetaDocumentInput:{
		answers:"AnswerInput"
	},
	AnswerInput:{

	},
	AppendixGenerationAgreementGenerateDocumentInput:{

	},
	ApprovalFilter:{
		created_from:"DateTime",
		created_to:"DateTime",
		statuses:"ApprovalStatus"
	},
	ApprovalStatus: "enum" as const,
	AssetContributionActGenerateDocumentInput:{

	},
	AssetContributionActSignedDocumentInput:{
		meta:"AssetContributionActSignedMetaDocumentInput",
		signatures:"SignatureInfoInput"
	},
	AssetContributionActSignedMetaDocumentInput:{

	},
	AssetContributionDecisionGenerateDocumentInput:{

	},
	AssetContributionStatementGenerateDocumentInput:{
		request:"CommonRequestInput"
	},
	AssetContributionStatementSignedDocumentInput:{
		meta:"AssetContributionStatementSignedMetaDocumentInput",
		signatures:"SignatureInfoInput"
	},
	AssetContributionStatementSignedMetaDocumentInput:{
		request:"CommonRequestInput"
	},
	BankAccountDetailsInput:{

	},
	BankAccountInput:{
		details:"BankAccountDetailsInput"
	},
	CalculateVotesInput:{

	},
	CancelRequestInput:{

	},
	CapitalCommitFilter:{
		status:"CommitStatus"
	},
	CapitalContributorFilter:{
		status:"ContributorStatus"
	},
	CapitalCycleFilter:{
		status:"CycleStatus"
	},
	CapitalInvestFilter:{
		status:"InvestStatus"
	},
	CapitalIssueFilter:{
		priorities:"IssuePriority",
		statuses:"IssueStatus"
	},
	CapitalLogFilterInput:{
		date_from:"DateTime",
		date_to:"DateTime",
		event_types:"LogEventType"
	},
	CapitalProjectFilter:{
		has_issues_with_priorities:"IssuePriority",
		has_issues_with_statuses:"IssueStatus",
		statuses:"ProjectStatus"
	},
	CapitalSegmentFilter:{
		status:"SegmentStatus"
	},
	CapitalStoryFilter:{
		status:"StoryStatus"
	},
	CapitalTimeEntriesFilter:{

	},
	CapitalTimeStatsInput:{

	},
	ChairmanOnboardingAgendaInput:{
		step:"ChairmanOnboardingAgendaStep"
	},
	ChairmanOnboardingAgendaStep: "enum" as const,
	ChairmanOnboardingGeneralMeetInput:{

	},
	CheckMatrixUsernameInput:{

	},
	CloseProjectInput:{

	},
	CommitApproveInput:{

	},
	CommitDeclineInput:{

	},
	CommitStatus: "enum" as const,
	CommonRequestInput:{

	},
	CompleteRequestInput:{

	},
	CompleteVotingInput:{

	},
	ConfigInput:{

	},
	ConfirmAgreementInput:{

	},
	ConfirmApproveInput:{
		approved_document:"SignedDigitalDocumentInput"
	},
	ConfirmReceiveOnRequestInput:{
		document:"ReturnByAssetActSignedDocumentInput"
	},
	ConfirmSupplyOnRequestInput:{
		document:"AssetContributionActSignedDocumentInput"
	},
	ContributorStatus: "enum" as const,
	ConvertSegmentInput:{
		convert_statement:"SignedDigitalDocumentInput"
	},
	ConvertToAxonStatementGenerateDocumentInput:{

	},
	ConvertToAxonStatementSignedDocumentInput:{
		meta:"ConvertToAxonStatementSignedMetaDocumentInput",
		signatures:"SignatureInfoInput"
	},
	ConvertToAxonStatementSignedMetaDocumentInput:{

	},
	Country: "enum" as const,
	CreateAnnualGeneralMeetInput:{
		agenda:"AgendaGeneralMeetPointInput",
		close_at:"DateTime",
		open_at:"DateTime",
		proposal:"AnnualGeneralMeetingAgendaSignedDocumentInput"
	},
	CreateBranchInput:{

	},
	CreateChildOrderInput:{
		document:"ReturnByAssetStatementSignedDocumentInput"
	},
	CreateCommitInput:{

	},
	CreateCycleInput:{
		status:"CycleStatus"
	},
	CreateDebtInput:{
		statement:"SignedDigitalDocumentInput"
	},
	CreateDepositPaymentInput:{

	},
	CreateEntrepreneurDataInput:{
		bank_account:"BankAccountInput",
		country:"Country",
		details:"EntrepreneurDetailsInput"
	},
	CreateExpenseInput:{
		statement:"SignedDigitalDocumentInput"
	},
	CreateIndividualDataInput:{
		passport:"PassportInput"
	},
	CreateInitOrganizationDataInput:{
		bank_account:"BankAccountInput",
		details:"OrganizationDetailsInput",
		represented_by:"RepresentedByInput",
		type:"OrganizationType"
	},
	CreateInitialPaymentInput:{

	},
	CreateIssueInput:{
		priority:"IssuePriority",
		status:"IssueStatus"
	},
	CreateMatrixAccountInputDTO:{

	},
	CreateOrganizationDataInput:{
		bank_account:"BankAccountInput",
		details:"OrganizationDetailsInput",
		represented_by:"RepresentedByInput",
		type:"OrganizationType"
	},
	CreateParentOfferInput:{

	},
	CreateProgramPropertyInput:{
		statement:"SignedDigitalDocumentInput"
	},
	CreateProjectFreeDecisionInput:{

	},
	CreateProjectInput:{

	},
	CreateProjectInvestInput:{
		statement:"SignedDigitalDocumentInput"
	},
	CreateProjectPropertyInput:{

	},
	CreateSovietIndividualDataInput:{
		passport:"PassportInput"
	},
	CreateStoryInput:{
		status:"StoryStatus"
	},
	CreateSubscriptionInput:{
		subscription:"WebPushSubscriptionDataInput"
	},
	CreateWithdrawInput:{
		statement:"ReturnByMoneySignedDocumentInput"
	},
	CurrentTableStatesFiltersInput:{

	},
	CycleStatus: "enum" as const,
	DateTime: `scalar.DateTime` as const,
	DeactivateSubscriptionInput:{

	},
	DebtFilter:{

	},
	DebtStatus: "enum" as const,
	DeclineAgreementInput:{

	},
	DeclineApproveInput:{

	},
	DeclineRequestInput:{

	},
	DeleteBranchInput:{

	},
	DeleteCapitalIssueByHashInput:{

	},
	DeleteCapitalStoryByHashInput:{

	},
	DeletePaymentMethodInput:{

	},
	DeleteProjectInput:{

	},
	DeleteTrustedAccountInput:{

	},
	DeliverOnRequestInput:{

	},
	DeltaFiltersInput:{

	},
	DisputeOnRequestInput:{
		document:"JSONObject"
	},
	DocumentAction: "enum" as const,
	EditBranchInput:{

	},
	EditContributorInput:{

	},
	EditProjectInput:{

	},
	EntrepreneurDetailsInput:{

	},
	ExpenseFilter:{

	},
	ExpenseStatus: "enum" as const,
	ExtendedMeetStatus: "enum" as const,
	ExtensionInput:{
		config:"JSON",
		created_at:"DateTime",
		updated_at:"DateTime"
	},
	FreeDecisionGenerateDocumentInput:{

	},
	FundProgramInput:{

	},
	FundProjectInput:{

	},
	GenerateAnyDocumentInput:{
		data:"JSON",
		options:"GenerateDocumentOptionsInput"
	},
	GenerateDocumentInput:{

	},
	GenerateDocumentOptionsInput:{

	},
	GenerateRegistrationDocumentsInput:{
		account_type:"AccountType"
	},
	GenerationAgreementGenerateDocumentInput:{

	},
	GetAccountInput:{

	},
	GetAccountsInput:{

	},
	GetBranchesInput:{

	},
	GetCapitalCommitByHashInput:{

	},
	GetCapitalConfigInput:{

	},
	GetCapitalIssueByHashInput:{

	},
	GetCapitalIssueLogsInput:{

	},
	GetCapitalLogsInput:{
		filter:"CapitalLogFilterInput",
		pagination:"PaginationInput"
	},
	GetCapitalStoryByHashInput:{

	},
	GetContributorInput:{

	},
	GetDebtInput:{

	},
	GetDocumentsInput:{
		actions:"DocumentAction",
		filter:"JSON"
	},
	GetExpenseInput:{

	},
	GetExtensionLogsInput:{
		createdFrom:"DateTime",
		createdTo:"DateTime"
	},
	GetExtensionsInput:{

	},
	GetInstallationStatusInput:{

	},
	GetInvestInput:{

	},
	GetLedgerHistoryInput:{

	},
	GetLedgerInput:{

	},
	GetMeetInput:{

	},
	GetMeetsInput:{

	},
	GetOneCoopDocumentsInput:{

	},
	GetPaymentMethodsInput:{

	},
	GetProgramInvestInput:{

	},
	GetProjectInput:{

	},
	GetProjectWithRelationsInput:{

	},
	GetResultInput:{

	},
	GetUserSubscriptionsInput:{

	},
	GetVoteInput:{

	},
	ImportContributorInput:{

	},
	Init:{
		organization_data:"CreateInitOrganizationDataInput"
	},
	Install:{
		soviet:"SovietMemberInput",
		vars:"SetVarsInput"
	},
	InstanceStatus: "enum" as const,
	InvestStatus: "enum" as const,
	IssuePriority: "enum" as const,
	IssueStatus: "enum" as const,
	JSON: `scalar.JSON` as const,
	JSONObject: `scalar.JSONObject` as const,
	LogEntityType: "enum" as const,
	LogEventType: "enum" as const,
	LoginInput:{

	},
	LogoutInput:{

	},
	MakeClearanceInput:{
		document:"SignedDigitalDocumentInput"
	},
	MetaDocumentInput:{

	},
	ModerateRequestInput:{

	},
	Mutation:{
		acceptChildOrder:{
			data:"AcceptChildOrderInput"
		},
		addParticipant:{
			data:"AddParticipantInput"
		},
		addPaymentMethod:{
			data:"AddPaymentMethodInput"
		},
		addTrustedAccount:{
			data:"AddTrustedAccountInput"
		},
		cancelRequest:{
			data:"CancelRequestInput"
		},
		capitalAddAuthor:{
			data:"AddAuthorInput"
		},
		capitalApproveCommit:{
			data:"CommitApproveInput"
		},
		capitalCalculateVotes:{
			data:"CalculateVotesInput"
		},
		capitalCloseProject:{
			data:"CloseProjectInput"
		},
		capitalCompleteVoting:{
			data:"CompleteVotingInput"
		},
		capitalConvertSegment:{
			data:"ConvertSegmentInput"
		},
		capitalCreateCommit:{
			data:"CreateCommitInput"
		},
		capitalCreateCycle:{
			data:"CreateCycleInput"
		},
		capitalCreateDebt:{
			data:"CreateDebtInput"
		},
		capitalCreateExpense:{
			data:"CreateExpenseInput"
		},
		capitalCreateIssue:{
			data:"CreateIssueInput"
		},
		capitalCreateProgramProperty:{
			data:"CreateProgramPropertyInput"
		},
		capitalCreateProject:{
			data:"CreateProjectInput"
		},
		capitalCreateProjectInvest:{
			data:"CreateProjectInvestInput"
		},
		capitalCreateProjectProperty:{
			data:"CreateProjectPropertyInput"
		},
		capitalCreateStory:{
			data:"CreateStoryInput"
		},
		capitalDeclineCommit:{
			data:"CommitDeclineInput"
		},
		capitalDeleteIssue:{
			data:"DeleteCapitalIssueByHashInput"
		},
		capitalDeleteProject:{
			data:"DeleteProjectInput"
		},
		capitalDeleteStory:{
			data:"DeleteCapitalStoryByHashInput"
		},
		capitalEditContributor:{
			data:"EditContributorInput"
		},
		capitalEditProject:{
			data:"EditProjectInput"
		},
		capitalFundProgram:{
			data:"FundProgramInput"
		},
		capitalFundProject:{
			data:"FundProjectInput"
		},
		capitalGenerateAppendixGenerationAgreement:{
			data:"AppendixGenerationAgreementGenerateDocumentInput",
			options:"GenerateDocumentOptionsInput"
		},
		capitalGenerateCapitalizationAgreement:{
			data:"GenerateDocumentInput",
			options:"GenerateDocumentOptionsInput"
		},
		capitalGenerateCapitalizationMoneyInvestStatement:{
			data:"GenerateDocumentInput",
			options:"GenerateDocumentOptionsInput"
		},
		capitalGenerateCapitalizationPropertyInvestAct:{
			data:"GenerateDocumentInput",
			options:"GenerateDocumentOptionsInput"
		},
		capitalGenerateCapitalizationPropertyInvestDecision:{
			data:"GenerateDocumentInput",
			options:"GenerateDocumentOptionsInput"
		},
		capitalGenerateCapitalizationPropertyInvestStatement:{
			data:"GenerateDocumentInput",
			options:"GenerateDocumentOptionsInput"
		},
		capitalGenerateCapitalizationToMainWalletConvertStatement:{
			data:"GenerateDocumentInput",
			options:"GenerateDocumentOptionsInput"
		},
		capitalGenerateExpenseDecision:{
			data:"GenerateDocumentInput",
			options:"GenerateDocumentOptionsInput"
		},
		capitalGenerateExpenseStatement:{
			data:"GenerateDocumentInput",
			options:"GenerateDocumentOptionsInput"
		},
		capitalGenerateGenerationAgreement:{
			data:"GenerationAgreementGenerateDocumentInput",
			options:"GenerateDocumentOptionsInput"
		},
		capitalGenerateGenerationMoneyInvestStatement:{
			data:"GenerateDocumentInput",
			options:"GenerateDocumentOptionsInput"
		},
		capitalGenerateGenerationMoneyReturnUnusedStatement:{
			data:"GenerateDocumentInput",
			options:"GenerateDocumentOptionsInput"
		},
		capitalGenerateGenerationPropertyInvestAct:{
			data:"GenerateDocumentInput",
			options:"GenerateDocumentOptionsInput"
		},
		capitalGenerateGenerationPropertyInvestDecision:{
			data:"GenerateDocumentInput",
			options:"GenerateDocumentOptionsInput"
		},
		capitalGenerateGenerationPropertyInvestStatement:{
			data:"GenerateDocumentInput",
			options:"GenerateDocumentOptionsInput"
		},
		capitalGenerateGenerationToCapitalizationConvertStatement:{
			data:"GenerateDocumentInput",
			options:"GenerateDocumentOptionsInput"
		},
		capitalGenerateGenerationToMainWalletConvertStatement:{
			data:"GenerateDocumentInput",
			options:"GenerateDocumentOptionsInput"
		},
		capitalGenerateGenerationToProjectConvertStatement:{
			data:"GenerateDocumentInput",
			options:"GenerateDocumentOptionsInput"
		},
		capitalGenerateGetLoanDecision:{
			data:"GenerateDocumentInput",
			options:"GenerateDocumentOptionsInput"
		},
		capitalGenerateGetLoanStatement:{
			data:"GenerateDocumentInput",
			options:"GenerateDocumentOptionsInput"
		},
		capitalGenerateResultContributionAct:{
			data:"GenerateDocumentInput",
			options:"GenerateDocumentOptionsInput"
		},
		capitalGenerateResultContributionDecision:{
			data:"GenerateDocumentInput",
			options:"GenerateDocumentOptionsInput"
		},
		capitalGenerateResultContributionStatement:{
			data:"GenerateDocumentInput",
			options:"GenerateDocumentOptionsInput"
		},
		capitalImportContributor:{
			data:"ImportContributorInput"
		},
		capitalMakeClearance:{
			data:"MakeClearanceInput"
		},
		capitalOpenProject:{
			data:"OpenProjectInput"
		},
		capitalPushResult:{
			data:"PushResultInput"
		},
		capitalRefreshProgram:{
			data:"RefreshProgramInput"
		},
		capitalRefreshProject:{
			data:"RefreshProjectInput"
		},
		capitalRefreshSegment:{
			data:"RefreshSegmentInput"
		},
		capitalRegisterContributor:{
			data:"RegisterContributorInput"
		},
		capitalSetConfig:{
			data:"SetConfigInput"
		},
		capitalSetMaster:{
			data:"SetMasterInput"
		},
		capitalSetPlan:{
			data:"SetPlanInput"
		},
		capitalSignActAsChairman:{
			data:"SignActAsChairmanInput"
		},
		capitalSignActAsContributor:{
			data:"SignActAsContributorInput"
		},
		capitalStartProject:{
			data:"StartProjectInput"
		},
		capitalStartVoting:{
			data:"StartVotingInput"
		},
		capitalStopProject:{
			data:"StopProjectInput"
		},
		capitalSubmitVote:{
			data:"SubmitVoteInput"
		},
		capitalUpdateIssue:{
			data:"UpdateIssueInput"
		},
		capitalUpdateStory:{
			data:"UpdateStoryInput"
		},
		chairmanConfirmApprove:{
			data:"ConfirmApproveInput"
		},
		chairmanDeclineApprove:{
			data:"DeclineApproveInput"
		},
		chatcoopCreateAccount:{
			data:"CreateMatrixAccountInputDTO"
		},
		completeChairmanAgendaStep:{
			data:"ChairmanOnboardingAgendaInput"
		},
		completeChairmanGeneralMeetStep:{
			data:"ChairmanOnboardingGeneralMeetInput"
		},
		completeRequest:{
			data:"CompleteRequestInput"
		},
		confirmAgreement:{
			data:"ConfirmAgreementInput"
		},
		confirmReceiveOnRequest:{
			data:"ConfirmReceiveOnRequestInput"
		},
		confirmSupplyOnRequest:{
			data:"ConfirmSupplyOnRequestInput"
		},
		createAnnualGeneralMeet:{
			data:"CreateAnnualGeneralMeetInput"
		},
		createBranch:{
			data:"CreateBranchInput"
		},
		createChildOrder:{
			data:"CreateChildOrderInput"
		},
		createDepositPayment:{
			data:"CreateDepositPaymentInput"
		},
		createInitialPayment:{
			data:"CreateInitialPaymentInput"
		},
		createParentOffer:{
			data:"CreateParentOfferInput"
		},
		createProjectOfFreeDecision:{
			data:"CreateProjectFreeDecisionInput"
		},
		createWebPushSubscription:{
			data:"CreateSubscriptionInput"
		},
		createWithdraw:{
			data:"CreateWithdrawInput"
		},
		deactivateWebPushSubscriptionById:{
			data:"DeactivateSubscriptionInput"
		},
		declineAgreement:{
			data:"DeclineAgreementInput"
		},
		declineRequest:{
			data:"DeclineRequestInput"
		},
		deleteBranch:{
			data:"DeleteBranchInput"
		},
		deletePaymentMethod:{
			data:"DeletePaymentMethodInput"
		},
		deleteTrustedAccount:{
			data:"DeleteTrustedAccountInput"
		},
		deliverOnRequest:{
			data:"DeliverOnRequestInput"
		},
		disputeOnRequest:{
			data:"DisputeOnRequestInput"
		},
		editBranch:{
			data:"EditBranchInput"
		},
		generateAnnualGeneralMeetAgendaDocument:{
			data:"AnnualGeneralMeetingAgendaGenerateDocumentInput",
			options:"GenerateDocumentOptionsInput"
		},
		generateAnnualGeneralMeetDecisionDocument:{
			data:"AnnualGeneralMeetingDecisionGenerateDocumentInput",
			options:"GenerateDocumentOptionsInput"
		},
		generateAnnualGeneralMeetNotificationDocument:{
			data:"AnnualGeneralMeetingNotificationGenerateDocumentInput",
			options:"GenerateDocumentOptionsInput"
		},
		generateAssetContributionAct:{
			data:"AssetContributionActGenerateDocumentInput",
			options:"GenerateDocumentOptionsInput"
		},
		generateAssetContributionDecision:{
			data:"AssetContributionDecisionGenerateDocumentInput",
			options:"GenerateDocumentOptionsInput"
		},
		generateAssetContributionStatement:{
			data:"AssetContributionStatementGenerateDocumentInput",
			options:"GenerateDocumentOptionsInput"
		},
		generateBallotForAnnualGeneralMeetDocument:{
			data:"AnnualGeneralMeetingVotingBallotGenerateDocumentInput",
			options:"GenerateDocumentOptionsInput"
		},
		generateConvertToAxonStatement:{
			data:"ConvertToAxonStatementGenerateDocumentInput",
			options:"GenerateDocumentOptionsInput"
		},
		generateDocument:{
			input:"GenerateAnyDocumentInput"
		},
		generateFreeDecision:{
			data:"FreeDecisionGenerateDocumentInput",
			options:"GenerateDocumentOptionsInput"
		},
		generateParticipantApplication:{
			data:"ParticipantApplicationGenerateDocumentInput",
			options:"GenerateDocumentOptionsInput"
		},
		generateParticipantApplicationDecision:{
			data:"ParticipantApplicationDecisionGenerateDocumentInput",
			options:"GenerateDocumentOptionsInput"
		},
		generatePrivacyAgreement:{
			data:"GenerateDocumentInput",
			options:"GenerateDocumentOptionsInput"
		},
		generateProjectOfFreeDecision:{
			data:"ProjectFreeDecisionGenerateDocumentInput",
			options:"GenerateDocumentOptionsInput"
		},
		generateRegistrationDocuments:{
			data:"GenerateRegistrationDocumentsInput"
		},
		generateReturnByAssetAct:{
			data:"ReturnByAssetActGenerateDocumentInput",
			options:"GenerateDocumentOptionsInput"
		},
		generateReturnByAssetDecision:{
			data:"ReturnByAssetDecisionGenerateDocumentInput",
			options:"GenerateDocumentOptionsInput"
		},
		generateReturnByAssetStatement:{
			data:"ReturnByAssetStatementGenerateDocumentInput",
			options:"GenerateDocumentOptionsInput"
		},
		generateReturnByMoneyDecisionDocument:{
			data:"ReturnByMoneyDecisionGenerateDocumentInput",
			options:"GenerateDocumentOptionsInput"
		},
		generateReturnByMoneyStatementDocument:{
			data:"ReturnByMoneyGenerateDocumentInput",
			options:"GenerateDocumentOptionsInput"
		},
		generateSelectBranchDocument:{
			data:"SelectBranchGenerateDocumentInput",
			options:"GenerateDocumentOptionsInput"
		},
		generateSignatureAgreement:{
			data:"GenerateDocumentInput",
			options:"GenerateDocumentOptionsInput"
		},
		generateSovietDecisionOnAnnualMeetDocument:{
			data:"AnnualGeneralMeetingSovietDecisionGenerateDocumentInput",
			options:"GenerateDocumentOptionsInput"
		},
		generateUserAgreement:{
			data:"GenerateDocumentInput",
			options:"GenerateDocumentOptionsInput"
		},
		generateWalletAgreement:{
			data:"GenerateDocumentInput",
			options:"GenerateDocumentOptionsInput"
		},
		initSystem:{
			data:"Init"
		},
		installExtension:{
			data:"ExtensionInput"
		},
		installSystem:{
			data:"Install"
		},
		login:{
			data:"LoginInput"
		},
		logout:{
			data:"LogoutInput"
		},
		moderateRequest:{
			data:"ModerateRequestInput"
		},
		notifyOnAnnualGeneralMeet:{
			data:"NotifyOnAnnualGeneralMeetInput"
		},
		processConvertToAxonStatement:{
			data:"ProcessConvertToAxonStatementInput"
		},
		prohibitRequest:{
			data:"ProhibitRequestInput"
		},
		publishProjectOfFreeDecision:{
			data:"PublishProjectFreeDecisionInput"
		},
		publishRequest:{
			data:"PublishRequestInput"
		},
		receiveOnRequest:{
			data:"ReceiveOnRequestInput"
		},
		refresh:{
			data:"RefreshInput"
		},
		registerAccount:{
			data:"RegisterAccountInput"
		},
		registerParticipant:{
			data:"RegisterParticipantInput"
		},
		resetKey:{
			data:"ResetKeyInput"
		},
		restartAnnualGeneralMeet:{
			data:"RestartAnnualGeneralMeetInput"
		},
		selectBranch:{
			data:"SelectBranchInput"
		},
		sendAgreement:{
			data:"SendAgreementInput"
		},
		setPaymentStatus:{
			data:"SetPaymentStatusInput"
		},
		setWif:{
			data:"SetWifInput"
		},
		signByPresiderOnAnnualGeneralMeet:{
			data:"SignByPresiderOnAnnualGeneralMeetInput"
		},
		signBySecretaryOnAnnualGeneralMeet:{
			data:"SignBySecretaryOnAnnualGeneralMeetInput"
		},
		startInstall:{
			data:"StartInstallInput"
		},
		startResetKey:{
			data:"StartResetKeyInput"
		},
		supplyOnRequest:{
			data:"SupplyOnRequestInput"
		},
		triggerNotificationWorkflow:{
			data:"TriggerNotificationWorkflowInput"
		},
		uninstallExtension:{
			data:"UninstallExtensionInput"
		},
		unpublishRequest:{
			data:"UnpublishRequestInput"
		},
		updateAccount:{
			data:"UpdateAccountInput"
		},
		updateBankAccount:{
			data:"UpdateBankAccountInput"
		},
		updateExtension:{
			data:"ExtensionInput"
		},
		updateRequest:{
			data:"UpdateRequestInput"
		},
		updateSettings:{
			data:"UpdateSettingsInput"
		},
		updateSystem:{
			data:"Update"
		},
		verifyEmail:{
			data:"VerifyEmailInputDTO"
		},
		voteOnAnnualGeneralMeet:{
			data:"VoteOnAnnualGeneralMeetInput"
		}
	},
	NotificationWorkflowRecipientInput:{

	},
	NotifyOnAnnualGeneralMeetInput:{
		notification:"AnnualGeneralMeetingNotificationSignedDocumentInput"
	},
	OpenProjectInput:{

	},
	OrganizationDetailsInput:{

	},
	OrganizationType: "enum" as const,
	PaginationInput:{

	},
	ParticipantApplicationDecisionGenerateDocumentInput:{

	},
	ParticipantApplicationGenerateDocumentInput:{

	},
	ParticipantApplicationSignedDocumentInput:{
		meta:"ParticipantApplicationSignedMetaDocumentInput",
		signatures:"SignatureInfoInput"
	},
	ParticipantApplicationSignedMetaDocumentInput:{

	},
	PassportInput:{

	},
	PaymentDirection: "enum" as const,
	PaymentFiltersInput:{
		direction:"PaymentDirection",
		status:"PaymentStatus",
		type:"PaymentType"
	},
	PaymentStatus: "enum" as const,
	PaymentType: "enum" as const,
	ProcessConvertToAxonStatementInput:{
		signedDocument:"ConvertToAxonStatementSignedDocumentInput"
	},
	ProgramInvestStatus: "enum" as const,
	ProhibitRequestInput:{

	},
	ProjectFreeDecisionGenerateDocumentInput:{

	},
	ProjectFreeDecisionSignedDocumentInput:{
		meta:"ProjectFreeDecisionSignedMetaDocumentInput",
		signatures:"SignatureInfoInput"
	},
	ProjectFreeDecisionSignedMetaDocumentInput:{

	},
	ProjectStatus: "enum" as const,
	PublishProjectFreeDecisionInput:{
		document:"ProjectFreeDecisionSignedDocumentInput"
	},
	PublishRequestInput:{

	},
	PushResultInput:{
		statement:"SignedDigitalDocumentInput"
	},
	Query:{
		agreements:{
			filter:"AgreementFilter",
			options:"PaginationInput"
		},
		capitalCommit:{
			data:"GetCapitalCommitByHashInput"
		},
		capitalCommits:{
			filter:"CapitalCommitFilter",
			options:"PaginationInput"
		},
		capitalContributor:{
			data:"GetContributorInput"
		},
		capitalContributors:{
			filter:"CapitalContributorFilter",
			options:"PaginationInput"
		},
		capitalCycles:{
			filter:"CapitalCycleFilter",
			options:"PaginationInput"
		},
		capitalDebt:{
			data:"GetDebtInput"
		},
		capitalDebts:{
			filter:"DebtFilter",
			options:"PaginationInput"
		},
		capitalExpense:{
			data:"GetExpenseInput"
		},
		capitalExpenses:{
			filter:"ExpenseFilter",
			options:"PaginationInput"
		},
		capitalInvest:{
			data:"GetInvestInput"
		},
		capitalInvests:{
			filter:"CapitalInvestFilter",
			options:"PaginationInput"
		},
		capitalIssue:{
			data:"GetCapitalIssueByHashInput"
		},
		capitalIssues:{
			filter:"CapitalIssueFilter",
			options:"PaginationInput"
		},
		capitalProgramInvest:{
			data:"GetProgramInvestInput"
		},
		capitalProgramInvests:{
			filter:"CapitalInvestFilter",
			options:"PaginationInput"
		},
		capitalProject:{
			data:"GetProjectInput"
		},
		capitalProjectWithRelations:{
			data:"GetProjectWithRelationsInput"
		},
		capitalProjects:{
			filter:"CapitalProjectFilter",
			options:"PaginationInput"
		},
		capitalResult:{
			data:"GetResultInput"
		},
		capitalResults:{
			filter:"ResultFilter",
			options:"PaginationInput"
		},
		capitalSegment:{
			filter:"CapitalSegmentFilter"
		},
		capitalSegments:{
			filter:"CapitalSegmentFilter",
			options:"PaginationInput"
		},
		capitalState:{
			data:"GetCapitalConfigInput"
		},
		capitalStories:{
			filter:"CapitalStoryFilter",
			options:"PaginationInput"
		},
		capitalStory:{
			data:"GetCapitalStoryByHashInput"
		},
		capitalTimeEntries:{
			filter:"CapitalTimeEntriesFilter",
			options:"PaginationInput"
		},
		capitalTimeEntriesByIssues:{
			filter:"CapitalTimeEntriesFilter",
			options:"PaginationInput"
		},
		capitalTimeStats:{
			data:"CapitalTimeStatsInput",
			options:"PaginationInput"
		},
		capitalVote:{
			data:"GetVoteInput"
		},
		capitalVotes:{
			filter:"VoteFilter",
			options:"PaginationInput"
		},
		chairmanApproval:{

		},
		chairmanApprovals:{
			filter:"ApprovalFilter",
			options:"PaginationInput"
		},
		chatcoopCheckUsernameAvailability:{
			data:"CheckMatrixUsernameInput"
		},
		getAccount:{
			data:"GetAccountInput"
		},
		getAccounts:{
			data:"GetAccountsInput",
			options:"PaginationInput"
		},
		getActions:{
			filters:"ActionFiltersInput",
			pagination:"PaginationInput"
		},
		getBranches:{
			data:"GetBranchesInput"
		},
		getCapitalIssueLogs:{
			data:"GetCapitalIssueLogsInput",
			options:"PaginationInput"
		},
		getCapitalProjectLogs:{
			data:"GetCapitalLogsInput"
		},
		getCurrentTableStates:{
			filters:"CurrentTableStatesFiltersInput",
			pagination:"PaginationInput"
		},
		getDeltas:{
			filters:"DeltaFiltersInput",
			pagination:"PaginationInput"
		},
		getDocuments:{
			data:"GetDocumentsInput"
		},
		getExtensionLogs:{
			data:"GetExtensionLogsInput",
			options:"PaginationInput"
		},
		getExtensions:{
			data:"GetExtensionsInput"
		},
		getInstallationStatus:{
			data:"GetInstallationStatusInput"
		},
		getLedger:{
			data:"GetLedgerInput"
		},
		getLedgerHistory:{
			data:"GetLedgerHistoryInput"
		},
		getMeet:{
			data:"GetMeetInput"
		},
		getMeets:{
			data:"GetMeetsInput"
		},
		getPaymentMethods:{
			data:"GetPaymentMethodsInput"
		},
		getPayments:{
			data:"PaymentFiltersInput",
			options:"PaginationInput"
		},
		getProviderSubscriptionById:{

		},
		getUserWebPushSubscriptions:{
			data:"GetUserSubscriptionsInput"
		},
		onecoopGetDocuments:{
			data:"GetOneCoopDocumentsInput"
		},
		searchPrivateAccounts:{
			data:"SearchPrivateAccountsInput"
		}
	},
	ReceiveOnRequestInput:{
		document:"ReturnByAssetActSignedDocumentInput"
	},
	RefreshInput:{

	},
	RefreshProgramInput:{

	},
	RefreshProjectInput:{

	},
	RefreshSegmentInput:{

	},
	RegisterAccountInput:{
		entrepreneur_data:"CreateEntrepreneurDataInput",
		individual_data:"CreateIndividualDataInput",
		organization_data:"CreateOrganizationDataInput",
		type:"AccountType"
	},
	RegisterContributorInput:{
		contract:"SignedDigitalDocumentInput"
	},
	RegisterParticipantInput:{
		capitalization_agreement:"SignedDigitalDocumentInput",
		privacy_agreement:"SignedDigitalDocumentInput",
		signature_agreement:"SignedDigitalDocumentInput",
		statement:"ParticipantApplicationSignedDocumentInput",
		user_agreement:"SignedDigitalDocumentInput",
		wallet_agreement:"SignedDigitalDocumentInput"
	},
	RepresentedByInput:{

	},
	ResetKeyInput:{

	},
	RestartAnnualGeneralMeetInput:{
		new_close_at:"DateTime",
		new_open_at:"DateTime",
		newproposal:"AnnualGeneralMeetingAgendaSignedDocumentInput"
	},
	ResultFilter:{

	},
	ResultStatus: "enum" as const,
	ReturnByAssetActGenerateDocumentInput:{

	},
	ReturnByAssetActSignedDocumentInput:{
		meta:"ReturnByAssetActSignedMetaDocumentInput",
		signatures:"SignatureInfoInput"
	},
	ReturnByAssetActSignedMetaDocumentInput:{

	},
	ReturnByAssetDecisionGenerateDocumentInput:{

	},
	ReturnByAssetStatementGenerateDocumentInput:{
		request:"CommonRequestInput"
	},
	ReturnByAssetStatementSignedDocumentInput:{
		meta:"ReturnByAssetStatementSignedMetaDocumentInput",
		signatures:"SignatureInfoInput"
	},
	ReturnByAssetStatementSignedMetaDocumentInput:{
		request:"CommonRequestInput"
	},
	ReturnByMoneyDecisionGenerateDocumentInput:{

	},
	ReturnByMoneyGenerateDocumentInput:{

	},
	ReturnByMoneySignedDocumentInput:{
		meta:"ReturnByMoneySignedMetaDocumentInput",
		signatures:"SignatureInfoInput"
	},
	ReturnByMoneySignedMetaDocumentInput:{

	},
	SbpDataInput:{

	},
	SearchPrivateAccountsInput:{

	},
	SegmentStatus: "enum" as const,
	SelectBranchGenerateDocumentInput:{

	},
	SelectBranchInput:{
		document:"SelectBranchSignedDocumentInput"
	},
	SelectBranchSignedDocumentInput:{
		meta:"SelectBranchSignedMetaDocumentInput",
		signatures:"SignatureInfoInput"
	},
	SelectBranchSignedMetaDocumentInput:{

	},
	SendAgreementInput:{
		document:"SignedDigitalDocumentInput"
	},
	SetConfigInput:{
		config:"ConfigInput"
	},
	SetMasterInput:{

	},
	SetPaymentStatusInput:{
		status:"PaymentStatus"
	},
	SetPlanInput:{

	},
	SetVarsInput:{
		coopenomics_agreement:"AgreementVarInput",
		participant_application:"AgreementVarInput",
		privacy_agreement:"AgreementVarInput",
		signature_agreement:"AgreementVarInput",
		user_agreement:"AgreementVarInput",
		wallet_agreement:"AgreementVarInput"
	},
	SetWifInput:{

	},
	SignActAsChairmanInput:{
		act:"SignedDigitalDocumentInput"
	},
	SignActAsContributorInput:{
		act:"SignedDigitalDocumentInput"
	},
	SignByPresiderOnAnnualGeneralMeetInput:{
		presider_decision:"AnnualGeneralMeetingDecisionSignedDocumentInput"
	},
	SignBySecretaryOnAnnualGeneralMeetInput:{
		secretary_decision:"AnnualGeneralMeetingDecisionSignedDocumentInput"
	},
	SignatureInfoInput:{

	},
	SignedDigitalDocumentInput:{
		meta:"MetaDocumentInput",
		signatures:"SignatureInfoInput"
	},
	SovietMemberInput:{
		individual_data:"CreateSovietIndividualDataInput"
	},
	StartInstallInput:{

	},
	StartProjectInput:{

	},
	StartResetKeyInput:{

	},
	StartVotingInput:{

	},
	StopProjectInput:{

	},
	StoryStatus: "enum" as const,
	SubmitVoteInput:{
		votes:"VoteDistributionInput"
	},
	SupplyOnRequestInput:{
		document:"AssetContributionActSignedDocumentInput"
	},
	SystemStatus: "enum" as const,
	TriggerNotificationWorkflowInput:{
		payload:"JSONObject",
		to:"NotificationWorkflowRecipientInput"
	},
	UninstallExtensionInput:{

	},
	UnpublishRequestInput:{

	},
	Update:{
		organization_data:"UpdateOrganizationDataInput",
		vars:"VarsInput"
	},
	UpdateAccountInput:{
		entrepreneur_data:"UpdateEntrepreneurDataInput",
		individual_data:"UpdateIndividualDataInput",
		organization_data:"UpdateOrganizationDataInput"
	},
	UpdateBankAccountInput:{
		data:"BankAccountInput"
	},
	UpdateEntrepreneurDataInput:{
		country:"Country",
		details:"EntrepreneurDetailsInput"
	},
	UpdateIndividualDataInput:{
		passport:"PassportInput"
	},
	UpdateIssueInput:{
		priority:"IssuePriority",
		status:"IssueStatus"
	},
	UpdateOrganizationDataInput:{
		details:"OrganizationDetailsInput",
		represented_by:"RepresentedByInput"
	},
	UpdateRequestInput:{

	},
	UpdateSettingsInput:{

	},
	UpdateStoryInput:{
		status:"StoryStatus"
	},
	UserStatus: "enum" as const,
	VarsInput:{
		coopenomics_agreement:"AgreementInput",
		participant_application:"AgreementInput",
		privacy_agreement:"AgreementInput",
		signature_agreement:"AgreementInput",
		user_agreement:"AgreementInput",
		wallet_agreement:"AgreementInput"
	},
	VerifyEmailInputDTO:{

	},
	VoteDistributionInput:{

	},
	VoteFilter:{

	},
	VoteItemInput:{

	},
	VoteOnAnnualGeneralMeetInput:{
		ballot:"AnnualGeneralMeetingVotingBallotSignedDocumentInput",
		votes:"VoteItemInput"
	},
	WebPushSubscriptionDataInput:{
		keys:"WebPushSubscriptionKeysInput"
	},
	WebPushSubscriptionKeysInput:{

	}
}

export const ReturnTypes: Record<string,any> = {
	Account:{
		blockchain_account:"BlockchainAccount",
		participant_account:"ParticipantAccount",
		private_account:"PrivateAccount",
		provider_account:"MonoAccount",
		user_account:"UserAccount",
		username:"String"
	},
	AccountRamDelta:{
		account:"String",
		delta:"Int"
	},
	AccountResourceInfo:{
		available:"String",
		current_used:"String",
		last_usage_update_time:"String",
		max:"String",
		used:"String"
	},
	AccountsPaginationResult:{
		currentPage:"Int",
		items:"Account",
		totalCount:"Int",
		totalPages:"Int"
	},
	ActDetailAggregate:{
		action:"ExtendedBlockchainAction",
		documentAggregate:"DocumentAggregate"
	},
	ActionAuthorization:{
		actor:"String",
		permission:"String"
	},
	ActionReceipt:{
		abi_sequence:"Int",
		act_digest:"String",
		auth_sequence:"AuthSequence",
		code_sequence:"Int",
		global_sequence:"String",
		receiver:"String",
		recv_sequence:"String"
	},
	AgendaMeetPoint:{
		context:"String",
		decision:"String",
		title:"String"
	},
	AgendaWithDocuments:{
		action:"BlockchainAction",
		documents:"DocumentPackageAggregate",
		table:"BlockchainDecision"
	},
	Agreement:{
		_created_at:"DateTime",
		_id:"String",
		_updated_at:"DateTime",
		block_num:"Float",
		coopname:"String",
		document:"DocumentAggregate",
		draft_id:"Int",
		id:"Int",
		present:"Boolean",
		program_id:"Int",
		status:"AgreementStatus",
		type:"String",
		updated_at:"DateTime",
		username:"String",
		version:"Int"
	},
	AgreementVar:{
		protocol_day_month_year:"String",
		protocol_number:"String"
	},
	Approval:{
		_created_at:"DateTime",
		_id:"String",
		_updated_at:"DateTime",
		approval_hash:"String",
		approved_document:"DocumentAggregate",
		block_num:"Float",
		callback_action_approve:"String",
		callback_action_decline:"String",
		callback_contract:"String",
		coopname:"String",
		created_at:"DateTime",
		document:"DocumentAggregate",
		id:"Float",
		meta:"String",
		present:"Boolean",
		status:"ApprovalStatus",
		username:"String"
	},
	AuthSequence:{
		account:"String",
		sequence:"String"
	},
	Authority:{
		accounts:"PermissionLevelWeight",
		keys:"KeyWeight",
		threshold:"Int",
		waits:"WaitWeight"
	},
	BankAccount:{
		account_number:"String",
		bank_name:"String",
		card_number:"String",
		currency:"String",
		details:"BankAccountDetails"
	},
	BankAccountDetails:{
		bik:"String",
		corr:"String",
		kpp:"String"
	},
	BankPaymentMethod:{
		created_at:"DateTime",
		data:"BankAccount",
		is_default:"Boolean",
		method_id:"String",
		method_type:"String",
		updated_at:"DateTime",
		username:"String"
	},
	BaseCapitalProject:{
		_created_at:"DateTime",
		_id:"String",
		_updated_at:"DateTime",
		block_num:"Float",
		blockchain_status:"String",
		can_convert_to_project:"Boolean",
		coopname:"String",
		counts:"CapitalProjectCountsData",
		created_at:"String",
		crps:"CapitalProjectCrpsData",
		data:"String",
		description:"String",
		fact:"CapitalProjectFactPool",
		id:"Int",
		invite:"String",
		is_opened:"Boolean",
		is_planed:"Boolean",
		issue_counter:"Int",
		master:"String",
		membership:"CapitalProjectMembershipCrps",
		meta:"String",
		parent_hash:"String",
		parent_title:"String",
		permissions:"CapitalProjectPermissions",
		plan:"CapitalProjectPlanPool",
		prefix:"String",
		present:"Boolean",
		project_hash:"String",
		status:"ProjectStatus",
		title:"String",
		voting:"CapitalProjectVotingData"
	},
	BlockchainAccount:{
		account_name:"String",
		core_liquid_balance:"String",
		cpu_limit:"AccountResourceInfo",
		cpu_weight:"String",
		created:"String",
		head_block_num:"Int",
		head_block_time:"String",
		last_code_update:"String",
		net_limit:"AccountResourceInfo",
		net_weight:"String",
		permissions:"Permission",
		privileged:"Boolean",
		ram_quota:"Int",
		ram_usage:"Int",
		refund_request:"RefundRequest",
		rex_info:"String",
		self_delegated_bandwidth:"ResourceDelegationDTO",
		total_resources:"ResourceOverview",
		voter_info:"String"
	},
	BlockchainAction:{
		account:"String",
		account_ram_deltas:"AccountRamDelta",
		action_ordinal:"Int",
		authorization:"ActionAuthorization",
		block_id:"String",
		block_num:"Int",
		chain_id:"String",
		console:"String",
		context_free:"Boolean",
		creator_action_ordinal:"Int",
		data:"JSON",
		elapsed:"Int",
		global_sequence:"String",
		name:"String",
		receipt:"ActionReceipt",
		receiver:"String",
		transaction_id:"String"
	},
	BlockchainDecision:{
		approved:"Boolean",
		authorization:"SignedBlockchainDocument",
		authorized:"Boolean",
		authorized_by:"String",
		batch_id:"Float",
		callback_contract:"String",
		confirm_callback:"String",
		coopname:"String",
		created_at:"String",
		decline_callback:"String",
		expired_at:"String",
		hash:"String",
		id:"Float",
		meta:"String",
		statement:"SignedBlockchainDocument",
		type:"String",
		username:"String",
		username_certificate:"UserCertificateUnion",
		validated:"Boolean",
		votes_against:"String",
		votes_against_certificates:"UserCertificateUnion",
		votes_for:"String",
		votes_for_certificates:"UserCertificateUnion"
	},
	BlockchainInfoDTO:{
		block_cpu_limit:"Int",
		block_net_limit:"Int",
		chain_id:"String",
		fork_db_head_block_id:"String",
		fork_db_head_block_num:"Int",
		head_block_id:"String",
		head_block_num:"Int",
		head_block_producer:"String",
		head_block_time:"String",
		last_irreversible_block_id:"String",
		last_irreversible_block_num:"Int",
		last_irreversible_block_time:"String",
		server_version:"String",
		server_version_string:"String",
		virtual_block_cpu_limit:"Int",
		virtual_block_net_limit:"Int"
	},
	BoardMember:{
		first_name:"String",
		is_chairman:"Boolean",
		last_name:"String",
		middle_name:"String",
		username:"String"
	},
	Branch:{
		bank_account:"BankPaymentMethod",
		braname:"String",
		city:"String",
		coopname:"String",
		country:"String",
		details:"OrganizationDetails",
		email:"String",
		fact_address:"String",
		full_address:"String",
		full_name:"String",
		phone:"String",
		represented_by:"RepresentedBy",
		short_name:"String",
		trusted:"Individual",
		trustee:"Individual",
		type:"String"
	},
	CapitalCommit:{
		_created_at:"DateTime",
		_id:"String",
		_updated_at:"DateTime",
		amounts:"CapitalCommitAmounts",
		block_num:"Float",
		blockchain_status:"String",
		commit_hash:"String",
		coopname:"String",
		created_at:"String",
		description:"String",
		display_name:"String",
		id:"Int",
		meta:"String",
		present:"Boolean",
		project:"BaseCapitalProject",
		project_hash:"String",
		status:"CommitStatus",
		username:"String"
	},
	CapitalCommitAmounts:{
		authors_base_pool:"String",
		authors_bonus_pool:"String",
		contributors_bonus_pool:"String",
		creators_base_pool:"String",
		creators_bonus_pool:"String",
		creators_hours:"String",
		hour_cost:"String",
		total_contribution:"String",
		total_generation_pool:"String"
	},
	CapitalConfigObject:{
		authors_voting_percent:"Float",
		coordinator_bonus_percent:"Float",
		coordinator_invite_validity_days:"Float",
		creators_voting_percent:"Float",
		energy_decay_rate_per_day:"Float",
		energy_gain_coefficient:"Float",
		expense_pool_percent:"Float",
		level_depth_base:"Float",
		level_growth_coefficient:"Float",
		voting_period_in_days:"Float"
	},
	CapitalContributor:{
		_created_at:"DateTime",
		_id:"String",
		_updated_at:"DateTime",
		about:"String",
		appendixes:"String",
		block_num:"Float",
		blockchain_status:"String",
		contract:"DocumentAggregate",
		contributed_as_author:"String",
		contributed_as_contributor:"String",
		contributed_as_coordinator:"String",
		contributed_as_creator:"String",
		contributed_as_investor:"String",
		contributed_as_propertor:"String",
		contributor_hash:"String",
		coopname:"String",
		created_at:"String",
		debt_amount:"String",
		display_name:"String",
		energy:"Float",
		hours_per_day:"Float",
		id:"Int",
		is_external_contract:"Boolean",
		last_energy_update:"String",
		level:"Int",
		memo:"String",
		present:"Boolean",
		rate_per_hour:"String",
		status:"ContributorStatus",
		username:"String"
	},
	CapitalCycle:{
		_created_at:"DateTime",
		_id:"String",
		_updated_at:"DateTime",
		block_num:"Float",
		end_date:"DateTime",
		name:"String",
		present:"Boolean",
		start_date:"DateTime",
		status:"CycleStatus"
	},
	CapitalDebt:{
		_created_at:"DateTime",
		_id:"String",
		_updated_at:"DateTime",
		amount:"Float",
		approved_statement:"DocumentAggregate",
		authorization:"DocumentAggregate",
		block_num:"Int",
		blockchain_status:"String",
		coopname:"String",
		debt_hash:"String",
		id:"Int",
		memo:"String",
		present:"Boolean",
		project_hash:"String",
		repaid_at:"String",
		statement:"DocumentAggregate",
		status:"DebtStatus",
		username:"String"
	},
	CapitalExpense:{
		_created_at:"DateTime",
		_id:"String",
		_updated_at:"DateTime",
		amount:"String",
		approved_statement:"DocumentAggregate",
		authorization:"DocumentAggregate",
		block_num:"Int",
		blockchain_status:"String",
		coopname:"String",
		description:"String",
		expense_hash:"String",
		expense_statement:"DocumentAggregate",
		fund_id:"Float",
		id:"Int",
		present:"Boolean",
		project_hash:"String",
		spended_at:"String",
		status:"ExpenseStatus",
		username:"String"
	},
	CapitalInvest:{
		_created_at:"DateTime",
		_id:"String",
		_updated_at:"DateTime",
		amount:"Float",
		block_num:"Int",
		blockchain_status:"String",
		coopname:"String",
		coordinator:"String",
		coordinator_amount:"Float",
		id:"Int",
		invest_hash:"String",
		invested_at:"String",
		present:"Boolean",
		project_hash:"String",
		statement:"String",
		status:"InvestStatus",
		username:"String"
	},
	CapitalIssue:{
		_created_at:"DateTime",
		_id:"String",
		_updated_at:"DateTime",
		block_num:"Float",
		created_by:"String",
		creators:"String",
		cycle_id:"String",
		description:"String",
		estimate:"Int",
		id:"String",
		issue_hash:"String",
		metadata:"JSON",
		permissions:"CapitalIssuePermissions",
		present:"Boolean",
		priority:"IssuePriority",
		project_hash:"String",
		sort_order:"Int",
		status:"IssueStatus",
		submaster:"String",
		title:"String"
	},
	CapitalIssuePermissions:{
		can_change_status:"Boolean",
		can_delete_issue:"Boolean",
		can_edit_issue:"Boolean",
		can_set_done:"Boolean",
		can_set_on_review:"Boolean",
		has_clearance:"Boolean",
		is_guest:"Boolean"
	},
	CapitalLog:{
		_id:"String",
		coopname:"String",
		created_at:"DateTime",
		entity_id:"String",
		entity_type:"LogEntityType",
		event_type:"LogEventType",
		initiator:"String",
		message:"String",
		metadata:"JSON",
		project_hash:"String",
		reference_id:"String"
	},
	CapitalProgramInvest:{
		_created_at:"DateTime",
		_id:"String",
		_updated_at:"DateTime",
		amount:"Float",
		block_num:"Int",
		blockchain_status:"String",
		coopname:"String",
		id:"Int",
		invest_hash:"String",
		invested_at:"String",
		present:"Boolean",
		statement:"DocumentAggregate",
		status:"ProgramInvestStatus",
		username:"String"
	},
	CapitalProject:{
		_created_at:"DateTime",
		_id:"String",
		_updated_at:"DateTime",
		block_num:"Float",
		blockchain_status:"String",
		can_convert_to_project:"Boolean",
		components:"CapitalProjectComponent",
		coopname:"String",
		counts:"CapitalProjectCountsData",
		created_at:"String",
		crps:"CapitalProjectCrpsData",
		data:"String",
		description:"String",
		fact:"CapitalProjectFactPool",
		id:"Int",
		invite:"String",
		is_opened:"Boolean",
		is_planed:"Boolean",
		issue_counter:"Int",
		master:"String",
		membership:"CapitalProjectMembershipCrps",
		meta:"String",
		parent_hash:"String",
		parent_title:"String",
		permissions:"CapitalProjectPermissions",
		plan:"CapitalProjectPlanPool",
		prefix:"String",
		present:"Boolean",
		project_hash:"String",
		status:"ProjectStatus",
		title:"String",
		voting:"CapitalProjectVotingData"
	},
	CapitalProjectComponent:{
		_created_at:"DateTime",
		_id:"String",
		_updated_at:"DateTime",
		block_num:"Float",
		blockchain_status:"String",
		can_convert_to_project:"Boolean",
		coopname:"String",
		counts:"CapitalProjectCountsData",
		created_at:"String",
		crps:"CapitalProjectCrpsData",
		data:"String",
		description:"String",
		fact:"CapitalProjectFactPool",
		id:"Int",
		invite:"String",
		is_opened:"Boolean",
		is_planed:"Boolean",
		issue_counter:"Int",
		master:"String",
		membership:"CapitalProjectMembershipCrps",
		meta:"String",
		parent_hash:"String",
		parent_title:"String",
		permissions:"CapitalProjectPermissions",
		plan:"CapitalProjectPlanPool",
		prefix:"String",
		present:"Boolean",
		project_hash:"String",
		status:"ProjectStatus",
		title:"String",
		voting:"CapitalProjectVotingData"
	},
	CapitalProjectCountsData:{
		total_authors:"Int",
		total_commits:"Int",
		total_contributors:"Int",
		total_coordinators:"Int",
		total_creators:"Int",
		total_investors:"Int",
		total_propertors:"Int",
		total_unique_participants:"Int"
	},
	CapitalProjectCrpsData:{
		author_base_cumulative_reward_per_share:"Float",
		author_bonus_cumulative_reward_per_share:"Float",
		contributor_cumulative_reward_per_share:"Float",
		total_capital_contributors_shares:"String"
	},
	CapitalProjectFactPool:{
		accumulated_expense_pool:"String",
		authors_base_pool:"String",
		authors_bonus_pool:"String",
		contributors_bonus_pool:"String",
		coordinators_base_pool:"String",
		coordinators_investment_pool:"String",
		creators_base_pool:"String",
		creators_bonus_pool:"String",
		creators_hours:"Int",
		hour_cost:"String",
		invest_pool:"String",
		program_invest_pool:"String",
		property_base_pool:"String",
		return_base_percent:"Float",
		target_expense_pool:"String",
		total:"String",
		total_contribution:"String",
		total_generation_pool:"String",
		total_received_investments:"String",
		total_returned_investments:"String",
		use_invest_percent:"Float",
		used_expense_pool:"String"
	},
	CapitalProjectMembershipCrps:{
		available:"String",
		converted_funds:"String",
		cumulative_reward_per_share:"Float",
		distributed:"String",
		funded:"String",
		total_shares:"String"
	},
	CapitalProjectPermissions:{
		can_change_project_status:"Boolean",
		can_delete_project:"Boolean",
		can_edit_project:"Boolean",
		can_manage_authors:"Boolean",
		can_manage_issues:"Boolean",
		can_set_master:"Boolean",
		can_set_plan:"Boolean",
		has_clearance:"Boolean",
		is_guest:"Boolean",
		pending_clearance:"Boolean"
	},
	CapitalProjectPlanPool:{
		authors_base_pool:"String",
		authors_bonus_pool:"String",
		contributors_bonus_pool:"String",
		coordinators_base_pool:"String",
		coordinators_investment_pool:"String",
		creators_base_pool:"String",
		creators_bonus_pool:"String",
		creators_hours:"Int",
		hour_cost:"String",
		invest_pool:"String",
		program_invest_pool:"String",
		return_base_percent:"Float",
		target_expense_pool:"String",
		total:"String",
		total_generation_pool:"String",
		total_received_investments:"String",
		use_invest_percent:"Float"
	},
	CapitalProjectTimeStats:{
		available_hours:"Float",
		contributor_hash:"String",
		pending_hours:"Float",
		project_hash:"String",
		project_name:"String",
		total_committed_hours:"Float",
		total_uncommitted_hours:"Float"
	},
	CapitalProjectVotingAmounts:{
		active_voting_amount:"String",
		authors_bonuses_on_voting:"String",
		authors_equal_per_author:"String",
		authors_equal_spread:"String",
		creators_bonuses_on_voting:"String",
		creators_direct_spread:"String",
		equal_voting_amount:"String",
		total_voting_pool:"String"
	},
	CapitalProjectVotingData:{
		amounts:"CapitalProjectVotingAmounts",
		authors_voting_percent:"Float",
		creators_voting_percent:"Float",
		total_voters:"Int",
		votes_received:"Int",
		voting_deadline:"String"
	},
	CapitalResult:{
		_created_at:"DateTime",
		_id:"String",
		_updated_at:"DateTime",
		act:"DocumentAggregate",
		authorization:"DocumentAggregate",
		block_num:"Float",
		blockchain_status:"String",
		coopname:"String",
		created_at:"String",
		debt_amount:"String",
		id:"Int",
		present:"Boolean",
		project_hash:"String",
		result_hash:"String",
		statement:"DocumentAggregate",
		status:"ResultStatus",
		total_amount:"String",
		username:"String"
	},
	CapitalSegment:{
		_created_at:"DateTime",
		_id:"String",
		_updated_at:"DateTime",
		author_base:"String",
		author_bonus:"String",
		block_num:"Float",
		capital_contributor_shares:"String",
		contributor_bonus:"String",
		coopname:"String",
		coordinator_base:"String",
		coordinator_investments:"String",
		creator_base:"String",
		creator_bonus:"String",
		debt_amount:"String",
		debt_settled:"String",
		direct_creator_bonus:"String",
		display_name:"String",
		equal_author_bonus:"String",
		has_vote:"Boolean",
		id:"Int",
		investor_amount:"String",
		investor_base:"String",
		is_author:"Boolean",
		is_completed:"Boolean",
		is_contributor:"Boolean",
		is_coordinator:"Boolean",
		is_creator:"Boolean",
		is_investor:"Boolean",
		is_propertor:"Boolean",
		is_votes_calculated:"Boolean",
		last_author_base_reward_per_share:"Float",
		last_author_bonus_reward_per_share:"Float",
		last_contributor_reward_per_share:"Float",
		last_known_coordinators_investment_pool:"String",
		last_known_creators_base_pool:"String",
		last_known_invest_pool:"String",
		present:"Boolean",
		project_hash:"String",
		property_base:"String",
		provisional_amount:"String",
		result:"CapitalResult",
		status:"SegmentStatus",
		total_segment_base_cost:"String",
		total_segment_bonus_cost:"String",
		total_segment_cost:"String",
		username:"String",
		value:"String",
		voting_bonus:"String"
	},
	CapitalState:{
		_created_at:"DateTime",
		_id:"String",
		_updated_at:"DateTime",
		block_num:"Float",
		config:"CapitalConfigObject",
		coopname:"String",
		global_available_invest_pool:"String",
		present:"Boolean",
		program_membership_available:"String",
		program_membership_cumulative_reward_per_share:"Float",
		program_membership_distributed:"String",
		program_membership_funded:"String"
	},
	CapitalStory:{
		_created_at:"DateTime",
		_id:"String",
		_updated_at:"DateTime",
		block_num:"Float",
		coopname:"String",
		created_by:"String",
		description:"String",
		issue_hash:"String",
		present:"Boolean",
		project_hash:"String",
		sort_order:"Int",
		status:"StoryStatus",
		story_hash:"String",
		title:"String"
	},
	CapitalTimeEntriesByIssues:{
		available_hours:"Float",
		committed_hours:"Float",
		contributor_hash:"String",
		contributor_name:"String",
		coopname:"String",
		issue_hash:"String",
		issue_title:"String",
		pending_hours:"Float",
		project_hash:"String",
		project_name:"String",
		total_hours:"Float",
		uncommitted_hours:"Float"
	},
	CapitalTimeEntry:{
		_created_at:"String",
		_id:"String",
		_updated_at:"String",
		commit_hash:"String",
		contributor_hash:"String",
		coopname:"String",
		date:"String",
		hours:"Float",
		is_committed:"Boolean",
		issue_hash:"String",
		project_hash:"String"
	},
	CapitalTimeStats:{
		currentPage:"Float",
		items:"CapitalProjectTimeStats",
		totalCount:"Float",
		totalPages:"Float"
	},
	CapitalVote:{
		_created_at:"DateTime",
		_id:"String",
		_updated_at:"DateTime",
		amount:"String",
		block_num:"Float",
		coopname:"String",
		id:"Int",
		present:"Boolean",
		project_hash:"String",
		recipient:"String",
		recipient_display_name:"String",
		voted_at:"String",
		voter:"String",
		voter_display_name:"String"
	},
	ChairmanOnboardingState:{
		general_meet_done:"Boolean",
		onboarding_expire_at:"String",
		onboarding_general_meet_hash:"String",
		onboarding_init_at:"String",
		onboarding_participant_application_hash:"String",
		onboarding_privacy_agreement_hash:"String",
		onboarding_signature_agreement_hash:"String",
		onboarding_user_agreement_hash:"String",
		onboarding_voskhod_membership_hash:"String",
		onboarding_wallet_agreement_hash:"String",
		participant_application_done:"Boolean",
		privacy_agreement_done:"Boolean",
		signature_agreement_done:"Boolean",
		user_agreement_done:"Boolean",
		voskhod_membership_done:"Boolean",
		wallet_agreement_done:"Boolean"
	},
	ChartOfAccountsItem:{
		available:"String",
		blocked:"String",
		displayId:"String",
		id:"Int",
		name:"String",
		writeoff:"String"
	},
	ContactsDTO:{
		chairman:"PublicChairman",
		details:"OrganizationDetails",
		email:"String",
		full_address:"String",
		full_name:"String",
		phone:"String"
	},
	CooperativeOperatorAccount:{
		active_participants_count:"Float",
		announce:"String",
		coop_type:"String",
		created_at:"String",
		description:"String",
		document:"SignedBlockchainDocument",
		initial:"String",
		is_branched:"Boolean",
		is_cooperative:"Boolean",
		is_enrolled:"Boolean",
		meta:"String",
		minimum:"String",
		org_initial:"String",
		org_minimum:"String",
		org_registration:"String",
		parent_username:"String",
		referer:"String",
		registered_at:"String",
		registration:"String",
		registrator:"String",
		status:"String",
		storages:"String",
		type:"String",
		username:"String",
		verifications:"Verification"
	},
	CreateSubscriptionResponse:{
		message:"String",
		subscription:"WebPushSubscriptionDto",
		success:"Boolean"
	},
	CreateWithdrawResponse:{
		withdraw_hash:"String"
	},
	CreatedProjectFreeDecision:{
		decision:"String",
		id:"String",
		question:"String",
		title:"String"
	},
	CurrentInstanceDTO:{
		blockchain_status:"String",
		description:"String",
		domain:"String",
		image:"String",
		is_delegated:"Boolean",
		is_valid:"Boolean",
		progress:"Float",
		status:"InstanceStatus",
		title:"String"
	},
	CurrentTableState:{
		block_num:"Float",
		code:"String",
		created_at:"DateTime",
		primary_key:"String",
		scope:"String",
		table:"String",
		value:"JSON"
	},
	DateTime: `scalar.DateTime` as const,
	DecisionDetailAggregate:{
		action:"ExtendedBlockchainAction",
		documentAggregate:"DocumentAggregate",
		votes_against:"ExtendedBlockchainAction",
		votes_for:"ExtendedBlockchainAction"
	},
	Delta:{
		block_id:"String",
		block_num:"Float",
		chain_id:"String",
		code:"String",
		created_at:"DateTime",
		id:"String",
		present:"Boolean",
		primary_key:"String",
		scope:"String",
		table:"String",
		value:"JSON"
	},
	Desktop:{
		authorizedHome:"String",
		coopname:"String",
		layout:"String",
		nonAuthorizedHome:"String",
		workspaces:"DesktopWorkspace"
	},
	DesktopConfig:{
		defaultRoute:"String",
		icon:"String",
		name:"String",
		title:"String"
	},
	DesktopWorkspace:{
		defaultRoute:"String",
		extension_name:"String",
		icon:"String",
		name:"String",
		title:"String"
	},
	DocumentAggregate:{
		document:"SignedDigitalDocument",
		hash:"String",
		rawDocument:"GeneratedDocument"
	},
	DocumentPackageAggregate:{
		acts:"ActDetailAggregate",
		decision:"DecisionDetailAggregate",
		links:"DocumentAggregate",
		statement:"StatementDetailAggregate"
	},
	DocumentsAggregatePaginationResult:{
		currentPage:"Int",
		items:"DocumentPackageAggregate",
		totalCount:"Int",
		totalPages:"Int"
	},
	Entrepreneur:{
		birthdate:"String",
		city:"String",
		country:"String",
		details:"EntrepreneurDetails",
		email:"String",
		first_name:"String",
		full_address:"String",
		last_name:"String",
		middle_name:"String",
		phone:"String",
		username:"String"
	},
	EntrepreneurCertificate:{
		first_name:"String",
		inn:"String",
		last_name:"String",
		middle_name:"String",
		type:"AccountType",
		username:"String"
	},
	EntrepreneurDetails:{
		inn:"String",
		ogrn:"String"
	},
	ExtendedBlockchainAction:{
		account:"String",
		account_ram_deltas:"AccountRamDelta",
		action_ordinal:"Int",
		actor_certificate:"UserCertificateUnion",
		authorization:"ActionAuthorization",
		block_id:"String",
		block_num:"Int",
		chain_id:"String",
		console:"String",
		context_free:"Boolean",
		creator_action_ordinal:"Int",
		data:"JSON",
		elapsed:"Int",
		global_sequence:"String",
		name:"String",
		receipt:"ActionReceipt",
		receiver:"String",
		transaction_id:"String"
	},
	Extension:{
		config:"JSON",
		created_at:"DateTime",
		description:"String",
		desktops:"DesktopConfig",
		enabled:"Boolean",
		external_url:"String",
		image:"String",
		instructions:"String",
		is_available:"Boolean",
		is_builtin:"Boolean",
		is_installed:"Boolean",
		is_internal:"Boolean",
		name:"String",
		readme:"String",
		schema:"JSON",
		tags:"String",
		title:"String",
		updated_at:"DateTime"
	},
	ExtensionLog:{
		created_at:"DateTime",
		data:"String",
		extension_local_id:"Float",
		id:"Float",
		name:"String",
		updated_at:"DateTime"
	},
	ExtensionLogsPaginationResult:{
		currentPage:"Int",
		items:"ExtensionLog",
		totalCount:"Int",
		totalPages:"Int"
	},
	GatewayPayment:{
		blockchain_data:"JSON",
		can_change_status:"Boolean",
		coopname:"String",
		created_at:"DateTime",
		direction:"PaymentDirection",
		direction_label:"String",
		expired_at:"DateTime",
		formatted_amount:"String",
		hash:"String",
		id:"ID",
		income_hash:"String",
		is_final:"Boolean",
		memo:"String",
		message:"String",
		outcome_hash:"String",
		payment_details:"PaymentDetails",
		payment_method_id:"String",
		provider:"String",
		quantity:"Float",
		statement:"JSON",
		status:"PaymentStatus",
		status_label:"String",
		symbol:"String",
		type:"PaymentType",
		type_label:"String",
		updated_at:"DateTime",
		username:"String",
		username_certificate:"UserCertificateUnion"
	},
	GenerateRegistrationDocumentsOutput:{
		account_type:"AccountType",
		documents:"GeneratedRegistrationDocument",
		username:"String"
	},
	GeneratedDocument:{
		binary:"String",
		full_title:"String",
		hash:"String",
		html:"String",
		meta:"JSON"
	},
	GeneratedRegistrationDocument:{
		agreement_type:"String",
		checkbox_text:"String",
		document:"GeneratedDocument",
		id:"String",
		is_blockchain_agreement:"Boolean",
		link_text:"String",
		link_to_statement:"Boolean",
		order:"Int",
		title:"String"
	},
	Individual:{
		birthdate:"String",
		email:"String",
		first_name:"String",
		full_address:"String",
		last_name:"String",
		middle_name:"String",
		passport:"Passport",
		phone:"String",
		username:"String"
	},
	IndividualCertificate:{
		first_name:"String",
		last_name:"String",
		middle_name:"String",
		type:"AccountType",
		username:"String"
	},
	InstallationStatus:{
		has_private_account:"Boolean",
		init_by_server:"Boolean",
		organization_data:"OrganizationWithBankAccount"
	},
	JSON: `scalar.JSON` as const,
	JSONObject: `scalar.JSONObject` as const,
	KeyWeight:{
		key:"String",
		weight:"Int"
	},
	LedgerHistoryResponse:{
		currentPage:"Int",
		items:"LedgerOperation",
		totalCount:"Int",
		totalPages:"Int"
	},
	LedgerOperation:{
		account_id:"Int",
		action:"String",
		comment:"String",
		coopname:"String",
		created_at:"DateTime",
		global_sequence:"Int",
		hash:"String",
		quantity:"String",
		username:"String"
	},
	LedgerState:{
		chartOfAccounts:"ChartOfAccountsItem",
		coopname:"String"
	},
	MatrixAccountStatusResponseDTO:{
		hasAccount:"Boolean",
		iframeUrl:"String",
		matrixUsername:"String"
	},
	Meet:{
		authorization:"DocumentAggregate",
		close_at:"DateTime",
		coopname:"String",
		created_at:"DateTime",
		current_quorum_percent:"Float",
		cycle:"Float",
		decision1:"DocumentAggregate",
		decision2:"DocumentAggregate",
		hash:"String",
		id:"Float",
		initiator:"String",
		initiator_certificate:"UserCertificateUnion",
		level:"String",
		notified_users:"String",
		open_at:"DateTime",
		presider:"String",
		presider_certificate:"UserCertificateUnion",
		proposal:"DocumentAggregate",
		quorum_passed:"Boolean",
		quorum_percent:"Float",
		secretary:"String",
		secretary_certificate:"UserCertificateUnion",
		signed_ballots:"Float",
		status:"String",
		type:"String"
	},
	MeetAggregate:{
		hash:"String",
		pre:"MeetPreProcessing",
		processed:"MeetProcessed",
		processing:"MeetProcessing"
	},
	MeetPreProcessing:{
		agenda:"AgendaMeetPoint",
		close_at:"DateTime",
		coopname:"String",
		hash:"String",
		initiator:"String",
		initiator_certificate:"UserCertificateUnion",
		open_at:"DateTime",
		presider:"String",
		presider_certificate:"UserCertificateUnion",
		proposal:"DocumentAggregate",
		secretary:"String",
		secretary_certificate:"UserCertificateUnion"
	},
	MeetProcessed:{
		coopname:"String",
		decision:"SignedDigitalDocument",
		decisionAggregate:"DocumentAggregate",
		hash:"String",
		presider:"String",
		presider_certificate:"UserCertificateUnion",
		quorum_passed:"Boolean",
		quorum_percent:"Int",
		results:"MeetQuestionResult",
		secretary:"String",
		secretary_certificate:"UserCertificateUnion",
		signed_ballots:"Int"
	},
	MeetProcessing:{
		extendedStatus:"ExtendedMeetStatus",
		hash:"String",
		isVoted:"Boolean",
		meet:"Meet",
		questions:"Question"
	},
	MeetQuestionResult:{
		accepted:"Boolean",
		context:"String",
		decision:"String",
		number:"Int",
		question_id:"Int",
		title:"String",
		votes_abstained:"Int",
		votes_against:"Int",
		votes_for:"Int"
	},
	MonoAccount:{
		email:"String",
		has_account:"Boolean",
		initial_order:"String",
		is_email_verified:"Boolean",
		is_registered:"Boolean",
		message:"String",
		public_key:"String",
		referer:"String",
		role:"String",
		status:"UserStatus",
		subscriber_hash:"String",
		subscriber_id:"String",
		type:"String",
		username:"String"
	},
	Mutation:{
		acceptChildOrder:"Transaction",
		addParticipant:"Account",
		addPaymentMethod:"PaymentMethod",
		addTrustedAccount:"Branch",
		cancelRequest:"Transaction",
		capitalAddAuthor:"CapitalProject",
		capitalApproveCommit:"CapitalCommit",
		capitalCalculateVotes:"CapitalSegment",
		capitalCloseProject:"CapitalProject",
		capitalCompleteVoting:"Transaction",
		capitalConvertSegment:"CapitalSegment",
		capitalCreateCommit:"Transaction",
		capitalCreateCycle:"CapitalCycle",
		capitalCreateDebt:"Transaction",
		capitalCreateExpense:"Transaction",
		capitalCreateIssue:"CapitalIssue",
		capitalCreateProgramProperty:"Transaction",
		capitalCreateProject:"Transaction",
		capitalCreateProjectInvest:"Transaction",
		capitalCreateProjectProperty:"Transaction",
		capitalCreateStory:"CapitalStory",
		capitalDeclineCommit:"CapitalCommit",
		capitalDeleteIssue:"Boolean",
		capitalDeleteProject:"Transaction",
		capitalDeleteStory:"Boolean",
		capitalEditContributor:"CapitalContributor",
		capitalEditProject:"Transaction",
		capitalFundProgram:"Transaction",
		capitalFundProject:"Transaction",
		capitalGenerateAppendixGenerationAgreement:"GeneratedDocument",
		capitalGenerateCapitalizationAgreement:"GeneratedDocument",
		capitalGenerateCapitalizationMoneyInvestStatement:"GeneratedDocument",
		capitalGenerateCapitalizationPropertyInvestAct:"GeneratedDocument",
		capitalGenerateCapitalizationPropertyInvestDecision:"GeneratedDocument",
		capitalGenerateCapitalizationPropertyInvestStatement:"GeneratedDocument",
		capitalGenerateCapitalizationToMainWalletConvertStatement:"GeneratedDocument",
		capitalGenerateExpenseDecision:"GeneratedDocument",
		capitalGenerateExpenseStatement:"GeneratedDocument",
		capitalGenerateGenerationAgreement:"GeneratedDocument",
		capitalGenerateGenerationMoneyInvestStatement:"GeneratedDocument",
		capitalGenerateGenerationMoneyReturnUnusedStatement:"GeneratedDocument",
		capitalGenerateGenerationPropertyInvestAct:"GeneratedDocument",
		capitalGenerateGenerationPropertyInvestDecision:"GeneratedDocument",
		capitalGenerateGenerationPropertyInvestStatement:"GeneratedDocument",
		capitalGenerateGenerationToCapitalizationConvertStatement:"GeneratedDocument",
		capitalGenerateGenerationToMainWalletConvertStatement:"GeneratedDocument",
		capitalGenerateGenerationToProjectConvertStatement:"GeneratedDocument",
		capitalGenerateGetLoanDecision:"GeneratedDocument",
		capitalGenerateGetLoanStatement:"GeneratedDocument",
		capitalGenerateResultContributionAct:"GeneratedDocument",
		capitalGenerateResultContributionDecision:"GeneratedDocument",
		capitalGenerateResultContributionStatement:"GeneratedDocument",
		capitalImportContributor:"Transaction",
		capitalMakeClearance:"Transaction",
		capitalOpenProject:"CapitalProject",
		capitalPushResult:"CapitalSegment",
		capitalRefreshProgram:"Transaction",
		capitalRefreshProject:"Transaction",
		capitalRefreshSegment:"CapitalSegment",
		capitalRegisterContributor:"Transaction",
		capitalSetConfig:"Transaction",
		capitalSetMaster:"Transaction",
		capitalSetPlan:"CapitalProject",
		capitalSignActAsChairman:"CapitalSegment",
		capitalSignActAsContributor:"CapitalSegment",
		capitalStartProject:"CapitalProject",
		capitalStartVoting:"Transaction",
		capitalStopProject:"CapitalProject",
		capitalSubmitVote:"Transaction",
		capitalUpdateIssue:"CapitalIssue",
		capitalUpdateStory:"CapitalStory",
		chairmanConfirmApprove:"Approval",
		chairmanDeclineApprove:"Approval",
		chatcoopCreateAccount:"Boolean",
		completeChairmanAgendaStep:"ChairmanOnboardingState",
		completeChairmanGeneralMeetStep:"ChairmanOnboardingState",
		completeRequest:"Transaction",
		confirmAgreement:"Transaction",
		confirmReceiveOnRequest:"Transaction",
		confirmSupplyOnRequest:"Transaction",
		createAnnualGeneralMeet:"MeetAggregate",
		createBranch:"Branch",
		createChildOrder:"Transaction",
		createDepositPayment:"GatewayPayment",
		createInitialPayment:"GatewayPayment",
		createParentOffer:"Transaction",
		createProjectOfFreeDecision:"CreatedProjectFreeDecision",
		createWebPushSubscription:"CreateSubscriptionResponse",
		createWithdraw:"CreateWithdrawResponse",
		deactivateWebPushSubscriptionById:"Boolean",
		declineAgreement:"Transaction",
		declineRequest:"Transaction",
		deleteBranch:"Boolean",
		deletePaymentMethod:"Boolean",
		deleteTrustedAccount:"Branch",
		deliverOnRequest:"Transaction",
		disputeOnRequest:"Transaction",
		editBranch:"Branch",
		generateAnnualGeneralMeetAgendaDocument:"GeneratedDocument",
		generateAnnualGeneralMeetDecisionDocument:"GeneratedDocument",
		generateAnnualGeneralMeetNotificationDocument:"GeneratedDocument",
		generateAssetContributionAct:"GeneratedDocument",
		generateAssetContributionDecision:"GeneratedDocument",
		generateAssetContributionStatement:"GeneratedDocument",
		generateBallotForAnnualGeneralMeetDocument:"GeneratedDocument",
		generateConvertToAxonStatement:"GeneratedDocument",
		generateDocument:"GeneratedDocument",
		generateFreeDecision:"GeneratedDocument",
		generateParticipantApplication:"GeneratedDocument",
		generateParticipantApplicationDecision:"GeneratedDocument",
		generatePrivacyAgreement:"GeneratedDocument",
		generateProjectOfFreeDecision:"GeneratedDocument",
		generateRegistrationDocuments:"GenerateRegistrationDocumentsOutput",
		generateReturnByAssetAct:"GeneratedDocument",
		generateReturnByAssetDecision:"GeneratedDocument",
		generateReturnByAssetStatement:"GeneratedDocument",
		generateReturnByMoneyDecisionDocument:"GeneratedDocument",
		generateReturnByMoneyStatementDocument:"GeneratedDocument",
		generateSelectBranchDocument:"GeneratedDocument",
		generateSignatureAgreement:"GeneratedDocument",
		generateSovietDecisionOnAnnualMeetDocument:"GeneratedDocument",
		generateUserAgreement:"GeneratedDocument",
		generateWalletAgreement:"GeneratedDocument",
		initSystem:"SystemInfo",
		installExtension:"Extension",
		installSystem:"SystemInfo",
		login:"RegisteredAccount",
		logout:"Boolean",
		moderateRequest:"Transaction",
		notifyOnAnnualGeneralMeet:"MeetAggregate",
		processConvertToAxonStatement:"Boolean",
		prohibitRequest:"Transaction",
		publishProjectOfFreeDecision:"Boolean",
		publishRequest:"Transaction",
		receiveOnRequest:"Transaction",
		refresh:"RegisteredAccount",
		registerAccount:"RegisteredAccount",
		registerParticipant:"Account",
		resetKey:"Boolean",
		restartAnnualGeneralMeet:"MeetAggregate",
		selectBranch:"Boolean",
		sendAgreement:"Transaction",
		setPaymentStatus:"GatewayPayment",
		setWif:"Boolean",
		signByPresiderOnAnnualGeneralMeet:"MeetAggregate",
		signBySecretaryOnAnnualGeneralMeet:"MeetAggregate",
		startInstall:"StartInstallResult",
		startResetKey:"Boolean",
		supplyOnRequest:"Transaction",
		triggerNotificationWorkflow:"Boolean",
		uninstallExtension:"Boolean",
		unpublishRequest:"Transaction",
		updateAccount:"Account",
		updateBankAccount:"PaymentMethod",
		updateExtension:"Extension",
		updateRequest:"Transaction",
		updateSettings:"Settings",
		updateSystem:"SystemInfo",
		verifyEmail:"Boolean",
		voteOnAnnualGeneralMeet:"MeetAggregate"
	},
	OneCoopDocumentOutput:{
		action:"String",
		block_num:"Int",
		data:"JSON",
		hash:"String",
		package:"String"
	},
	OneCoopDocumentsResponse:{
		current_page:"Int",
		items:"OneCoopDocumentOutput",
		max_block_num:"Int",
		total_count:"Int",
		total_pages:"Int"
	},
	Organization:{
		city:"String",
		country:"String",
		details:"OrganizationDetails",
		email:"String",
		fact_address:"String",
		full_address:"String",
		full_name:"String",
		phone:"String",
		represented_by:"RepresentedBy",
		short_name:"String",
		type:"String",
		username:"String"
	},
	OrganizationCertificate:{
		inn:"String",
		ogrn:"String",
		represented_by:"RepresentedByCertificate",
		short_name:"String",
		type:"AccountType",
		username:"String"
	},
	OrganizationDetails:{
		inn:"String",
		kpp:"String",
		ogrn:"String"
	},
	OrganizationWithBankAccount:{
		bank_account:"BankAccount",
		city:"String",
		country:"String",
		details:"OrganizationDetails",
		email:"String",
		fact_address:"String",
		full_address:"String",
		full_name:"String",
		phone:"String",
		represented_by:"RepresentedBy",
		short_name:"String",
		type:"String",
		username:"String"
	},
	PaginatedActionsPaginationResult:{
		currentPage:"Int",
		items:"BlockchainAction",
		totalCount:"Int",
		totalPages:"Int"
	},
	PaginatedAgreementsPaginationResult:{
		currentPage:"Int",
		items:"Agreement",
		totalCount:"Int",
		totalPages:"Int"
	},
	PaginatedCapitalCommitsPaginationResult:{
		currentPage:"Int",
		items:"CapitalCommit",
		totalCount:"Int",
		totalPages:"Int"
	},
	PaginatedCapitalContributorsPaginationResult:{
		currentPage:"Int",
		items:"CapitalContributor",
		totalCount:"Int",
		totalPages:"Int"
	},
	PaginatedCapitalCyclesPaginationResult:{
		currentPage:"Int",
		items:"CapitalCycle",
		totalCount:"Int",
		totalPages:"Int"
	},
	PaginatedCapitalDebtsPaginationResult:{
		currentPage:"Int",
		items:"CapitalDebt",
		totalCount:"Int",
		totalPages:"Int"
	},
	PaginatedCapitalExpensesPaginationResult:{
		currentPage:"Int",
		items:"CapitalExpense",
		totalCount:"Int",
		totalPages:"Int"
	},
	PaginatedCapitalInvestsPaginationResult:{
		currentPage:"Int",
		items:"CapitalInvest",
		totalCount:"Int",
		totalPages:"Int"
	},
	PaginatedCapitalIssuesPaginationResult:{
		currentPage:"Int",
		items:"CapitalIssue",
		totalCount:"Int",
		totalPages:"Int"
	},
	PaginatedCapitalLogsPaginationResult:{
		currentPage:"Int",
		items:"CapitalLog",
		totalCount:"Int",
		totalPages:"Int"
	},
	PaginatedCapitalProgramInvestsPaginationResult:{
		currentPage:"Int",
		items:"CapitalProgramInvest",
		totalCount:"Int",
		totalPages:"Int"
	},
	PaginatedCapitalProjectsPaginationResult:{
		currentPage:"Int",
		items:"CapitalProject",
		totalCount:"Int",
		totalPages:"Int"
	},
	PaginatedCapitalResultsPaginationResult:{
		currentPage:"Int",
		items:"CapitalResult",
		totalCount:"Int",
		totalPages:"Int"
	},
	PaginatedCapitalSegmentsPaginationResult:{
		currentPage:"Int",
		items:"CapitalSegment",
		totalCount:"Int",
		totalPages:"Int"
	},
	PaginatedCapitalStoriesPaginationResult:{
		currentPage:"Int",
		items:"CapitalStory",
		totalCount:"Int",
		totalPages:"Int"
	},
	PaginatedCapitalTimeEntriesByIssuesPaginationResult:{
		currentPage:"Int",
		items:"CapitalTimeEntriesByIssues",
		totalCount:"Int",
		totalPages:"Int"
	},
	PaginatedCapitalTimeEntriesPaginationResult:{
		currentPage:"Int",
		items:"CapitalTimeEntry",
		totalCount:"Int",
		totalPages:"Int"
	},
	PaginatedCapitalVotesPaginationResult:{
		currentPage:"Int",
		items:"CapitalVote",
		totalCount:"Int",
		totalPages:"Int"
	},
	PaginatedChairmanApprovalsPaginationResult:{
		currentPage:"Int",
		items:"Approval",
		totalCount:"Int",
		totalPages:"Int"
	},
	PaginatedCurrentTableStatesPaginationResult:{
		currentPage:"Int",
		items:"CurrentTableState",
		totalCount:"Int",
		totalPages:"Int"
	},
	PaginatedDeltasPaginationResult:{
		currentPage:"Int",
		items:"Delta",
		totalCount:"Int",
		totalPages:"Int"
	},
	PaginatedGatewayPaymentsPaginationResult:{
		currentPage:"Int",
		items:"GatewayPayment",
		totalCount:"Int",
		totalPages:"Int"
	},
	ParticipantAccount:{
		braname:"String",
		created_at:"DateTime",
		has_vote:"Boolean",
		initial_amount:"String",
		is_initial:"Boolean",
		is_minimum:"Boolean",
		last_min_pay:"DateTime",
		last_update:"DateTime",
		minimum_amount:"String",
		status:"String",
		type:"String",
		username:"String"
	},
	Passport:{
		code:"String",
		issued_at:"String",
		issued_by:"String",
		number:"Int",
		series:"Int"
	},
	PaymentDetails:{
		amount_plus_fee:"String",
		amount_without_fee:"String",
		data:"JSON",
		fact_fee_percent:"Float",
		fee_amount:"String",
		fee_percent:"Float",
		tolerance_percent:"Float"
	},
	PaymentMethod:{
		created_at:"DateTime",
		data:"PaymentMethodData",
		is_default:"Boolean",
		method_id:"String",
		method_type:"String",
		updated_at:"DateTime",
		username:"String"
	},
	PaymentMethodData:{
		"...on BankAccount":"BankAccount",
		"...on SbpAccount":"SbpAccount"
	},
	PaymentMethodPaginationResult:{
		currentPage:"Int",
		items:"PaymentMethod",
		totalCount:"Int",
		totalPages:"Int"
	},
	Permission:{
		parent:"String",
		perm_name:"String",
		required_auth:"Authority"
	},
	PermissionLevel:{
		actor:"String",
		permission:"String"
	},
	PermissionLevelWeight:{
		permission:"PermissionLevel",
		weight:"Int"
	},
	PrivateAccount:{
		entrepreneur_data:"Entrepreneur",
		individual_data:"Individual",
		organization_data:"Organization",
		type:"AccountType"
	},
	PrivateAccountSearchData:{
		"...on Entrepreneur":"Entrepreneur",
		"...on Individual":"Individual",
		"...on Organization":"Organization"
	},
	PrivateAccountSearchResult:{
		data:"PrivateAccountSearchData",
		highlightedFields:"String",
		score:"Float",
		type:"String"
	},
	ProviderSubscription:{
		created_at:"String",
		domain_valid:"Boolean",
		expires_at:"String",
		id:"Float",
		installation_progress:"Float",
		instance_status:"String",
		instance_username:"String",
		is_trial:"Boolean",
		next_payment_due:"String",
		period_days:"Float",
		price:"Float",
		specific_data:"JSON",
		started_at:"String",
		status:"String",
		subscriber_id:"Float",
		subscriber_username:"String",
		subscription_type_description:"String",
		subscription_type_id:"Float",
		subscription_type_name:"String",
		updated_at:"String"
	},
	PublicChairman:{
		first_name:"String",
		last_name:"String",
		middle_name:"String"
	},
	Query:{
		agreements:"PaginatedAgreementsPaginationResult",
		capitalCommit:"CapitalCommit",
		capitalCommits:"PaginatedCapitalCommitsPaginationResult",
		capitalContributor:"CapitalContributor",
		capitalContributors:"PaginatedCapitalContributorsPaginationResult",
		capitalCycles:"PaginatedCapitalCyclesPaginationResult",
		capitalDebt:"CapitalDebt",
		capitalDebts:"PaginatedCapitalDebtsPaginationResult",
		capitalExpense:"CapitalExpense",
		capitalExpenses:"PaginatedCapitalExpensesPaginationResult",
		capitalInvest:"CapitalInvest",
		capitalInvests:"PaginatedCapitalInvestsPaginationResult",
		capitalIssue:"CapitalIssue",
		capitalIssues:"PaginatedCapitalIssuesPaginationResult",
		capitalProgramInvest:"CapitalProgramInvest",
		capitalProgramInvests:"PaginatedCapitalProgramInvestsPaginationResult",
		capitalProject:"CapitalProject",
		capitalProjectWithRelations:"CapitalProject",
		capitalProjects:"PaginatedCapitalProjectsPaginationResult",
		capitalResult:"CapitalResult",
		capitalResults:"PaginatedCapitalResultsPaginationResult",
		capitalSegment:"CapitalSegment",
		capitalSegments:"PaginatedCapitalSegmentsPaginationResult",
		capitalState:"CapitalState",
		capitalStories:"PaginatedCapitalStoriesPaginationResult",
		capitalStory:"CapitalStory",
		capitalTimeEntries:"PaginatedCapitalTimeEntriesPaginationResult",
		capitalTimeEntriesByIssues:"PaginatedCapitalTimeEntriesByIssuesPaginationResult",
		capitalTimeStats:"CapitalTimeStats",
		capitalVote:"CapitalVote",
		capitalVotes:"PaginatedCapitalVotesPaginationResult",
		chairmanApproval:"Approval",
		chairmanApprovals:"PaginatedChairmanApprovalsPaginationResult",
		chatcoopCheckUsernameAvailability:"Boolean",
		chatcoopGetAccountStatus:"MatrixAccountStatusResponseDTO",
		getAccount:"Account",
		getAccounts:"AccountsPaginationResult",
		getActions:"PaginatedActionsPaginationResult",
		getAgenda:"AgendaWithDocuments",
		getBranches:"Branch",
		getCapitalIssueLogs:"PaginatedCapitalLogsPaginationResult",
		getCapitalProjectLogs:"PaginatedCapitalLogsPaginationResult",
		getChairmanOnboardingState:"ChairmanOnboardingState",
		getCurrentInstance:"CurrentInstanceDTO",
		getCurrentTableStates:"PaginatedCurrentTableStatesPaginationResult",
		getDeltas:"PaginatedDeltasPaginationResult",
		getDesktop:"Desktop",
		getDocuments:"DocumentsAggregatePaginationResult",
		getExtensionLogs:"ExtensionLogsPaginationResult",
		getExtensions:"Extension",
		getInstallationStatus:"InstallationStatus",
		getLedger:"LedgerState",
		getLedgerHistory:"LedgerHistoryResponse",
		getMeet:"MeetAggregate",
		getMeets:"MeetAggregate",
		getPaymentMethods:"PaymentMethodPaginationResult",
		getPayments:"PaginatedGatewayPaymentsPaginationResult",
		getProviderSubscriptionById:"ProviderSubscription",
		getProviderSubscriptions:"ProviderSubscription",
		getSystemInfo:"SystemInfo",
		getUserWebPushSubscriptions:"WebPushSubscriptionDto",
		getWebPushSubscriptionStats:"SubscriptionStatsDto",
		onecoopGetDocuments:"OneCoopDocumentsResponse",
		searchPrivateAccounts:"PrivateAccountSearchResult"
	},
	Question:{
		context:"String",
		coopname:"String",
		counter_votes_abstained:"Float",
		counter_votes_against:"Float",
		counter_votes_for:"Float",
		decision:"String",
		id:"Float",
		meet_id:"Float",
		number:"Float",
		title:"String",
		voters_abstained:"String",
		voters_against:"String",
		voters_for:"String"
	},
	RefundRequest:{
		cpu_amount:"String",
		net_amount:"String",
		owner:"String",
		request_time:"String"
	},
	RegisteredAccount:{
		account:"Account",
		tokens:"Tokens"
	},
	RepresentedBy:{
		based_on:"String",
		first_name:"String",
		last_name:"String",
		middle_name:"String",
		position:"String"
	},
	RepresentedByCertificate:{
		first_name:"String",
		last_name:"String",
		middle_name:"String",
		position:"String"
	},
	ResourceDelegationDTO:{
		cpu_weight:"String",
		from:"String",
		net_weight:"String",
		to:"String"
	},
	ResourceOverview:{
		cpu_weight:"String",
		net_weight:"String",
		owner:"String",
		ram_bytes:"Int"
	},
	SbpAccount:{
		phone:"String"
	},
	Settings:{
		authorized_default_route:"String",
		authorized_default_workspace:"String",
		coopname:"String",
		created_at:"DateTime",
		non_authorized_default_route:"String",
		non_authorized_default_workspace:"String",
		provider_name:"String",
		updated_at:"DateTime"
	},
	SignatureInfo:{
		id:"Float",
		is_valid:"Boolean",
		meta:"JSON",
		public_key:"String",
		signature:"String",
		signed_at:"String",
		signed_hash:"String",
		signer:"String",
		signer_certificate:"UserCertificateUnion"
	},
	SignedBlockchainDocument:{
		doc_hash:"String",
		hash:"String",
		meta:"String",
		meta_hash:"String",
		signatures:"SignatureInfo",
		version:"String"
	},
	SignedDigitalDocument:{
		doc_hash:"String",
		hash:"String",
		meta:"JSON",
		meta_hash:"String",
		signatures:"SignatureInfo",
		version:"String"
	},
	StartInstallResult:{
		coopname:"String",
		install_code:"String"
	},
	StatementDetailAggregate:{
		action:"ExtendedBlockchainAction",
		documentAggregate:"DocumentAggregate"
	},
	SubscriptionStatsDto:{
		active:"Int",
		inactive:"Int",
		total:"Int",
		uniqueUsers:"Int"
	},
	Symbols:{
		root_govern_precision:"Float",
		root_govern_symbol:"String",
		root_precision:"Float",
		root_symbol:"String"
	},
	SystemInfo:{
		blockchain_account:"BlockchainAccount",
		blockchain_info:"BlockchainInfoDTO",
		board_members:"BoardMember",
		contacts:"ContactsDTO",
		cooperator_account:"CooperativeOperatorAccount",
		coopname:"String",
		is_providered:"Boolean",
		is_unioned:"Boolean",
		settings:"Settings",
		symbols:"Symbols",
		system_status:"SystemStatus",
		union_link:"String",
		vars:"Vars"
	},
	Token:{
		expires:"DateTime",
		token:"String"
	},
	Tokens:{
		access:"Token",
		refresh:"Token"
	},
	Transaction:{
		chain:"JSON",
		request:"JSON",
		resolved:"JSON",
		response:"JSON",
		returns:"JSON",
		revisions:"JSON",
		signatures:"JSON",
		signer:"JSON",
		transaction:"JSON"
	},
	UserAccount:{
		meta:"String",
		referer:"String",
		registered_at:"String",
		registrator:"String",
		status:"String",
		storages:"String",
		type:"String",
		username:"String",
		verifications:"Verification"
	},
	UserCertificateUnion:{
		"...on EntrepreneurCertificate":"EntrepreneurCertificate",
		"...on IndividualCertificate":"IndividualCertificate",
		"...on OrganizationCertificate":"OrganizationCertificate"
	},
	Vars:{
		confidential_email:"String",
		confidential_link:"String",
		contact_email:"String",
		coopenomics_agreement:"AgreementVar",
		coopname:"String",
		full_abbr:"String",
		full_abbr_dative:"String",
		full_abbr_genitive:"String",
		name:"String",
		participant_application:"AgreementVar",
		passport_request:"String",
		privacy_agreement:"AgreementVar",
		short_abbr:"String",
		signature_agreement:"AgreementVar",
		statute_link:"String",
		user_agreement:"AgreementVar",
		wallet_agreement:"AgreementVar",
		website:"String"
	},
	Verification:{
		created_at:"String",
		is_verified:"Boolean",
		last_update:"String",
		notice:"String",
		procedure:"String",
		verificator:"String"
	},
	WaitWeight:{
		wait_sec:"Int",
		weight:"Int"
	},
	WebPushSubscriptionDto:{
		authKey:"String",
		createdAt:"DateTime",
		endpoint:"String",
		id:"String",
		isActive:"Boolean",
		p256dhKey:"String",
		updatedAt:"DateTime",
		userAgent:"String",
		username:"String"
	}
}

export const Ops = {
query: "Query" as const,
	mutation: "Mutation" as const
}