export * as WalletAgreement from './1.WalletAgreement'
export * as RegulationElectronicSignature from './2.RegulationElectronicSignature'
export * as PrivacyPolicy from './3.PrivacyPolicy'
export * as UserAgreement from './4.UserAgreement'
export * as CoopenomicsAgreement from './50.CoopenomicsAgreement'
export * as ParticipantApplication from './100.ParticipantApplication'
export * as DecisionOfParticipantApplication from './501.DecisionOfParticipantApplication'
export * as SelectBranchStatement from './101.SelectBranchStatement'
export * as ProjectFreeDecision from './599.ProjectFreeDecision'
export * as FreeDecision from './600.FreeDecision'
export * as AssetContributionStatement from './700.assetContributionStatement'
export * as ReturnByAssetStatement from './800.returnByAssetStatement'

export * as AssetContributionDecision from './701.assetContributionDecision'
export * as ReturnByAssetDecision from './801.returnByAssetDecision'

export * as AssetContributionAct from './702.assetContributionAct'
export * as ReturnByAssetAct from './802.returnByAssetAct'
export * as InvestmentAgreement from './1000.InvestmentAgreement'
export * as InvestByResultStatement from './1001.InvestByResultStatement'
export * as InvestByResultAct from './1002.InvestByResultAct'
export * as InvestByMoneyStatement from './1005.InvestByMoneyStatement'
export * as InvestMembershipConvertation from './1010.InvestMembershipConvertation'

export * from './registry'
