import { boot } from 'quasar/wrappers';

import AccountBadge from 'src/shared/ui/domain/AccountBadge/AccountBadge.vue';
import ActivityTimeline from 'src/shared/ui/domain/ActivityTimeline/ActivityTimeline.vue';
import AmountInput from 'src/shared/ui/domain/AmountInput/AmountInput.vue';
import CommandPalette from 'src/shared/ui/domain/CommandPalette/CommandPalette.vue';
import ContactSheet from 'src/shared/ui/domain/ContactSheet/ContactSheet.vue';
import DataRow from 'src/shared/ui/domain/DataRow/DataRow.vue';
import DetailsDrawer from 'src/shared/ui/domain/DetailsDrawer/DetailsDrawer.vue';
import DocumentPreview from 'src/shared/ui/domain/DocumentPreview/DocumentPreview.vue';
import DocumentRow from 'src/shared/ui/domain/DocumentRow/DocumentRow.vue';
import DocumentSignatures from 'src/shared/ui/domain/DocumentSignatures/DocumentSignatures.vue';
import FileUploader from 'src/shared/ui/domain/FileUploader/FileUploader.vue';
import FilterBar from 'src/shared/ui/domain/FilterBar/FilterBar.vue';
import IdentityPanel from 'src/shared/ui/domain/IdentityPanel/IdentityPanel.vue';
import NotificationCenter from 'src/shared/ui/domain/NotificationCenter/NotificationCenter.vue';
import OtpInput from 'src/shared/ui/domain/OtpInput/OtpInput.vue';
import PersonCard from 'src/shared/ui/domain/PersonCard/PersonCard.vue';
import SignatureCard from 'src/shared/ui/domain/SignatureCard/SignatureCard.vue';
import VerticalStepper from 'src/shared/ui/domain/VerticalStepper/VerticalStepper.vue';
import BaseButton from 'src/shared/ui/base/BaseButton/BaseButton.vue';
import BaseInput from 'src/shared/ui/base/BaseInput/BaseInput.vue';
import BaseSelect from 'src/shared/ui/base/BaseSelect/BaseSelect.vue';
import BaseCard from 'src/shared/ui/base/BaseCard/BaseCard.vue';
import BaseTable from 'src/shared/ui/base/BaseTable/BaseTable.vue';
import BaseChip from 'src/shared/ui/base/BaseChip/BaseChip.vue';
import BaseBadge from 'src/shared/ui/base/BaseBadge/BaseBadge.vue';
import BaseDialog from 'src/shared/ui/base/BaseDialog/BaseDialog.vue';
import BaseBanner from 'src/shared/ui/base/BaseBanner/BaseBanner.vue';
import BaseForm from 'src/shared/ui/base/BaseForm/BaseForm.vue';
import EmptyState from 'src/shared/ui/base/EmptyState/EmptyState.vue';
import Avatar from 'src/shared/ui/base/Avatar/Avatar.vue';
import ThemeToggle from 'src/shared/ui/base/ThemeToggle/ThemeToggle.vue';

export default boot(({ app }) => {
  app.component('AccountBadge', AccountBadge);
  app.component('ActivityTimeline', ActivityTimeline);
  app.component('AmountInput', AmountInput);
  app.component('CommandPalette', CommandPalette);
  app.component('ContactSheet', ContactSheet);
  app.component('DataRow', DataRow);
  app.component('DetailsDrawer', DetailsDrawer);
  app.component('DocumentPreview', DocumentPreview);
  app.component('DocumentRow', DocumentRow);
  app.component('DocumentSignatures', DocumentSignatures);
  app.component('FileUploader', FileUploader);
  app.component('FilterBar', FilterBar);
  app.component('IdentityPanel', IdentityPanel);
  app.component('NotificationCenter', NotificationCenter);
  app.component('OtpInput', OtpInput);
  app.component('PersonCard', PersonCard);
  app.component('SignatureCard', SignatureCard);
  app.component('VerticalStepper', VerticalStepper);
  app.component('BaseButton', BaseButton);
  app.component('BaseInput', BaseInput);
  app.component('BaseSelect', BaseSelect);
  app.component('BaseCard', BaseCard);
  app.component('BaseTable', BaseTable);
  app.component('BaseChip', BaseChip);
  app.component('BaseBadge', BaseBadge);
  app.component('BaseDialog', BaseDialog);
  app.component('BaseBanner', BaseBanner);
  app.component('BaseForm', BaseForm);
  app.component('EmptyState', EmptyState);
  app.component('Avatar', Avatar);
  app.component('ThemeToggle', ThemeToggle);
});
