
version: '3'

services:
  node:
    image: dicoop/blockchain_v5.1.1:dev
    container_name: node
    ports:
      - "8888:8888"
      - "9876:9876"
      - "8070:8070"
    volumes:
      - ./components/boot/blockchain-data:/mnt/dev/data
      - ./components/boot/wallet-data:/root/eosio-wallet
      - ./components/contracts/build/contracts:/contracts
      - ./components/boot/src/configs:/mnt/dev/config
    command: >
      /bin/bash -c "/usr/local/bin/nodeos -d /mnt/dev/data --config-dir /mnt/dev/config --genesis-json /mnt/dev/config/genesis.json"
    restart: unless-stopped
      
  mongo:
    image: mongo:latest
    container_name: mongo
    restart: always
    volumes:
      - mongo_data:/data/db
    ports:
      - 127.0.0.1:27017:27017
    entrypoint: >
      /bin/bash -c "
      mongod --replSet rs0 --bind_ip_all & 
      sleep 5;
      mongosh --eval '
        try {
          rs.status();
        } catch (e) {
          rs.initiate({
            _id: \"rs0\",
            members: [{ _id: 0, host: \"mongo:27017\" }]
          });
        }
      ';
      tail -f /dev/null"

  monoredis:
    image: redis:latest
    container_name: monoredis
    restart: always
    ports:
      - 127.0.0.1:6379:6379

  postgres:
    image: postgres:latest
    container_name: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres!23!23
      POSTGRES_DB: voskhod
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - 127.0.0.1:5532:5432

  coopback:
    container_name: coopback
    build:
      context: ./
      dockerfile: components/controller/Dockerfile
    image: coopback
    env_file:
      - ./components/controller/.env
    restart: unless-stopped
    volumes:
      - ./:/app
    working_dir: /app
    command: pnpm --filter @coopenomics/controller run dev
  

  cooparser:
    container_name: cooparser
    build:
      context: ./
      dockerfile: components/parser/Dockerfile
    image: cooparser
    env_file:
      - ./components/parser/.env
    restart: unless-stopped
    volumes:
      - ./:/app
    working_dir: /app
    command: pnpm --filter @coopenomics/parser run dev

  desktop:
    container_name: desktop
    build:
      context: ./
      dockerfile: components/desktop/Dockerfile
    image: desktop
    env_file:
      - ./components/desktop/.env
    restart: unless-stopped
    ports:
      - 127.0.0.1:2999:2999
    volumes:
      - ./:/app
    working_dir: /app
    command: pnpm --filter @coopenomics/desktop run dev

volumes:
  mongo_data:
  postgres_data:
