/* eslint-disable */

export const AllTypesProps: Record<string,any> = {
	AccountType: "enum" as const,
	AddPaymentMethodInput:{
		bank_transfer_data:"BankAccountInput",
		sbp_data:"SbpDataInput"
	},
	AddTrustedAccountInput:{

	},
	AgreementInput:{

	},
	AgreementStatus: "enum" as const,
	AgreementVarInput:{

	},
	ApprovalStatus: "enum" as const,
	BankAccountDetailsInput:{

	},
	BankAccountInput:{
		details:"BankAccountDetailsInput"
	},
	CandidateStatus: "enum" as const,
	CapitalLogFilterInput:{
		date_from:"DateTime",
		date_to:"DateTime",
		event_types:"LogEventType"
	},
	CapitalStoryContentFormat: "enum" as const,
	CommitStatus: "enum" as const,
	ContributorStatus: "enum" as const,
	Country: "enum" as const,
	CreateBranchInput:{

	},
	CreateEntrepreneurDataInput:{
		bank_account:"BankAccountInput",
		country:"Country",
		details:"EntrepreneurDetailsInput"
	},
	CreateIndividualDataInput:{
		passport:"PassportInput"
	},
	CreateInitOrganizationDataInput:{
		bank_account:"BankAccountInput",
		details:"OrganizationDetailsInput",
		represented_by:"RepresentedByInput",
		type:"OrganizationType"
	},
	CreateOrganizationDataInput:{
		bank_account:"BankAccountInput",
		details:"OrganizationDetailsInput",
		represented_by:"RepresentedByInput",
		type:"OrganizationType"
	},
	CreateSovietIndividualDataInput:{
		passport:"PassportInput"
	},
	CreateSubscriptionInput:{
		subscription:"WebPushSubscriptionDataInput"
	},
	CycleStatus: "enum" as const,
	DateTime: `scalar.DateTime` as const,
	DeactivateSubscriptionInput:{

	},
	DebtStatus: "enum" as const,
	DeleteBranchInput:{

	},
	DeletePaymentMethodInput:{

	},
	DeleteTrustedAccountInput:{

	},
	EditBranchInput:{

	},
	EntrepreneurDetailsInput:{

	},
	ExpenseStatus: "enum" as const,
	ExtendedMeetStatus: "enum" as const,
	ExtensionInput:{
		config:"JSON",
		created_at:"DateTime",
		updated_at:"DateTime"
	},
	GenerateDocumentOptionsInput:{

	},
	GetAccountInput:{

	},
	GetAccountsInput:{

	},
	GetBranchesInput:{

	},
	GetCapitalIssueLogsInput:{

	},
	GetCapitalLogsInput:{
		filter:"CapitalLogFilterInput",
		pagination:"PaginationInput"
	},
	GetExtensionLogsInput:{
		createdFrom:"DateTime",
		createdTo:"DateTime"
	},
	GetExtensionsInput:{

	},
	GetInstallationStatusInput:{

	},
	GetPaymentMethodsInput:{

	},
	GetUserSubscriptionsInput:{

	},
	Init:{
		organization_data:"CreateInitOrganizationDataInput"
	},
	Install:{
		soviet:"SovietMemberInput",
		vars:"SetVarsInput"
	},
	InvestStatus: "enum" as const,
	IssuePriority: "enum" as const,
	IssueStatus: "enum" as const,
	JSON: `scalar.JSON` as const,
	LogEntityType: "enum" as const,
	LogEventType: "enum" as const,
	Mutation:{
		addPaymentMethod:{
			data:"AddPaymentMethodInput"
		},
		addTrustedAccount:{
			data:"AddTrustedAccountInput"
		},
		createBranch:{
			data:"CreateBranchInput"
		},
		createWebPushSubscription:{
			data:"CreateSubscriptionInput"
		},
		deactivateWebPushSubscriptionById:{
			data:"DeactivateSubscriptionInput"
		},
		deleteBranch:{
			data:"DeleteBranchInput"
		},
		deletePaymentMethod:{
			data:"DeletePaymentMethodInput"
		},
		deleteTrustedAccount:{
			data:"DeleteTrustedAccountInput"
		},
		editBranch:{
			data:"EditBranchInput"
		},
		generateSelectBranchDocument:{
			data:"SelectBranchGenerateDocumentInput",
			options:"GenerateDocumentOptionsInput"
		},
		initSystem:{
			data:"Init"
		},
		installExtension:{
			data:"ExtensionInput"
		},
		installSystem:{
			data:"Install"
		},
		registerAccount:{
			data:"RegisterAccountInput"
		},
		selectBranch:{
			data:"SelectBranchInput"
		},
		setWif:{
			data:"SetWifInput"
		},
		startInstall:{
			data:"StartInstallInput"
		},
		uninstallExtension:{
			data:"UninstallExtensionInput"
		},
		updateAccount:{
			data:"UpdateAccountInput"
		},
		updateBankAccount:{
			data:"UpdateBankAccountInput"
		},
		updateExtension:{
			data:"ExtensionInput"
		},
		updateSettings:{
			data:"UpdateSettingsInput"
		},
		updateSystem:{
			data:"Update"
		}
	},
	OrganizationDetailsInput:{

	},
	OrganizationType: "enum" as const,
	PaginationInput:{

	},
	PassportInput:{

	},
	PaymentDirection: "enum" as const,
	PaymentStatus: "enum" as const,
	PaymentType: "enum" as const,
	ProcessStepPositionInput:{

	},
	ProcessStepStatus: "enum" as const,
	ProgramInvestStatus: "enum" as const,
	ProgramType: "enum" as const,
	ProjectStatus: "enum" as const,
	Query:{
		getAccount:{
			data:"GetAccountInput"
		},
		getAccounts:{
			data:"GetAccountsInput",
			options:"PaginationInput"
		},
		getBranches:{
			data:"GetBranchesInput"
		},
		getCapitalIssueLogs:{
			data:"GetCapitalIssueLogsInput",
			options:"PaginationInput"
		},
		getCapitalProjectLogs:{
			data:"GetCapitalLogsInput"
		},
		getExtensionLogs:{
			data:"GetExtensionLogsInput",
			options:"PaginationInput"
		},
		getExtensions:{
			data:"GetExtensionsInput"
		},
		getInstallationStatus:{
			data:"GetInstallationStatusInput"
		},
		getPaymentMethods:{
			data:"GetPaymentMethodsInput"
		},
		getRegistrationConfig:{
			account_type:"AccountType"
		},
		getUserWebPushSubscriptions:{
			data:"GetUserSubscriptionsInput"
		},
		searchPrivateAccounts:{
			data:"SearchPrivateAccountsInput"
		}
	},
	RegisterAccountInput:{
		entrepreneur_data:"CreateEntrepreneurDataInput",
		individual_data:"CreateIndividualDataInput",
		organization_data:"CreateOrganizationDataInput",
		type:"AccountType"
	},
	RepresentedByInput:{

	},
	ResultStatus: "enum" as const,
	SbpDataInput:{

	},
	SearchPrivateAccountsInput:{

	},
	SegmentStatus: "enum" as const,
	SelectBranchGenerateDocumentInput:{

	},
	SelectBranchInput:{
		document:"SelectBranchSignedDocumentInput"
	},
	SelectBranchSignedDocumentInput:{
		meta:"SelectBranchSignedMetaDocumentInput",
		signatures:"SignatureInfoInput"
	},
	SelectBranchSignedMetaDocumentInput:{

	},
	SetVarsInput:{
		coopenomics_agreement:"AgreementVarInput",
		participant_application:"AgreementVarInput",
		privacy_agreement:"AgreementVarInput",
		signature_agreement:"AgreementVarInput",
		user_agreement:"AgreementVarInput",
		wallet_agreement:"AgreementVarInput"
	},
	SetWifInput:{

	},
	SignatureInfoInput:{

	},
	SovietMemberInput:{
		individual_data:"CreateSovietIndividualDataInput"
	},
	StartInstallInput:{

	},
	StoryStatus: "enum" as const,
	SystemStatus: "enum" as const,
	TranscriptionStatus: "enum" as const,
	UninstallExtensionInput:{

	},
	Update:{
		organization_data:"UpdateOrganizationDataInput",
		vars:"VarsInput"
	},
	UpdateAccountInput:{
		entrepreneur_data:"UpdateEntrepreneurDataInput",
		individual_data:"UpdateIndividualDataInput",
		organization_data:"UpdateOrganizationDataInput"
	},
	UpdateBankAccountInput:{
		data:"BankAccountInput"
	},
	UpdateEntrepreneurDataInput:{
		country:"Country",
		details:"EntrepreneurDetailsInput"
	},
	UpdateIndividualDataInput:{
		passport:"PassportInput"
	},
	UpdateOrganizationDataInput:{
		details:"OrganizationDetailsInput",
		represented_by:"RepresentedByInput"
	},
	UpdateSettingsInput:{

	},
	UserStatus: "enum" as const,
	VarsInput:{
		coopenomics_agreement:"AgreementInput",
		participant_application:"AgreementInput",
		privacy_agreement:"AgreementInput",
		signature_agreement:"AgreementInput",
		user_agreement:"AgreementInput",
		wallet_agreement:"AgreementInput"
	},
	WebPushSubscriptionDataInput:{
		keys:"WebPushSubscriptionKeysInput"
	},
	WebPushSubscriptionKeysInput:{

	},
	ID: `scalar.ID` as const
}

export const ReturnTypes: Record<string,any> = {
	Account:{
		blockchain_account:"BlockchainAccount",
		participant_account:"ParticipantAccount",
		private_account:"PrivateAccount",
		provider_account:"MonoAccount",
		user_account:"UserAccount",
		username:"String"
	},
	AccountRamDelta:{
		account:"String",
		delta:"Int"
	},
	AccountResourceInfo:{
		available:"String",
		current_used:"String",
		last_usage_update_time:"String",
		max:"String",
		used:"String"
	},
	AccountsPaginationResult:{
		currentPage:"Int",
		items:"Account",
		totalCount:"Int",
		totalPages:"Int"
	},
	ActDetailAggregate:{
		action:"ExtendedBlockchainAction",
		documentAggregate:"DocumentAggregate"
	},
	ActionAuthorization:{
		actor:"String",
		permission:"String"
	},
	ActionReceipt:{
		abi_sequence:"Int",
		act_digest:"String",
		auth_sequence:"AuthSequence",
		code_sequence:"Int",
		global_sequence:"String",
		receiver:"String",
		recv_sequence:"String"
	},
	AgendaMeetPoint:{
		context:"String",
		decision:"String",
		title:"String"
	},
	Agreement:{
		_created_at:"DateTime",
		_id:"String",
		_updated_at:"DateTime",
		block_num:"Float",
		coopname:"String",
		document:"DocumentAggregate",
		draft_id:"Int",
		id:"Int",
		present:"Boolean",
		program_id:"Int",
		status:"AgreementStatus",
		type:"String",
		updated_at:"DateTime",
		username:"String",
		version:"Int"
	},
	AgreementVar:{
		protocol_day_month_year:"String",
		protocol_number:"String"
	},
	Approval:{
		_created_at:"DateTime",
		_id:"String",
		_updated_at:"DateTime",
		approval_hash:"String",
		approved_document:"DocumentAggregate",
		block_num:"Float",
		callback_action_approve:"String",
		callback_action_decline:"String",
		callback_contract:"String",
		coopname:"String",
		created_at:"DateTime",
		document:"DocumentAggregate",
		id:"Float",
		meta:"String",
		present:"Boolean",
		status:"ApprovalStatus",
		username:"String"
	},
	AuthSequence:{
		account:"String",
		sequence:"String"
	},
	Authority:{
		accounts:"PermissionLevelWeight",
		keys:"KeyWeight",
		threshold:"Int",
		waits:"WaitWeight"
	},
	BankAccount:{
		account_number:"String",
		bank_name:"String",
		card_number:"String",
		currency:"String",
		details:"BankAccountDetails"
	},
	BankAccountDetails:{
		bik:"String",
		corr:"String",
		kpp:"String"
	},
	BankPaymentMethod:{
		created_at:"DateTime",
		data:"BankAccount",
		is_default:"Boolean",
		method_id:"String",
		method_type:"String",
		updated_at:"DateTime",
		username:"String"
	},
	BaseCapitalProject:{
		_created_at:"DateTime",
		_id:"String",
		_updated_at:"DateTime",
		block_num:"Float",
		blockchain_status:"String",
		coopname:"String",
		counts:"CapitalProjectCountsData",
		created_at:"String",
		crps:"CapitalProjectCrpsData",
		data:"String",
		description:"String",
		fact:"CapitalProjectFactPool",
		id:"Int",
		invite:"String",
		is_opened:"Boolean",
		is_planed:"Boolean",
		issue_counter:"Int",
		master:"String",
		meta:"String",
		parent_hash:"String",
		parent_title:"String",
		permissions:"CapitalProjectPermissions",
		plan:"CapitalProjectPlanPool",
		prefix:"String",
		present:"Boolean",
		project_hash:"String",
		status:"ProjectStatus",
		title:"String",
		voting:"CapitalProjectVotingData"
	},
	BlockchainAccount:{
		account_name:"String",
		core_liquid_balance:"String",
		cpu_limit:"AccountResourceInfo",
		cpu_weight:"String",
		created:"String",
		head_block_num:"Int",
		head_block_time:"String",
		last_code_update:"String",
		net_limit:"AccountResourceInfo",
		net_weight:"String",
		permissions:"Permission",
		privileged:"Boolean",
		ram_quota:"Int",
		ram_usage:"Int",
		refund_request:"RefundRequest",
		rex_info:"String",
		self_delegated_bandwidth:"ResourceDelegationDTO",
		total_resources:"ResourceOverview",
		voter_info:"String"
	},
	BlockchainAction:{
		account:"String",
		account_ram_deltas:"AccountRamDelta",
		action_ordinal:"Int",
		authorization:"ActionAuthorization",
		block_id:"String",
		block_num:"Int",
		chain_id:"String",
		console:"String",
		context_free:"Boolean",
		creator_action_ordinal:"Int",
		data:"JSON",
		elapsed:"Int",
		global_sequence:"String",
		name:"String",
		receipt:"ActionReceipt",
		receiver:"String",
		transaction_id:"String"
	},
	BlockchainDecision:{
		approved:"Boolean",
		authorization:"SignedBlockchainDocument",
		authorized:"Boolean",
		authorized_by:"String",
		batch_id:"Float",
		callback_contract:"String",
		confirm_callback:"String",
		coopname:"String",
		created_at:"String",
		decline_callback:"String",
		expired_at:"String",
		hash:"String",
		id:"Float",
		meta:"String",
		statement:"SignedBlockchainDocument",
		type:"String",
		username:"String",
		username_certificate:"UserCertificateUnion",
		validated:"Boolean",
		votes_against:"String",
		votes_against_certificates:"UserCertificateUnion",
		votes_for:"String",
		votes_for_certificates:"UserCertificateUnion"
	},
	BlockchainInfoDTO:{
		block_cpu_limit:"Int",
		block_net_limit:"Int",
		chain_id:"String",
		fork_db_head_block_id:"String",
		fork_db_head_block_num:"Int",
		head_block_id:"String",
		head_block_num:"Int",
		head_block_producer:"String",
		head_block_time:"String",
		last_irreversible_block_id:"String",
		last_irreversible_block_num:"Int",
		last_irreversible_block_time:"String",
		server_version:"String",
		server_version_string:"String",
		virtual_block_cpu_limit:"Int",
		virtual_block_net_limit:"Int"
	},
	BoardMember:{
		first_name:"String",
		is_chairman:"Boolean",
		last_name:"String",
		middle_name:"String",
		username:"String"
	},
	Branch:{
		bank_account:"BankPaymentMethod",
		braname:"String",
		city:"String",
		coopname:"String",
		country:"String",
		details:"OrganizationDetails",
		email:"String",
		fact_address:"String",
		full_address:"String",
		full_name:"String",
		phone:"String",
		represented_by:"RepresentedBy",
		short_name:"String",
		trusted:"Individual",
		trustee:"Individual",
		type:"String"
	},
	CallTranscription:{
		createdAt:"DateTime",
		endedAt:"DateTime",
		id:"String",
		matrixRoomId:"String",
		memo:"String",
		participants:"String",
		roomId:"String",
		roomName:"String",
		startedAt:"DateTime",
		status:"TranscriptionStatus",
		updatedAt:"DateTime"
	},
	Candidate:{
		braname:"String",
		coopname:"String",
		created_at:"DateTime",
		program_key:"String",
		public_key:"String",
		referer:"String",
		referer_display_name:"String",
		registered_at:"DateTime",
		status:"CandidateStatus",
		type:"String",
		username:"String",
		username_display_name:"String"
	},
	CapitalCandidate:{
		about:"String",
		braname:"String",
		capital_status:"ContributorStatus",
		contributed_as_author:"String",
		contributed_as_contributor:"String",
		contributed_as_coordinator:"String",
		contributed_as_creator:"String",
		contributed_as_investor:"String",
		contributed_as_propertor:"String",
		contributor_hash:"String",
		coopname:"String",
		created_at:"DateTime",
		hours_per_day:"Float",
		level:"Float",
		memo:"String",
		program_key:"String",
		public_key:"String",
		rate_per_hour:"String",
		referer:"String",
		referer_display_name:"String",
		registered_at:"DateTime",
		status:"CandidateStatus",
		type:"String",
		username:"String",
		username_display_name:"String"
	},
	CapitalCommit:{
		_created_at:"DateTime",
		_id:"String",
		_updated_at:"DateTime",
		amounts:"CapitalCommitAmounts",
		block_num:"Float",
		blockchain_status:"String",
		commit_hash:"String",
		coopname:"String",
		created_at:"String",
		data:"JSON",
		description:"String",
		display_name:"String",
		id:"Int",
		meta:"String",
		present:"Boolean",
		project:"BaseCapitalProject",
		project_hash:"String",
		status:"CommitStatus",
		username:"String"
	},
	CapitalCommitAmounts:{
		authors_base_pool:"String",
		authors_bonus_pool:"String",
		contributors_bonus_pool:"String",
		creators_base_pool:"String",
		creators_bonus_pool:"String",
		creators_hours:"String",
		hour_cost:"String",
		total_contribution:"String",
		total_generation_pool:"String"
	},
	CapitalConfigObject:{
		authors_voting_percent:"Float",
		coordinator_bonus_percent:"Float",
		coordinator_invite_validity_days:"Float",
		creators_voting_percent:"Float",
		energy_decay_rate_per_day:"Float",
		energy_gain_coefficient:"Float",
		expense_pool_percent:"Float",
		level_depth_base:"Float",
		level_growth_coefficient:"Float",
		voting_period_in_days:"Float"
	},
	CapitalContributor:{
		_created_at:"DateTime",
		_id:"String",
		_updated_at:"DateTime",
		about:"String",
		appendixes:"String",
		blagorost_agreement_hash:"String",
		blagorost_offer_hash:"String",
		blagorost_wallet:"ProgramWallet",
		block_num:"Float",
		blockchain_status:"String",
		contract:"DocumentAggregate",
		contributed_as_author:"String",
		contributed_as_contributor:"String",
		contributed_as_coordinator:"String",
		contributed_as_creator:"String",
		contributed_as_investor:"String",
		contributed_as_propertor:"String",
		contributor_hash:"String",
		coopname:"String",
		created_at:"String",
		debt_amount:"String",
		display_name:"String",
		document_parameters:"ContributorDocumentParameters",
		energy:"Float",
		generation_contract_hash:"String",
		generation_wallet:"ProgramWallet",
		generator_offer_hash:"String",
		hours_per_day:"Float",
		id:"Int",
		is_external_blagorost_agreement:"Boolean",
		is_external_contract:"Boolean",
		last_energy_update:"String",
		level:"Int",
		main_wallet:"ProgramWallet",
		memo:"String",
		present:"Boolean",
		program_key:"String",
		rate_per_hour:"String",
		status:"ContributorStatus",
		storage_agreement_hash:"String",
		username:"String"
	},
	CapitalCycle:{
		_created_at:"DateTime",
		_id:"String",
		_updated_at:"DateTime",
		block_num:"Float",
		end_date:"DateTime",
		name:"String",
		present:"Boolean",
		start_date:"DateTime",
		status:"CycleStatus"
	},
	CapitalDebt:{
		_created_at:"DateTime",
		_id:"String",
		_updated_at:"DateTime",
		amount:"Float",
		approved_statement:"DocumentAggregate",
		authorization:"DocumentAggregate",
		block_num:"Int",
		blockchain_status:"String",
		coopname:"String",
		debt_hash:"String",
		id:"Int",
		memo:"String",
		present:"Boolean",
		project_hash:"String",
		repaid_at:"String",
		statement:"DocumentAggregate",
		status:"DebtStatus",
		username:"String"
	},
	CapitalExpense:{
		_created_at:"DateTime",
		_id:"String",
		_updated_at:"DateTime",
		amount:"String",
		approved_statement:"DocumentAggregate",
		authorization:"DocumentAggregate",
		block_num:"Int",
		blockchain_status:"String",
		coopname:"String",
		description:"String",
		expense_hash:"String",
		expense_statement:"DocumentAggregate",
		fund_id:"Float",
		id:"Int",
		present:"Boolean",
		project_hash:"String",
		spended_at:"String",
		status:"ExpenseStatus",
		username:"String"
	},
	CapitalInvest:{
		_created_at:"DateTime",
		_id:"String",
		_updated_at:"DateTime",
		amount:"Float",
		block_num:"Int",
		blockchain_status:"String",
		coopname:"String",
		coordinator:"String",
		coordinator_amount:"Float",
		id:"Int",
		invest_hash:"String",
		invested_at:"String",
		present:"Boolean",
		project_hash:"String",
		statement:"String",
		status:"InvestStatus",
		username:"String"
	},
	CapitalIssue:{
		_created_at:"DateTime",
		_id:"String",
		_updated_at:"DateTime",
		block_num:"Float",
		created_by:"String",
		creators:"String",
		cycle_id:"String",
		description:"String",
		estimate:"Float",
		id:"String",
		issue_hash:"String",
		metadata:"JSON",
		permissions:"CapitalIssuePermissions",
		present:"Boolean",
		priority:"IssuePriority",
		project_hash:"String",
		sort_order:"Int",
		status:"IssueStatus",
		submaster:"String",
		title:"String"
	},
	CapitalIssuePermissions:{
		allowed_status_transitions:"IssueStatus",
		can_assign_creator:"Boolean",
		can_change_status:"Boolean",
		can_complete_requirement:"Boolean",
		can_create_requirement:"Boolean",
		can_delete_issue:"Boolean",
		can_delete_requirement:"Boolean",
		can_edit_issue:"Boolean",
		can_set_done:"Boolean",
		can_set_estimate:"Boolean",
		can_set_on_review:"Boolean",
		can_set_priority:"Boolean",
		has_clearance:"Boolean",
		is_guest:"Boolean"
	},
	CapitalLog:{
		_id:"String",
		coopname:"String",
		created_at:"DateTime",
		entity_id:"String",
		entity_type:"LogEntityType",
		event_type:"LogEventType",
		initiator:"String",
		message:"String",
		metadata:"JSON",
		project_hash:"String",
		reference_id:"String"
	},
	CapitalProgramInvest:{
		_created_at:"DateTime",
		_id:"String",
		_updated_at:"DateTime",
		amount:"Float",
		block_num:"Int",
		blockchain_status:"String",
		coopname:"String",
		id:"Int",
		invest_hash:"String",
		invested_at:"String",
		present:"Boolean",
		statement:"DocumentAggregate",
		status:"ProgramInvestStatus",
		username:"String"
	},
	CapitalProject:{
		_created_at:"DateTime",
		_id:"String",
		_updated_at:"DateTime",
		block_num:"Float",
		blockchain_status:"String",
		components:"CapitalProjectComponent",
		coopname:"String",
		counts:"CapitalProjectCountsData",
		created_at:"String",
		crps:"CapitalProjectCrpsData",
		data:"String",
		description:"String",
		fact:"CapitalProjectFactPool",
		id:"Int",
		invite:"String",
		is_opened:"Boolean",
		is_planed:"Boolean",
		issue_counter:"Int",
		master:"String",
		meta:"String",
		parent_hash:"String",
		parent_title:"String",
		permissions:"CapitalProjectPermissions",
		plan:"CapitalProjectPlanPool",
		prefix:"String",
		present:"Boolean",
		project_hash:"String",
		status:"ProjectStatus",
		title:"String",
		voting:"CapitalProjectVotingData"
	},
	CapitalProjectComponent:{
		_created_at:"DateTime",
		_id:"String",
		_updated_at:"DateTime",
		block_num:"Float",
		blockchain_status:"String",
		coopname:"String",
		counts:"CapitalProjectCountsData",
		created_at:"String",
		crps:"CapitalProjectCrpsData",
		data:"String",
		description:"String",
		fact:"CapitalProjectFactPool",
		id:"Int",
		invite:"String",
		is_opened:"Boolean",
		is_planed:"Boolean",
		issue_counter:"Int",
		master:"String",
		meta:"String",
		parent_hash:"String",
		parent_title:"String",
		permissions:"CapitalProjectPermissions",
		plan:"CapitalProjectPlanPool",
		prefix:"String",
		present:"Boolean",
		project_hash:"String",
		status:"ProjectStatus",
		title:"String",
		voting:"CapitalProjectVotingData"
	},
	CapitalProjectCountsData:{
		total_authors:"Int",
		total_commits:"Int",
		total_contributors:"Int",
		total_coordinators:"Int",
		total_creators:"Int",
		total_investors:"Int",
		total_propertors:"Int",
		total_unique_participants:"Int"
	},
	CapitalProjectCrpsData:{
		author_base_cumulative_reward_per_share:"Float",
		author_bonus_cumulative_reward_per_share:"Float",
		contributor_cumulative_reward_per_share:"Float",
		total_capital_contributors_shares:"String"
	},
	CapitalProjectFactPool:{
		accumulated_expense_pool:"String",
		authors_base_pool:"String",
		authors_bonus_pool:"String",
		contributors_bonus_pool:"String",
		coordinators_base_pool:"String",
		coordinators_investment_pool:"String",
		creators_base_pool:"String",
		creators_bonus_pool:"String",
		creators_hours:"Int",
		hour_cost:"String",
		invest_pool:"String",
		program_invest_pool:"String",
		property_base_pool:"String",
		return_base_percent:"Float",
		target_expense_pool:"String",
		total:"String",
		total_contribution:"String",
		total_generation_pool:"String",
		total_received_investments:"String",
		total_returned_investments:"String",
		total_used_investments:"String",
		total_with_investments:"String",
		use_invest_percent:"Float",
		used_expense_pool:"String"
	},
	CapitalProjectPermissions:{
		can_change_project_status:"Boolean",
		can_complete_requirement:"Boolean",
		can_create_requirement:"Boolean",
		can_delete_project:"Boolean",
		can_delete_requirement:"Boolean",
		can_edit_project:"Boolean",
		can_manage_authors:"Boolean",
		can_manage_issues:"Boolean",
		can_set_master:"Boolean",
		can_set_plan:"Boolean",
		has_clearance:"Boolean",
		is_guest:"Boolean",
		pending_clearance:"Boolean"
	},
	CapitalProjectPlanPool:{
		authors_base_pool:"String",
		authors_bonus_pool:"String",
		contributors_bonus_pool:"String",
		coordinators_base_pool:"String",
		coordinators_investment_pool:"String",
		creators_base_pool:"String",
		creators_bonus_pool:"String",
		creators_hours:"Int",
		hour_cost:"String",
		invest_pool:"String",
		program_invest_pool:"String",
		return_base_percent:"Float",
		target_expense_pool:"String",
		total:"String",
		total_generation_pool:"String",
		total_received_investments:"String",
		total_with_investments:"String",
		use_invest_percent:"Float"
	},
	CapitalProjectTimeStats:{
		available_hours:"Float",
		contributor_hash:"String",
		pending_hours:"Float",
		project_hash:"String",
		project_name:"String",
		total_committed_hours:"Float",
		total_uncommitted_hours:"Float"
	},
	CapitalProjectVotingAmounts:{
		active_voting_amount:"String",
		authors_bonuses_on_voting:"String",
		authors_equal_per_author:"String",
		authors_equal_spread:"String",
		creators_bonuses_on_voting:"String",
		creators_direct_spread:"String",
		equal_voting_amount:"String",
		total_voting_pool:"String"
	},
	CapitalProjectVotingData:{
		amounts:"CapitalProjectVotingAmounts",
		authors_voting_percent:"Float",
		creators_voting_percent:"Float",
		total_voters:"Int",
		votes_received:"Int",
		voting_deadline:"String"
	},
	CapitalResult:{
		_created_at:"DateTime",
		_id:"String",
		_updated_at:"DateTime",
		act:"DocumentAggregate",
		authorization:"DocumentAggregate",
		block_num:"Float",
		blockchain_status:"String",
		coopname:"String",
		created_at:"String",
		data:"String",
		debt_amount:"String",
		id:"Int",
		present:"Boolean",
		project_hash:"String",
		result_hash:"String",
		statement:"DocumentAggregate",
		status:"ResultStatus",
		total_amount:"String",
		username:"String"
	},
	CapitalSegment:{
		_created_at:"DateTime",
		_id:"String",
		_updated_at:"DateTime",
		author_base:"String",
		author_bonus:"String",
		available_for_program:"String",
		available_for_wallet:"String",
		block_num:"Float",
		capital_contributor_shares:"String",
		contributor_bonus:"String",
		coopname:"String",
		coordinator_base:"String",
		coordinator_investments:"String",
		creator_base:"String",
		creator_bonus:"String",
		debt_amount:"String",
		debt_settled:"String",
		direct_creator_bonus:"String",
		display_name:"String",
		equal_author_bonus:"String",
		has_vote:"Boolean",
		id:"Int",
		intellectual_cost:"String",
		investor_amount:"String",
		investor_base:"String",
		is_author:"Boolean",
		is_completed:"Boolean",
		is_contributor:"Boolean",
		is_coordinator:"Boolean",
		is_creator:"Boolean",
		is_investor:"Boolean",
		is_propertor:"Boolean",
		is_votes_calculated:"Boolean",
		last_author_base_reward_per_share:"Float",
		last_author_bonus_reward_per_share:"Float",
		last_contributor_reward_per_share:"Float",
		last_known_coordinators_investment_pool:"String",
		last_known_creators_base_pool:"String",
		last_known_invest_pool:"String",
		present:"Boolean",
		project_hash:"String",
		property_base:"String",
		provisional_amount:"String",
		share_percent:"Float",
		status:"SegmentStatus",
		total_segment_base_cost:"String",
		total_segment_bonus_cost:"String",
		total_segment_cost:"String",
		username:"String",
		value:"String",
		voting_bonus:"String"
	},
	CapitalStory:{
		_created_at:"DateTime",
		_id:"String",
		_updated_at:"DateTime",
		block_num:"Float",
		content_format:"CapitalStoryContentFormat",
		coopname:"String",
		created_by:"String",
		description:"String",
		issue_hash:"String",
		present:"Boolean",
		project_hash:"String",
		sort_order:"Int",
		status:"StoryStatus",
		story_hash:"String",
		title:"String"
	},
	CapitalTimeEntriesByIssues:{
		available_hours:"Float",
		committed_hours:"Float",
		contributor_hash:"String",
		contributor_name:"String",
		coopname:"String",
		issue_hash:"String",
		issue_title:"String",
		pending_hours:"Float",
		project_hash:"String",
		project_name:"String",
		total_hours:"Float",
		uncommitted_hours:"Float"
	},
	CapitalTimeEntry:{
		_created_at:"String",
		_id:"String",
		_updated_at:"String",
		commit_hash:"String",
		contributor_hash:"String",
		coopname:"String",
		date:"String",
		entry_type:"String",
		estimate_snapshot:"Float",
		hours:"Float",
		is_committed:"Boolean",
		issue_hash:"String",
		project_hash:"String"
	},
	CapitalVote:{
		_created_at:"DateTime",
		_id:"String",
		_updated_at:"DateTime",
		amount:"String",
		block_num:"Float",
		coopname:"String",
		id:"Int",
		present:"Boolean",
		project_hash:"String",
		recipient:"String",
		recipient_display_name:"String",
		voted_at:"String",
		voter:"String",
		voter_display_name:"String"
	},
	ChartOfAccountsItem:{
		available:"String",
		blocked:"String",
		displayId:"String",
		id:"Int",
		name:"String",
		writeoff:"String"
	},
	ContactsDTO:{
		chairman:"PublicChairman",
		details:"OrganizationDetails",
		email:"String",
		full_address:"String",
		full_name:"String",
		phone:"String"
	},
	ContributorDocumentParameters:{
		blagorost_agreement_created_at:"String",
		blagorost_agreement_number:"String",
		blagorost_contributor_contract_created_at:"String",
		blagorost_contributor_contract_number:"String",
		blagorost_storage_agreement_created_at:"String",
		blagorost_storage_agreement_number:"String",
		generator_agreement_created_at:"String",
		generator_agreement_number:"String"
	},
	CooperativeOperatorAccount:{
		active_participants_count:"Float",
		announce:"String",
		coop_type:"String",
		created_at:"String",
		description:"String",
		document:"SignedBlockchainDocument",
		initial:"String",
		is_branched:"Boolean",
		is_cooperative:"Boolean",
		is_enrolled:"Boolean",
		meta:"String",
		minimum:"String",
		org_initial:"String",
		org_minimum:"String",
		org_registration:"String",
		parent_username:"String",
		referer:"String",
		registered_at:"String",
		registration:"String",
		registrator:"String",
		status:"String",
		storages:"String",
		type:"String",
		username:"String",
		verifications:"Verification"
	},
	CreateSubscriptionResponse:{
		message:"String",
		subscription:"WebPushSubscriptionDto",
		success:"Boolean"
	},
	CurrentTableState:{
		block_num:"Float",
		code:"String",
		created_at:"DateTime",
		primary_key:"String",
		scope:"String",
		table:"String",
		value:"JSON"
	},
	DateTime: `scalar.DateTime` as const,
	DecisionDetailAggregate:{
		action:"ExtendedBlockchainAction",
		documentAggregate:"DocumentAggregate",
		votes_against:"ExtendedBlockchainAction",
		votes_for:"ExtendedBlockchainAction"
	},
	Delta:{
		block_id:"String",
		block_num:"Float",
		chain_id:"String",
		code:"String",
		created_at:"DateTime",
		id:"String",
		present:"Boolean",
		primary_key:"String",
		scope:"String",
		table:"String",
		value:"JSON"
	},
	Desktop:{
		authorizedHome:"String",
		coopname:"String",
		layout:"String",
		nonAuthorizedHome:"String",
		workspaces:"DesktopWorkspace"
	},
	DesktopConfig:{
		defaultRoute:"String",
		icon:"String",
		name:"String",
		title:"String"
	},
	DesktopWorkspace:{
		defaultRoute:"String",
		extension_name:"String",
		icon:"String",
		name:"String",
		title:"String"
	},
	DocumentAggregate:{
		document:"SignedDigitalDocument",
		hash:"String",
		rawDocument:"GeneratedDocument"
	},
	DocumentPackageAggregate:{
		acts:"ActDetailAggregate",
		decision:"DecisionDetailAggregate",
		links:"DocumentAggregate",
		statement:"StatementDetailAggregate"
	},
	Entrepreneur:{
		birthdate:"String",
		city:"String",
		country:"String",
		details:"EntrepreneurDetails",
		email:"String",
		first_name:"String",
		full_address:"String",
		last_name:"String",
		middle_name:"String",
		phone:"String",
		username:"String"
	},
	EntrepreneurCertificate:{
		first_name:"String",
		inn:"String",
		last_name:"String",
		middle_name:"String",
		type:"AccountType",
		username:"String"
	},
	EntrepreneurDetails:{
		inn:"String",
		ogrn:"String"
	},
	ExtendedBlockchainAction:{
		account:"String",
		account_ram_deltas:"AccountRamDelta",
		action_ordinal:"Int",
		actor_certificate:"UserCertificateUnion",
		authorization:"ActionAuthorization",
		block_id:"String",
		block_num:"Int",
		chain_id:"String",
		console:"String",
		context_free:"Boolean",
		creator_action_ordinal:"Int",
		data:"JSON",
		elapsed:"Int",
		global_sequence:"String",
		name:"String",
		receipt:"ActionReceipt",
		receiver:"String",
		transaction_id:"String"
	},
	Extension:{
		config:"JSON",
		created_at:"DateTime",
		description:"String",
		desktops:"DesktopConfig",
		enabled:"Boolean",
		external_url:"String",
		image:"String",
		instructions:"String",
		is_available:"Boolean",
		is_builtin:"Boolean",
		is_installed:"Boolean",
		is_internal:"Boolean",
		name:"String",
		readme:"String",
		schema:"JSON",
		tags:"String",
		title:"String",
		updated_at:"DateTime"
	},
	ExtensionLog:{
		created_at:"DateTime",
		data:"String",
		extension_local_id:"Float",
		id:"Float",
		name:"String",
		updated_at:"DateTime"
	},
	ExtensionLogsPaginationResult:{
		currentPage:"Int",
		items:"ExtensionLog",
		totalCount:"Int",
		totalPages:"Int"
	},
	GatewayPayment:{
		blockchain_data:"JSON",
		can_change_status:"Boolean",
		coopname:"String",
		created_at:"DateTime",
		direction:"PaymentDirection",
		direction_label:"String",
		expired_at:"DateTime",
		formatted_amount:"String",
		hash:"String",
		id:"ID",
		income_hash:"String",
		is_final:"Boolean",
		memo:"String",
		message:"String",
		outcome_hash:"String",
		payment_details:"PaymentDetails",
		payment_method_id:"String",
		provider:"String",
		quantity:"Float",
		statement:"JSON",
		status:"PaymentStatus",
		status_label:"String",
		symbol:"String",
		type:"PaymentType",
		type_label:"String",
		updated_at:"DateTime",
		username:"String",
		username_certificate:"UserCertificateUnion"
	},
	GeneratedDocument:{
		binary:"String",
		full_title:"String",
		hash:"String",
		html:"String",
		meta:"JSON"
	},
	GeneratedRegistrationDocument:{
		agreement_type:"String",
		checkbox_text:"String",
		document:"GeneratedDocument",
		id:"String",
		is_blockchain_agreement:"Boolean",
		link_text:"String",
		link_to_statement:"Boolean",
		order:"Int",
		title:"String"
	},
	Individual:{
		birthdate:"String",
		email:"String",
		first_name:"String",
		full_address:"String",
		last_name:"String",
		middle_name:"String",
		passport:"Passport",
		phone:"String",
		username:"String"
	},
	IndividualCertificate:{
		first_name:"String",
		last_name:"String",
		middle_name:"String",
		type:"AccountType",
		username:"String"
	},
	InstallationStatus:{
		has_private_account:"Boolean",
		init_by_server:"Boolean",
		organization_data:"OrganizationWithBankAccount"
	},
	JSON: `scalar.JSON` as const,
	KeyWeight:{
		key:"String",
		weight:"Int"
	},
	LedgerOperation:{
		account_id:"Int",
		action:"String",
		comment:"String",
		coopname:"String",
		created_at:"DateTime",
		global_sequence:"Int",
		hash:"String",
		quantity:"String",
		username:"String"
	},
	Meet:{
		authorization:"DocumentAggregate",
		close_at:"DateTime",
		coopname:"String",
		created_at:"DateTime",
		current_quorum_percent:"Float",
		cycle:"Float",
		decision1:"DocumentAggregate",
		decision2:"DocumentAggregate",
		hash:"String",
		id:"Float",
		initiator:"String",
		initiator_certificate:"UserCertificateUnion",
		level:"String",
		notified_users:"String",
		open_at:"DateTime",
		presider:"String",
		presider_certificate:"UserCertificateUnion",
		proposal:"DocumentAggregate",
		quorum_passed:"Boolean",
		quorum_percent:"Float",
		secretary:"String",
		secretary_certificate:"UserCertificateUnion",
		signed_ballots:"Float",
		status:"String",
		type:"String"
	},
	MeetPreProcessing:{
		agenda:"AgendaMeetPoint",
		close_at:"DateTime",
		coopname:"String",
		details:"String",
		hash:"String",
		initiator:"String",
		initiator_certificate:"UserCertificateUnion",
		open_at:"DateTime",
		presider:"String",
		presider_certificate:"UserCertificateUnion",
		proposal:"DocumentAggregate",
		secretary:"String",
		secretary_certificate:"UserCertificateUnion"
	},
	MeetProcessed:{
		coopname:"String",
		decision:"SignedDigitalDocument",
		decisionAggregate:"DocumentAggregate",
		hash:"String",
		presider:"String",
		presider_certificate:"UserCertificateUnion",
		quorum_passed:"Boolean",
		quorum_percent:"Int",
		results:"MeetQuestionResult",
		secretary:"String",
		secretary_certificate:"UserCertificateUnion",
		signed_ballots:"Int"
	},
	MeetProcessing:{
		extendedStatus:"ExtendedMeetStatus",
		hash:"String",
		isVoted:"Boolean",
		meet:"Meet",
		questions:"Question"
	},
	MeetQuestionResult:{
		accepted:"Boolean",
		context:"String",
		decision:"String",
		number:"Int",
		question_id:"Int",
		title:"String",
		votes_abstained:"Int",
		votes_against:"Int",
		votes_for:"Int"
	},
	MonoAccount:{
		email:"String",
		has_account:"Boolean",
		initial_order:"String",
		is_email_verified:"Boolean",
		is_registered:"Boolean",
		message:"String",
		public_key:"String",
		referer:"String",
		role:"String",
		status:"UserStatus",
		subscriber_hash:"String",
		subscriber_id:"String",
		type:"String",
		username:"String"
	},
	Mutation:{
		addPaymentMethod:"PaymentMethod",
		addTrustedAccount:"Branch",
		createBranch:"Branch",
		createWebPushSubscription:"CreateSubscriptionResponse",
		deactivateWebPushSubscriptionById:"Boolean",
		deleteBranch:"Boolean",
		deletePaymentMethod:"Boolean",
		deleteTrustedAccount:"Branch",
		editBranch:"Branch",
		generateSelectBranchDocument:"GeneratedDocument",
		initSystem:"SystemInfo",
		installExtension:"Extension",
		installSystem:"SystemInfo",
		registerAccount:"RegisteredAccount",
		selectBranch:"Boolean",
		setWif:"Boolean",
		startInstall:"StartInstallResult",
		uninstallExtension:"Boolean",
		updateAccount:"Account",
		updateBankAccount:"PaymentMethod",
		updateExtension:"Extension",
		updateSettings:"Settings",
		updateSystem:"SystemInfo"
	},
	OneCoopDocumentOutput:{
		action:"String",
		block_num:"Int",
		data:"JSON",
		hash:"String",
		package:"String"
	},
	Organization:{
		city:"String",
		country:"String",
		details:"OrganizationDetails",
		email:"String",
		fact_address:"String",
		full_address:"String",
		full_name:"String",
		phone:"String",
		represented_by:"RepresentedBy",
		short_name:"String",
		type:"String",
		username:"String"
	},
	OrganizationCertificate:{
		inn:"String",
		ogrn:"String",
		represented_by:"RepresentedByCertificate",
		short_name:"String",
		type:"AccountType",
		username:"String"
	},
	OrganizationDetails:{
		inn:"String",
		kpp:"String",
		ogrn:"String"
	},
	OrganizationWithBankAccount:{
		bank_account:"BankAccount",
		city:"String",
		country:"String",
		details:"OrganizationDetails",
		email:"String",
		fact_address:"String",
		full_address:"String",
		full_name:"String",
		phone:"String",
		represented_by:"RepresentedBy",
		short_name:"String",
		type:"String",
		username:"String"
	},
	PaginatedCapitalLogsPaginationResult:{
		currentPage:"Int",
		items:"CapitalLog",
		totalCount:"Int",
		totalPages:"Int"
	},
	ParticipantAccount:{
		braname:"String",
		created_at:"DateTime",
		has_vote:"Boolean",
		initial_amount:"String",
		is_initial:"Boolean",
		is_minimum:"Boolean",
		last_min_pay:"DateTime",
		last_update:"DateTime",
		minimum_amount:"String",
		status:"String",
		type:"String",
		username:"String"
	},
	Passport:{
		code:"String",
		issued_at:"String",
		issued_by:"String",
		number:"Int",
		series:"Int"
	},
	PaymentDetails:{
		amount_plus_fee:"String",
		amount_without_fee:"String",
		data:"JSON",
		fact_fee_percent:"Float",
		fee_amount:"String",
		fee_percent:"Float",
		tolerance_percent:"Float"
	},
	PaymentMethod:{
		created_at:"DateTime",
		data:"PaymentMethodData",
		is_default:"Boolean",
		method_id:"String",
		method_type:"String",
		updated_at:"DateTime",
		username:"String"
	},
	PaymentMethodData:{
		"...on BankAccount":"BankAccount",
		"...on SbpAccount":"SbpAccount"
	},
	PaymentMethodPaginationResult:{
		currentPage:"Int",
		items:"PaymentMethod",
		totalCount:"Int",
		totalPages:"Int"
	},
	Permission:{
		parent:"String",
		perm_name:"String",
		required_auth:"Authority"
	},
	PermissionLevel:{
		actor:"String",
		permission:"String"
	},
	PermissionLevelWeight:{
		permission:"PermissionLevel",
		weight:"Int"
	},
	PrivateAccount:{
		entrepreneur_data:"Entrepreneur",
		individual_data:"Individual",
		organization_data:"Organization",
		type:"AccountType"
	},
	PrivateAccountSearchData:{
		"...on Entrepreneur":"Entrepreneur",
		"...on Individual":"Individual",
		"...on Organization":"Organization"
	},
	PrivateAccountSearchResult:{
		data:"PrivateAccountSearchData",
		highlightedFields:"String",
		score:"Float",
		type:"String"
	},
	ProcessEdge:{
		id:"String",
		source:"String",
		target:"String"
	},
	ProcessStepPosition:{
		x:"Float",
		y:"Float"
	},
	ProcessStepState:{
		completed_at:"DateTime",
		issue_hash:"String",
		status:"ProcessStepStatus",
		step_id:"String"
	},
	ProcessStepTemplate:{
		description:"String",
		estimate:"Float",
		id:"String",
		is_start:"Boolean",
		position:"ProcessStepPosition",
		title:"String"
	},
	ProgramWallet:{
		agreement_id:"ID",
		available:"String",
		blockNum:"Float",
		blocked:"String",
		coopname:"String",
		id:"ID",
		membership_contribution:"String",
		program_id:"ID",
		program_type:"ProgramType",
		username:"String"
	},
	PublicChairman:{
		first_name:"String",
		last_name:"String",
		middle_name:"String"
	},
	Query:{
		getAccount:"Account",
		getAccounts:"AccountsPaginationResult",
		getBranches:"Branch",
		getCapitalIssueLogs:"PaginatedCapitalLogsPaginationResult",
		getCapitalProjectLogs:"PaginatedCapitalLogsPaginationResult",
		getDesktop:"Desktop",
		getExtensionLogs:"ExtensionLogsPaginationResult",
		getExtensions:"Extension",
		getInstallationStatus:"InstallationStatus",
		getPaymentMethods:"PaymentMethodPaginationResult",
		getRegistrationConfig:"RegistrationConfig",
		getSystemInfo:"SystemInfo",
		getUserWebPushSubscriptions:"WebPushSubscriptionDto",
		getWebPushSubscriptionStats:"SubscriptionStatsDto",
		searchPrivateAccounts:"PrivateAccountSearchResult"
	},
	Question:{
		context:"String",
		coopname:"String",
		counter_votes_abstained:"Float",
		counter_votes_against:"Float",
		counter_votes_for:"Float",
		decision:"String",
		id:"Float",
		meet_id:"Float",
		number:"Float",
		title:"String",
		voters_abstained:"String",
		voters_against:"String",
		voters_for:"String"
	},
	RefundRequest:{
		cpu_amount:"String",
		net_amount:"String",
		owner:"String",
		request_time:"String"
	},
	RegisteredAccount:{
		account:"Account",
		tokens:"Tokens"
	},
	RegistrationConfig:{
		programs:"RegistrationProgram",
		requires_selection:"Boolean"
	},
	RegistrationProgram:{
		applicable_account_types:"AccountType",
		description:"String",
		image_url:"String",
		key:"String",
		order:"Int",
		requirements:"String",
		title:"String"
	},
	RepresentedBy:{
		based_on:"String",
		first_name:"String",
		last_name:"String",
		middle_name:"String",
		position:"String"
	},
	RepresentedByCertificate:{
		first_name:"String",
		last_name:"String",
		middle_name:"String",
		position:"String"
	},
	ResourceDelegationDTO:{
		cpu_weight:"String",
		from:"String",
		net_weight:"String",
		to:"String"
	},
	ResourceOverview:{
		cpu_weight:"String",
		net_weight:"String",
		owner:"String",
		ram_bytes:"Int"
	},
	SbpAccount:{
		phone:"String"
	},
	Settings:{
		authorized_default_route:"String",
		authorized_default_workspace:"String",
		coopname:"String",
		created_at:"DateTime",
		non_authorized_default_route:"String",
		non_authorized_default_workspace:"String",
		provider_name:"String",
		updated_at:"DateTime"
	},
	SignatureInfo:{
		id:"Float",
		is_valid:"Boolean",
		meta:"JSON",
		public_key:"String",
		signature:"String",
		signed_at:"String",
		signed_hash:"String",
		signer:"String",
		signer_certificate:"UserCertificateUnion"
	},
	SignedBlockchainDocument:{
		doc_hash:"String",
		hash:"String",
		meta:"String",
		meta_hash:"String",
		signatures:"SignatureInfo",
		version:"String"
	},
	SignedDigitalDocument:{
		doc_hash:"String",
		hash:"String",
		meta:"JSON",
		meta_hash:"String",
		signatures:"SignatureInfo",
		version:"String"
	},
	StartInstallResult:{
		coopname:"String",
		install_code:"String"
	},
	StatementDetailAggregate:{
		action:"ExtendedBlockchainAction",
		documentAggregate:"DocumentAggregate"
	},
	SubscriptionStatsDto:{
		active:"Int",
		inactive:"Int",
		total:"Int",
		uniqueUsers:"Int"
	},
	Symbols:{
		root_govern_precision:"Float",
		root_govern_symbol:"String",
		root_precision:"Float",
		root_symbol:"String"
	},
	SystemFeatures:{
		search:"Boolean"
	},
	SystemInfo:{
		blockchain_account:"BlockchainAccount",
		blockchain_info:"BlockchainInfoDTO",
		board_members:"BoardMember",
		contacts:"ContactsDTO",
		cooperator_account:"CooperativeOperatorAccount",
		coopname:"String",
		features:"SystemFeatures",
		is_providered:"Boolean",
		is_unioned:"Boolean",
		settings:"Settings",
		symbols:"Symbols",
		system_status:"SystemStatus",
		union_link:"String",
		vars:"Vars"
	},
	Token:{
		expires:"DateTime",
		token:"String"
	},
	Tokens:{
		access:"Token",
		refresh:"Token"
	},
	TranscriptionSegment:{
		createdAt:"DateTime",
		endOffset:"Float",
		id:"String",
		speakerIdentity:"String",
		speakerName:"String",
		startOffset:"Float",
		text:"String"
	},
	UserAccount:{
		meta:"String",
		referer:"String",
		registered_at:"String",
		registrator:"String",
		status:"String",
		storages:"String",
		type:"String",
		username:"String",
		verifications:"Verification"
	},
	UserCertificateUnion:{
		"...on EntrepreneurCertificate":"EntrepreneurCertificate",
		"...on IndividualCertificate":"IndividualCertificate",
		"...on OrganizationCertificate":"OrganizationCertificate"
	},
	Vars:{
		confidential_email:"String",
		confidential_link:"String",
		contact_email:"String",
		coopenomics_agreement:"AgreementVar",
		coopname:"String",
		full_abbr:"String",
		full_abbr_dative:"String",
		full_abbr_genitive:"String",
		name:"String",
		participant_application:"AgreementVar",
		passport_request:"String",
		privacy_agreement:"AgreementVar",
		short_abbr:"String",
		signature_agreement:"AgreementVar",
		statute_link:"String",
		user_agreement:"AgreementVar",
		wallet_agreement:"AgreementVar",
		website:"String"
	},
	Verification:{
		created_at:"String",
		is_verified:"Boolean",
		last_update:"String",
		notice:"String",
		procedure:"String",
		verificator:"String"
	},
	WaitWeight:{
		wait_sec:"Int",
		weight:"Int"
	},
	WebPushSubscriptionDto:{
		authKey:"String",
		createdAt:"DateTime",
		endpoint:"String",
		id:"String",
		isActive:"Boolean",
		p256dhKey:"String",
		updatedAt:"DateTime",
		userAgent:"String",
		username:"String"
	},
	ID: `scalar.ID` as const
}

export const Ops = {
query: "Query" as const,
	mutation: "Mutation" as const
}