/**
 * This file was automatically generated by joi-to-typescript
 * Do not modify this file manually
 */

export interface forgotPassword {
  body?: {
    email: string;
  };
}

export interface login {
  body?: {
    password: string;
    username: string;
  };
}

export interface logout {
  body?: {
    refreshToken: string;
  };
}

export interface refreshTokens {
  body?: {
    refreshToken: string;
  };
}

export interface resetPassword {
  body?: {
    password: string;
  };
  query?: {
    token: string;
  };
}

export interface verifyEmail {
  query?: {
    token: string;
  };
}
