/**
 * This file was automatically generated by joi-to-typescript
 * Do not modify this file manually
 */

export interface ISendNotification {
  message: string;
  subject: string;
  to: string;
  type: 'email' | 'push';
}

export interface RSendNotification {
  body: {
    message: string;
    subject: string;
    to: string;
    type: 'email' | 'push';
  };
}
