/**
 * This file was automatically generated by joi-to-typescript
 * Do not modify this file manually
 */

export interface IBankAccount {
  account_number: string;
  bank_name: string;
  card_number?: string;
  currency: 'RUB' | 'Other';
  details: {
    bik: string;
    corr: string;
    kpp: string;
  };
}

export interface ICreateDeposit {
  provider: 'yookassa';
  quantity: string;
}

export interface ICreateInitialPayment {
  provider: 'yookassa';
}

export interface IDeletePaymentMethod {
  method_id: number;
}

export interface IRecieveIPN {
  event: string;
  object: {
    /**
     * Unknown Property
     */
    [x: string]: unknown;
    amount: {
      /**
       * Unknown Property
       */
      [x: string]: unknown;
      currency: string;
      value: string;
    };
    authorization_details?: {
      /**
       * Unknown Property
       */
      [x: string]: unknown;
      auth_code?: string;
      rrn?: string;
      three_d_secure?: {
        /**
         * Unknown Property
         */
        [x: string]: unknown;
        applied?: boolean;
      };
    };
    created_at?: string;
    description?: string;
    expires_at?: string;
    id: string;
    income_amount: {
      /**
       * Unknown Property
       */
      [x: string]: unknown;
      currency: string;
      value: string;
    };
    metadata?: {
      /**
       * Unknown Property
       */
      [x: string]: unknown;
    };
    paid: boolean;
    payment_method: {
      /**
       * Unknown Property
       */
      [x: string]: unknown;
      card?: {
        /**
         * Unknown Property
         */
        [x: string]: unknown;
        card_type?: string;
        expiry_month?: string;
        expiry_year?: string;
        first6?: string;
        issuer_country?: string;
        issuer_name?: string;
        last4?: string;
      };
      id: string;
      saved?: boolean;
      title?: string;
      type: string;
    };
    refundable?: boolean;
    refunded_amount: {
      /**
       * Unknown Property
       */
      [x: string]: unknown;
      currency: string;
      value: string;
    };
    status: string;
    test?: boolean;
  };
  type: string;
}

export interface ISavePaymentMethod {
  data: {
      phone: string;
    } | ({
      account_number: string;
      bank_name: string;
      card_number?: string;
      currency: 'RUB' | 'Other';
      details: {
        bik: string;
        corr: string;
        kpp: string;
      };
    });
  method_id: number;
  method_type: 'sbp' | 'bank_transfer';
  username: string;
}

export interface ISbpDetails {
  phone: string;
}

export interface RDeletePaymentMethod {
  body: {
    method_id: number;
  };
  params?: {
    username: string;
  };
}

export interface RGetListPaymentMethods {
  params?: {
    username?: string;
  };
}

export interface RSavePaymentMethod {
  body: {
    data: {
        phone: string;
      } | ({
        account_number: string;
        bank_name: string;
        card_number?: string;
        currency: 'RUB' | 'Other';
        details: {
          bik: string;
          corr: string;
          kpp: string;
        };
      });
    method_id: number;
    method_type: 'sbp' | 'bank_transfer';
    username: string;
  };
  params?: {
    username: string;
  };
}
