// AUTO-GENERATED by cooptypes/scripts/gen-from-cpp.ts — DO NOT EDIT.
// Source: contracts/cpp/lib/core/ledger2/wallets.hpp
// Run `pnpm --filter cooptypes gen:from-cpp` to regenerate.

import type { IName } from '../interfaces/ledger2'

export type WalletKind = 'USER_SHARED' | 'COOPERATIVE'

export interface WalletMeta {
  /** Машинный идентификатор — eosio::name в контракте. */
  name: IName
  /** Человекочитаемое название для UI. */
  human_name: string
  /** Тип кошелька: USER_SHARED — L3-разрез по пайщику; COOPERATIVE — единый баланс. */
  kind: WalletKind
}

/**
 * Реестр кошельков ledger2 — точная копия `LEDGER2_WALLET_REGISTRY` из C++.
 */
export const LEDGER2_WALLET_REGISTRY: readonly WalletMeta[] = [
  { name: "w.reg.minshr", human_name: "Минимальный паевой взнос", kind: "USER_SHARED" },
  { name: "w.wal.share", human_name: "Паевой взнос пайщика", kind: "USER_SHARED" },
  { name: "w.wal.member", human_name: "ЦК — членская часть пайщика", kind: "USER_SHARED" },
  { name: "w.cap.blago", human_name: "ЦПП «Благорост» — единый кошелёк программы у пайщика", kind: "USER_SHARED" },
  { name: "w.cap.preimp", human_name: "Первичный учёт РИД-взносов до перехода на электронный учёт", kind: "USER_SHARED" },
  { name: "w.cap.gen", human_name: "ЦПП «Генератор» — единый кошелёк программы", kind: "COOPERATIVE" },
  { name: "w.reg.entry", human_name: "Вступительные взносы", kind: "COOPERATIVE" },
  { name: "w.wal.wthdrw", human_name: "Возвраты паевых взносов пайщикам (deprecated, не используется в новых операциях)", kind: "COOPERATIVE" },
  { name: "w.sov.infra", human_name: "Членские взносы за инфраструктуру кооп. платформы", kind: "COOPERATIVE" },
  { name: "w.sov.delgte", human_name: "Делегатские членские взносы", kind: "COOPERATIVE" },
  { name: "w.sov.expns", human_name: "Хозяйственные расходы из числа целевого финансирования", kind: "COOPERATIVE" },
  { name: "w.sov.mnused", human_name: "Использованные минимальные паевые взносы", kind: "COOPERATIVE" },
  { name: "w.cap.loan", human_name: "Выданные пайщикам беспроцентные займы", kind: "COOPERATIVE" },
  { name: "w.mkt.payout", human_name: "Выплаты поставщикам", kind: "COOPERATIVE" },
] as const

export interface ProgramWalletMapping {
  /** Машинный идентификатор кошелька. */
  wallet_name: IName
  /** Требуемый program_id для cross-contract проверки в `wallet::users.programs[]`; 0 — без проверки. */
  required_program_id: number
  /** Человекочитаемая метка программы из inline-комментария hpp; null для program_id == 0. */
  program_label: string | null
}

/**
 * Маппинг USER_SHARED-кошелька → program_id (`LEDGER2_USER_SHARED_PROGRAM_MAPPING`).
 * N→1: один program_id может ссылаться на несколько wallet_name (ЦК = share + member).
 */
export const LEDGER2_USER_SHARED_PROGRAM_MAPPING: readonly ProgramWalletMapping[] = [
  { wallet_name: "w.reg.minshr", required_program_id: 0, program_label: null },
  { wallet_name: "w.wal.share", required_program_id: 1, program_label: "ЦК" },
  { wallet_name: "w.wal.member", required_program_id: 1, program_label: "ЦК" },
  { wallet_name: "w.cap.blago", required_program_id: 4, program_label: "Благорост" },
  { wallet_name: "w.cap.gen", required_program_id: 3, program_label: "Генератор" },
  { wallet_name: "w.cap.preimp", required_program_id: 0, program_label: null },
] as const
