import type { AssetContributionStatement, InvestMembershipConvertation, InvestmentAgreement, ReturnByAssetStatement } from '../Templates'

export * as WalletAgreement from './1.WalletAgreement'
export * as RegulationElectronicSignature from './2.RegulationElectronicSignature'
export * as PrivacyPolicy from './3.PrivacyPolicy'
export * as UserAgreement from './4.UserAgreement'
export * as CoopenomicsAgreement from './50.CoopenomicsAgreement'
export * as SelectBranchStatement from './101.SelectBranchStatement'
export * as ParticipantApplication from './100.ParticipantApplication'
export * as DecisionOfParticipantApplication from './501.DecisionOfParticipantApplication'
export * as ProjectFreeDecision from './599.ProjectFreeDecision'
export * as FreeDecision from './600.FreeDecision'
export * as AssetContributionStatement from './700.AssetContributionStatement'
export * as ReturnByAssetStatement from './800.ReturnByAssetStatement'

export * as SosediAgreement from './699.SosediAgreement'
export * as AssetContributionDecision from './701.AssetContributionDecision'
export * as AssetContributionAct from './702.AssetContributionAct'
export * as ReturnByAssetDecision from './801.ReturnByAssetDecision'
export * as ReturnByAssetAct from './802.ReturnByAssetAct'

export * as InvestmentAgreement from './1000.InvestmentAgreement'
export * as InvestByResultStatement from './1001.InvestByResultStatement'
export * as InvestByResultAct from './1002.InvestByResultAct'
export * as InvestByMoneyStatement from './1005.InvestByMoneyStatement'
export * as InvestMembershipConvertation from './1010.InvestMembershipConvertation'

// общие собрания
export * as AnnualGeneralMeetingAgenda from './300.AnnualGeneralMeetingAgenda'
export * as SovietDecisionOnAnnualMeeting from './301.SovietDecisionOnAnnualMeeting'
export * as AnnualMeetingNotification from './302.AnnualMeetingNotification'
export * as VotingBallot from './303.VotingBallot'
export * as AnnualGeneralMeetingDecision from './304.AnnualGeneralMeetingDecision'
