import type { AssetContributionStatement, ReturnByAssetStatement } from '../templates'

export * as WalletAgreement from './1.WalletAgreement'
export * as RegulationElectronicSignature from './2.RegulationElectronicSignature'
export * as PrivacyPolicy from './3.PrivacyPolicy'
export * as UserAgreement from './4.UserAgreement'
export * as CoopenomicsAgreement from './50.CoopenomicsAgreement'
export * as SelectBranchStatement from './101.SelectBranchStatement'
export * as ParticipantApplication from './100.ParticipantApplication'
export * as DecisionOfParticipantApplication from './501.DecisionOfParticipantApplication'
export * as ProjectFreeDecision from './599.ProjectFreeDecision'
export * as FreeDecision from './600.FreeDecision'
export * as AssetContributionStatement from './700.AssetContributionStatement'
export * as ReturnByAssetStatement from './800.ReturnByAssetStatement'

export * as AssetContributionDecision from './701.AssetContributionDecision'
export * as AssetContributionAct from './702.AssetContributionAct'
export * as ReturnByAssetDecision from './801.ReturnByAssetDecision'
export * as ReturnByAssetAct from './802.ReturnByAssetAct'
