/**
 * This file was automatically generated by joi-to-typescript
 * Do not modify this file manually
 */

export interface IForgotPassword {
  email: string;
}

export interface ILogin {
  email: string;
  now: string;
  signature: string;
}

export interface ILogout {
  refreshToken: string;
}

export interface IRefreshTokens {
  refreshToken: string;
}

export interface IResetKeyBody {
  public_key: string;
  token: string;
}

export interface IVerifyEmail {
  token: string;
}

export interface RForgotKey {
  body: {
    email: string;
  };
}

export interface RLogin {
  body: {
    email: string;
    now: string;
    signature: string;
  };
}

export interface RLogout {
  body: {
    refreshToken: string;
  };
}

export interface RRefreshTokens {
  body: {
    refreshToken: string;
  };
}

export interface RResetKey {
  body: {
    public_key: string;
    token: string;
  };
}

export interface RVerifyEmail {
  query: {
    token: string;
  };
}
