/**
 * This file was automatically generated by joi-to-typescript
 * Do not modify this file manually
 */

export interface IForgotPassword {
  email: string;
}

export interface ILogin {
  email: string;
  password: string;
}

export interface ILogout {
  refreshToken: string;
}

export interface IRefreshTokens {
  refreshToken: string;
}

export interface IResetPasswordBody {
  password: string;
}

export interface IResetPasswordQuery {
  token: string;
}

export interface IVerifyEmail {
  token: string;
}

export interface RForgotPassword {
  body: {
    email: string;
  };
}

export interface RLogin {
  body: {
    email: string;
    password: string;
  };
}

export interface RLogout {
  body: {
    refreshToken: string;
  };
}

export interface RRefreshTokens {
  body: {
    refreshToken: string;
  };
}

export interface RResetPassword {
  body: {
    password: string;
  };
  query: {
    token: string;
  };
}

export interface RVerifyEmail {
  query: {
    token: string;
  };
}
