/**
 * This file was automatically generated by joi-to-typescript
 * Do not modify this file manually
 */

export interface ICreateDeposit {
  quantity: string;
}

// eslint-disable-next-line @typescript-eslint/no-empty-interface
export interface ICreateInitialPayment {}
