/**
 * This file was automatically generated by joi-to-typescript
 * Do not modify this file manually
 */

export interface ICreateDeposit {
  quantity: string;
}

export interface ICreateInitialPayment {}

export interface IGetCoopOrders {
  id?: string;
  limit?: number;
  page?: number;
  sort?: string;
  sortBy?: string;
  username?: string;
}

export interface IGetMyOrders {
  limit?: number;
  page?: number;
  sort?: string;
  sortBy?: string;
}

export interface RGetCoopOrders {
  query: {
    id?: string;
    limit?: number;
    page?: number;
    sort?: string;
    sortBy?: string;
    username?: string;
  };
}
