/**
 * This file was automatically generated by joi-to-typescript
 * Do not modify this file manually
 */

export interface ICreateDeposit {
  provider: string;
  quantity: string;
}

export interface ICreateInitialPayment {
  provider: string;
}
