/**
 * This file was automatically generated by joi-to-typescript
 * Do not modify this file manually
 */

export interface IDocument {
  hash: string;
  meta: object;
  public_key: string;
  signature: string;
}

export interface IJoinCooperative {
  privacy_agreement: {
    hash: string;
    meta: object;
    public_key: string;
    signature: string;
  };
  signature_agreement: {
    hash: string;
    meta: object;
    public_key: string;
    signature: string;
  };
  statement: {
    hash: string;
    meta: object;
    public_key: string;
    signature: string;
  };
  user_agreement: {
    hash: string;
    meta: object;
    public_key: string;
    signature: string;
  };
  username: string;
  wallet_agreement: {
    hash: string;
    meta: object;
    public_key: string;
    signature: string;
  };
}

export interface RJoinCooperative {
  body: {
    privacy_agreement: {
      hash: string;
      meta: object;
      public_key: string;
      signature: string;
    };
    signature_agreement: {
      hash: string;
      meta: object;
      public_key: string;
      signature: string;
    };
    statement: {
      hash: string;
      meta: object;
      public_key: string;
      signature: string;
    };
    user_agreement: {
      hash: string;
      meta: object;
      public_key: string;
      signature: string;
    };
    username: string;
    wallet_agreement: {
      hash: string;
      meta: object;
      public_key: string;
      signature: string;
    };
  };
}
