/**
 * This file was automatically generated by joi-to-typescript
 * Do not modify this file manually
 */

export interface IGetPluginConfig {
  name: string;
}

export interface IGetPluginList {
  limit?: number;
  name: string;
  page?: number;
}

export interface IGetPluginSchema {
  name: string;
}

export interface ISetPlugin {
  config?: object;
  enabled: boolean;
  name: string;
}

export interface RGetPluginConfig {
  query: {
    name: string;
  };
}

export interface RGetPluginList {
  query: {
    name: string;
  };
}

export interface RGetPluginSchema {
  query: {
    name: string;
  };
}

export interface RSetPlugin {
  body: {
    config?: object;
    enabled: boolean;
    name: string;
  };
}
