/**
 * This file was automatically generated by joi-to-typescript
 * Do not modify this file manually
 */

export interface loadAgenda {
  query?: {
    coopname: string;
  };
}

export interface loadStaff {
  query?: {
    coopname: string;
  };
}
