/**
 * This file was automatically generated by joi-to-typescript
 * Do not modify this file manually
 */

export type IInstall = {
  individual_data: {
    birthdate: string;
    email: string;
    first_name: string;
    full_address: string;
    last_name: string;
    middle_name: string;
    phone: string;
  };
  role: 'chairman' | 'member';
}[];

export interface RInstall {
  body: {
    individual_data: {
      birthdate: string;
      email: string;
      first_name: string;
      full_address: string;
      last_name: string;
      middle_name: string;
      phone: string;
    };
    role: 'chairman' | 'member';
  }[];
}
