export * as WalletAgreement from './1.WalletAgreement'
export * as RegulationElectronicSignature from './2.RegulationElectronicSignature'
export * as PrivacyPolicy from './3.PrivacyPolicy'
export * as UserAgreement from './4.UserAgreement'
export * as CoopenomicsAgreement from './50.CoopenomicsAgreement'
export * as ParticipantApplication from './100.ParticipantApplication'
export * as DecisionOfParticipantApplication from './501.DecisionOfParticipantApplication'
export * as SelectBranchStatement from './101.SelectBranchStatement'

export * from './registry'
