// Фичи для работы с проектами
export * as CreateProject from './CreateProject';
export * as CreateComponent from './CreateComponent';
export * as AddAuthor from './AddAuthor';
export * as ConvertSegment from './ConvertSegment';
export * as DeleteProject from './DeleteProject';
export * as EditProject from './EditProject';
export * as OpenCloseProject from './OpenCloseProject';
export * as RefreshSegment from './RefreshSegment';
export * as SetMaster from './SetMaster';
export * as SetPlan from './SetPlan';
export * as UpdateProjectStatus from './UpdateProjectStatus'
