/* eslint-disable */

export const AllTypesProps: Record<string,any> = {
	AccountType: "enum" as const,
	AddParticipantInput:{
		entrepreneur_data:"CreateEntrepreneurDataInput",
		individual_data:"CreateIndividualDataInput",
		organization_data:"CreateOrganizationDataInput",
		type:"AccountType"
	},
	AddTrustedAccountInput:{

	},
	AgreementInput:{

	},
	BankAccountDetailsInput:{

	},
	BankAccountInput:{
		details:"BankAccountDetailsInput"
	},
	Country: "enum" as const,
	CreateBankAccountInput:{
		data:"BankAccountInput"
	},
	CreateBranchInput:{

	},
	CreateDepositPaymentInput:{

	},
	CreateEntrepreneurDataInput:{
		bank_account:"BankAccountInput",
		country:"Country",
		details:"EntrepreneurDetailsInput"
	},
	CreateIndividualDataInput:{
		passport:"PassportInput"
	},
	CreateInitialPaymentInput:{

	},
	CreateOrganizationDataInput:{
		bank_account:"BankAccountInput",
		details:"OrganizationDetailsInput",
		represented_by:"RepresentedByInput",
		type:"OrganizationType"
	},
	CreateProjectFreeDecisionInput:{

	},
	DateTime: `scalar.DateTime` as const,
	DeleteAccountInput:{

	},
	DeleteBranchInput:{

	},
	DeletePaymentMethodInput:{

	},
	DeleteTrustedAccountInput:{

	},
	EditBranchInput:{

	},
	EntrepreneurDetailsInput:{

	},
	ExtensionInput:{
		config:"JSON",
		created_at:"DateTime",
		updated_at:"DateTime"
	},
	FreeDecisionGenerateDocumentInput:{

	},
	GenerateDocumentInput:{

	},
	GenerateDocumentOptionsInput:{

	},
	GetAccountInput:{

	},
	GetAccountsInput:{

	},
	GetBranchesInput:{

	},
	GetDocumentsFilterInput:{
		additionalFilters:"JSON"
	},
	GetDocumentsInput:{
		filter:"GetDocumentsFilterInput"
	},
	GetExtensionsInput:{

	},
	GetPaymentMethodsInput:{

	},
	GetPaymentsInput:{
		status:"PaymentStatus"
	},
	Init:{
		organization_data:"CreateOrganizationDataInput",
		vars:"VarsInput"
	},
	Install:{
		soviet:"SovietMemberInput"
	},
	JSON: `scalar.JSON` as const,
	LangType: "enum" as const,
	LoginInput:{

	},
	LogoutInput:{

	},
	MetaDocumentInput:{

	},
	Mutation:{
		addParticipant:{
			data:"AddParticipantInput"
		},
		addTrustedAccount:{
			data:"AddTrustedAccountInput"
		},
		createBankAccount:{
			data:"CreateBankAccountInput"
		},
		createBranch:{
			data:"CreateBranchInput"
		},
		createDeposit:{
			data:"CreateDepositPaymentInput"
		},
		createInitialPayment:{
			data:"CreateInitialPaymentInput"
		},
		createProjectOfFreeDecision:{
			data:"CreateProjectFreeDecisionInput"
		},
		deleteAccount:{
			data:"DeleteAccountInput"
		},
		deleteBranch:{
			data:"DeleteBranchInput"
		},
		deletePaymentMethod:{
			data:"DeletePaymentMethodInput"
		},
		deleteTrustedAccount:{
			data:"DeleteTrustedAccountInput"
		},
		editBranch:{
			data:"EditBranchInput"
		},
		generateFreeDecision:{
			data:"FreeDecisionGenerateDocumentInput",
			options:"GenerateDocumentOptionsInput"
		},
		generateParticipantApplication:{
			data:"ParticipantApplicationGenerateDocumentInput",
			options:"GenerateDocumentOptionsInput"
		},
		generateParticipantApplicationDecision:{
			data:"ParticipantApplicationDecisionGenerateDocumentInput",
			options:"GenerateDocumentOptionsInput"
		},
		generatePrivacyAgreement:{
			data:"GenerateDocumentInput",
			options:"GenerateDocumentOptionsInput"
		},
		generateProjectOfFreeDecision:{
			data:"ProjectFreeDecisionGenerateDocumentInput",
			options:"GenerateDocumentOptionsInput"
		},
		generateSelectBranchDocument:{
			data:"SelectBranchGenerateDocumentInput",
			options:"GenerateDocumentOptionsInput"
		},
		generateSignatureAgreement:{
			data:"GenerateDocumentInput",
			options:"GenerateDocumentOptionsInput"
		},
		generateUserAgreement:{
			data:"GenerateDocumentInput",
			options:"GenerateDocumentOptionsInput"
		},
		generateWalletAgreement:{
			data:"GenerateDocumentInput",
			options:"GenerateDocumentOptionsInput"
		},
		initSystem:{
			data:"Init"
		},
		installExtension:{
			data:"ExtensionInput"
		},
		installSystem:{
			data:"Install"
		},
		login:{
			data:"LoginInput"
		},
		logout:{
			data:"LogoutInput"
		},
		publishProjectOfFreeDecision:{
			data:"PublishProjectFreeDecisionInput"
		},
		refresh:{
			data:"RefreshInput"
		},
		registerAccount:{
			data:"RegisterAccountInput"
		},
		registerParticipant:{
			data:"RegisterParticipantInput"
		},
		resetKey:{
			data:"ResetKeyInput"
		},
		selectBranch:{
			data:"SelectBranchInput"
		},
		setPaymentStatus:{
			data:"SetPaymentStatusInput"
		},
		setWif:{
			data:"SetWifInput"
		},
		startResetKey:{
			data:"StartResetKeyInput"
		},
		uninstallExtension:{
			data:"UninstallExtensionInput"
		},
		updateAccount:{
			data:"UpdateAccountInput"
		},
		updateBankAccount:{
			data:"UpdateBankAccountInput"
		},
		updateExtension:{
			data:"ExtensionInput"
		},
		updateSystem:{
			data:"Update"
		}
	},
	OrganizationDetailsInput:{

	},
	OrganizationType: "enum" as const,
	PaginationInput:{

	},
	ParticipantApplicationDecisionGenerateDocumentInput:{

	},
	ParticipantApplicationGenerateDocumentInput:{

	},
	ParticipantApplicationSignedDocumentInput:{
		meta:"ParticipantApplicationSignedMetaDocumentInput"
	},
	ParticipantApplicationSignedMetaDocumentInput:{

	},
	PassportInput:{

	},
	PaymentStatus: "enum" as const,
	ProjectFreeDecisionGenerateDocumentInput:{

	},
	ProjectFreeDecisionSignedDocumentInput:{
		meta:"ProjectFreeDecisionSignedMetaDocumentInput"
	},
	ProjectFreeDecisionSignedMetaDocumentInput:{

	},
	PublishProjectFreeDecisionInput:{
		document:"ProjectFreeDecisionSignedDocumentInput"
	},
	Query:{
		getAccount:{
			data:"GetAccountInput"
		},
		getAccounts:{
			data:"GetAccountsInput",
			options:"PaginationInput"
		},
		getBranches:{
			data:"GetBranchesInput"
		},
		getDocuments:{
			data:"GetDocumentsInput"
		},
		getExtensions:{
			data:"GetExtensionsInput"
		},
		getPaymentMethods:{
			data:"GetPaymentMethodsInput"
		},
		getPayments:{
			data:"GetPaymentsInput",
			options:"PaginationInput"
		}
	},
	RefreshInput:{

	},
	RegisterAccountInput:{
		entrepreneur_data:"CreateEntrepreneurDataInput",
		individual_data:"CreateIndividualDataInput",
		organization_data:"CreateOrganizationDataInput",
		role:"RegisterRole",
		type:"AccountType"
	},
	RegisterParticipantInput:{
		privacy_agreement:"SignedDigitalDocumentInput",
		signature_agreement:"SignedDigitalDocumentInput",
		statement:"ParticipantApplicationSignedDocumentInput",
		user_agreement:"SignedDigitalDocumentInput",
		wallet_agreement:"SignedDigitalDocumentInput"
	},
	RegisterRole: "enum" as const,
	RepresentedByInput:{

	},
	ResetKeyInput:{

	},
	SelectBranchGenerateDocumentInput:{

	},
	SelectBranchInput:{
		document:"SelectBranchSignedDocumentInput"
	},
	SelectBranchSignedDocumentInput:{
		meta:"SelectBranchSignedMetaDocumentInput"
	},
	SelectBranchSignedMetaDocumentInput:{

	},
	SetPaymentStatusInput:{
		status:"PaymentStatus"
	},
	SetWifInput:{

	},
	SignedDigitalDocumentInput:{
		meta:"MetaDocumentInput"
	},
	SovietMemberInput:{
		individual_data:"CreateIndividualDataInput"
	},
	StartResetKeyInput:{

	},
	SystemStatus: "enum" as const,
	UninstallExtensionInput:{

	},
	Update:{
		organization_data:"UpdateOrganizationDataInput",
		vars:"VarsInput"
	},
	UpdateAccountInput:{
		entrepreneur_data:"UpdateEntrepreneurDataInput",
		individual_data:"UpdateIndividualDataInput",
		organization_data:"UpdateOrganizationDataInput",
		role:"RegisterRole",
		type:"AccountType"
	},
	UpdateBankAccountInput:{
		data:"BankAccountInput"
	},
	UpdateEntrepreneurDataInput:{
		country:"Country",
		details:"EntrepreneurDetailsInput"
	},
	UpdateIndividualDataInput:{
		passport:"PassportInput"
	},
	UpdateOrganizationDataInput:{
		details:"OrganizationDetailsInput",
		represented_by:"RepresentedByInput",
		type:"OrganizationType"
	},
	UserStatus: "enum" as const,
	VarsInput:{
		coopenomics_agreement:"AgreementInput",
		participant_application:"AgreementInput",
		privacy_agreement:"AgreementInput",
		signature_agreement:"AgreementInput",
		user_agreement:"AgreementInput",
		wallet_agreement:"AgreementInput"
	}
}

export const ReturnTypes: Record<string,any> = {
	Account:{
		blockchain_account:"BlockchainAccount",
		participant_account:"ParticipantAccount",
		provider_account:"MonoAccount",
		user_account:"UserAccount",
		username:"String"
	},
	AccountRamDelta:{
		account:"String",
		delta:"Int"
	},
	AccountResourceInfo:{
		available:"String",
		current_used:"String",
		last_usage_update_time:"String",
		max:"String",
		used:"String"
	},
	AccountsPaginationResult:{
		currentPage:"Int",
		items:"Account",
		totalCount:"Int",
		totalPages:"Int"
	},
	ActDetail:{
		action:"ExtendedBlockchainAction",
		document:"GeneratedDocument"
	},
	ActionAuthorization:{
		actor:"String",
		permission:"String"
	},
	ActionReceipt:{
		abi_sequence:"Int",
		act_digest:"String",
		auth_sequence:"AuthSequence",
		code_sequence:"Int",
		global_sequence:"String",
		receiver:"String",
		recv_sequence:"String"
	},
	AgendaWithDocuments:{
		action:"BlockchainAction",
		documents:"DocumentPackage",
		table:"BlockchainDecision"
	},
	AgreementVar:{
		protocol_day_month_year:"String",
		protocol_number:"String"
	},
	AuthSequence:{
		account:"String",
		sequence:"String"
	},
	Authority:{
		accounts:"PermissionLevelWeight",
		keys:"KeyWeight",
		threshold:"Int",
		waits:"WaitWeight"
	},
	BankAccount:{
		account_number:"String",
		bank_name:"String",
		card_number:"String",
		currency:"String",
		details:"BankAccountDetails"
	},
	BankAccountDetails:{
		bik:"String",
		corr:"String",
		kpp:"String"
	},
	BankPaymentMethod:{
		created_at:"DateTime",
		data:"BankAccount",
		is_default:"Boolean",
		method_id:"String",
		method_type:"String",
		updated_at:"DateTime",
		username:"String"
	},
	BlockchainAccount:{
		account_name:"String",
		core_liquid_balance:"String",
		cpu_limit:"AccountResourceInfo",
		cpu_weight:"String",
		created:"String",
		head_block_num:"Int",
		head_block_time:"String",
		last_code_update:"String",
		net_limit:"AccountResourceInfo",
		net_weight:"String",
		permissions:"Permission",
		privileged:"Boolean",
		ram_quota:"Int",
		ram_usage:"Int",
		refund_request:"RefundRequest",
		rex_info:"String",
		self_delegated_bandwidth:"ResourceDelegationDTO",
		total_resources:"ResourceOverview",
		voter_info:"String"
	},
	BlockchainAction:{
		account:"String",
		account_ram_deltas:"AccountRamDelta",
		action_ordinal:"Int",
		authorization:"ActionAuthorization",
		block_id:"String",
		block_num:"Int",
		chain_id:"String",
		console:"String",
		context_free:"Boolean",
		creator_action_ordinal:"Int",
		data:"JSON",
		elapsed:"Int",
		global_sequence:"String",
		name:"String",
		receipt:"ActionReceipt",
		receiver:"String",
		transaction_id:"String"
	},
	BlockchainDecision:{
		approved:"Boolean",
		authorization:"SignedBlockchainDocument",
		authorized:"Boolean",
		authorized_by:"String",
		batch_id:"Float",
		coopname:"String",
		created_at:"String",
		expired_at:"String",
		id:"Float",
		meta:"String",
		statement:"SignedBlockchainDocument",
		type:"String",
		username:"String",
		validated:"Boolean",
		votes_against:"String",
		votes_for:"String"
	},
	BlockchainInfoDTO:{
		block_cpu_limit:"Int",
		block_net_limit:"Int",
		chain_id:"String",
		fork_db_head_block_id:"String",
		fork_db_head_block_num:"Int",
		head_block_id:"String",
		head_block_num:"Int",
		head_block_producer:"String",
		head_block_time:"String",
		last_irreversible_block_id:"String",
		last_irreversible_block_num:"Int",
		last_irreversible_block_time:"String",
		server_version:"String",
		server_version_string:"String",
		virtual_block_cpu_limit:"Int",
		virtual_block_net_limit:"Int"
	},
	Branch:{
		bank_account:"BankPaymentMethod",
		braname:"String",
		city:"String",
		coopname:"String",
		country:"String",
		details:"OrganizationDetails",
		email:"String",
		fact_address:"String",
		full_address:"String",
		full_name:"String",
		phone:"String",
		represented_by:"RepresentedBy",
		short_name:"String",
		trusted:"Individual",
		trustee:"Individual",
		type:"String"
	},
	ContactsDTO:{
		chairman:"PublicChairman",
		details:"OrganizationDetails",
		email:"String",
		full_address:"String",
		full_name:"String",
		phone:"String"
	},
	CooperativeOperatorAccount:{
		announce:"String",
		coop_type:"String",
		created_at:"String",
		description:"String",
		document:"SignedBlockchainDocument",
		initial:"String",
		is_branched:"Boolean",
		is_cooperative:"Boolean",
		is_enrolled:"Boolean",
		meta:"String",
		minimum:"String",
		org_initial:"String",
		org_minimum:"String",
		org_registration:"String",
		parent_username:"String",
		referer:"String",
		registered_at:"String",
		registration:"String",
		registrator:"String",
		status:"String",
		storages:"String",
		type:"String",
		username:"String",
		verifications:"Verification"
	},
	CreatedProjectFreeDecision:{
		decision:"String",
		id:"String",
		question:"String"
	},
	DateTime: `scalar.DateTime` as const,
	DecisionDetail:{
		action:"ExtendedBlockchainAction",
		document:"DecisionDocumentUnion",
		votes_against:"ExtendedBlockchainAction",
		votes_for:"ExtendedBlockchainAction"
	},
	DecisionDocumentUnion:{
		"...on FreeDecisionDocument":"FreeDecisionDocument",
		"...on ParticipantApplicationDecisionDocument":"ParticipantApplicationDecisionDocument"
	},
	DocumentPackage:{
		acts:"ActDetail",
		decision:"DecisionDetail",
		links:"GeneratedDocument",
		statement:"StatementDetail"
	},
	DocumentsPaginationResult:{
		currentPage:"Int",
		items:"DocumentPackage",
		totalCount:"Int",
		totalPages:"Int"
	},
	Entrepreneur:{
		birthdate:"String",
		city:"String",
		country:"String",
		details:"EntrepreneurDetails",
		email:"String",
		first_name:"String",
		full_address:"String",
		last_name:"String",
		middle_name:"String",
		phone:"String",
		username:"String"
	},
	EntrepreneurDetails:{
		inn:"String",
		ogrn:"String"
	},
	ExtendedBlockchainAction:{
		account:"String",
		account_ram_deltas:"AccountRamDelta",
		action_ordinal:"Int",
		authorization:"ActionAuthorization",
		block_id:"String",
		block_num:"Int",
		chain_id:"String",
		console:"String",
		context_free:"Boolean",
		creator_action_ordinal:"Int",
		data:"JSON",
		elapsed:"Int",
		global_sequence:"String",
		name:"String",
		receipt:"ActionReceipt",
		receiver:"String",
		transaction_id:"String",
		user:"UserDataUnion"
	},
	Extension:{
		available:"Boolean",
		config:"JSON",
		created_at:"DateTime",
		description:"String",
		enabled:"Boolean",
		image:"String",
		installed:"Boolean",
		instructions:"String",
		name:"String",
		readme:"String",
		schema:"JSON",
		tags:"String",
		title:"String",
		updated_at:"DateTime"
	},
	FreeDecisionDocument:{
		binary:"String",
		full_title:"String",
		hash:"String",
		html:"String",
		meta:"FreeDecisionMetaDocumentOutput"
	},
	FreeDecisionMetaDocumentOutput:{
		block_num:"Int",
		coopname:"String",
		created_at:"String",
		decision_id:"Float",
		generator:"String",
		lang:"LangType",
		links:"String",
		project_id:"String",
		registry_id:"Int",
		timezone:"String",
		title:"String",
		username:"String",
		version:"String"
	},
	GeneratedDocument:{
		binary:"String",
		full_title:"String",
		hash:"String",
		html:"String",
		meta:"MetaDocument"
	},
	Individual:{
		birthdate:"String",
		email:"String",
		first_name:"String",
		full_address:"String",
		last_name:"String",
		middle_name:"String",
		passport:"Passport",
		phone:"String",
		username:"String"
	},
	JSON: `scalar.JSON` as const,
	KeyWeight:{
		key:"String",
		weight:"Int"
	},
	MetaDocument:{
		block_num:"Int",
		coopname:"String",
		created_at:"String",
		generator:"String",
		lang:"LangType",
		links:"String",
		registry_id:"Int",
		timezone:"String",
		title:"String",
		username:"String",
		version:"String"
	},
	MonoAccount:{
		email:"String",
		has_account:"Boolean",
		initial_order:"String",
		is_email_verified:"Boolean",
		is_registered:"Boolean",
		message:"String",
		public_key:"String",
		referer:"String",
		role:"String",
		status:"UserStatus",
		type:"String",
		username:"String"
	},
	Mutation:{
		addParticipant:"Account",
		addTrustedAccount:"Branch",
		createBankAccount:"PaymentMethod",
		createBranch:"Branch",
		createDeposit:"Payment",
		createInitialPayment:"Payment",
		createProjectOfFreeDecision:"CreatedProjectFreeDecision",
		deleteAccount:"Boolean",
		deleteBranch:"Boolean",
		deletePaymentMethod:"Boolean",
		deleteTrustedAccount:"Branch",
		editBranch:"Branch",
		generateFreeDecision:"ProjectFreeDecisionDocument",
		generateParticipantApplication:"ParticipantApplicationDocument",
		generateParticipantApplicationDecision:"ParticipantApplicationDecisionDocument",
		generatePrivacyAgreement:"GeneratedDocument",
		generateProjectOfFreeDecision:"ProjectFreeDecisionDocument",
		generateSelectBranchDocument:"SelectBranchDocument",
		generateSignatureAgreement:"GeneratedDocument",
		generateUserAgreement:"GeneratedDocument",
		generateWalletAgreement:"GeneratedDocument",
		initSystem:"SystemInfo",
		installExtension:"Extension",
		installSystem:"SystemInfo",
		login:"RegisteredAccount",
		logout:"Boolean",
		publishProjectOfFreeDecision:"Boolean",
		refresh:"RegisteredAccount",
		registerAccount:"RegisteredAccount",
		registerParticipant:"Account",
		resetKey:"Boolean",
		selectBranch:"Boolean",
		setPaymentStatus:"Payment",
		setWif:"Boolean",
		startResetKey:"Boolean",
		uninstallExtension:"Boolean",
		updateAccount:"Account",
		updateBankAccount:"PaymentMethod",
		updateExtension:"Extension",
		updateSystem:"SystemInfo"
	},
	Organization:{
		city:"String",
		country:"String",
		details:"OrganizationDetails",
		email:"String",
		fact_address:"String",
		full_address:"String",
		full_name:"String",
		phone:"String",
		represented_by:"RepresentedBy",
		short_name:"String",
		type:"String",
		username:"String"
	},
	OrganizationDetails:{
		inn:"String",
		kpp:"String",
		ogrn:"String"
	},
	ParticipantAccount:{
		braname:"String",
		created_at:"DateTime",
		has_vote:"Boolean",
		is_initial:"Boolean",
		is_minimum:"Boolean",
		last_min_pay:"DateTime",
		last_update:"DateTime",
		status:"String",
		type:"String",
		username:"String"
	},
	ParticipantApplicationDecisionDocument:{
		binary:"String",
		full_title:"String",
		hash:"String",
		html:"String",
		meta:"ParticipantApplicationDecisionMetaDocumentOutput"
	},
	ParticipantApplicationDecisionMetaDocumentOutput:{
		block_num:"Int",
		coopname:"String",
		created_at:"String",
		decision_id:"Float",
		generator:"String",
		lang:"LangType",
		links:"String",
		registry_id:"Int",
		timezone:"String",
		title:"String",
		username:"String",
		version:"String"
	},
	ParticipantApplicationDocument:{
		binary:"String",
		full_title:"String",
		hash:"String",
		html:"String",
		meta:"ParticipantApplicationMetaDocumentOutput"
	},
	ParticipantApplicationMetaDocumentOutput:{
		block_num:"Int",
		coopname:"String",
		created_at:"String",
		generator:"String",
		lang:"LangType",
		links:"String",
		registry_id:"Int",
		timezone:"String",
		title:"String",
		username:"String",
		version:"String"
	},
	Passport:{
		code:"String",
		issued_at:"String",
		issued_by:"String",
		number:"Int",
		series:"Int"
	},
	Payment:{
		amount:"Float",
		blockchain_id:"Float",
		created_at:"DateTime",
		details:"PaymentDetails",
		expired_at:"DateTime",
		id:"String",
		message:"String",
		provider:"String",
		status:"PaymentStatus",
		symbol:"String",
		updated_at:"DateTime",
		username:"String"
	},
	PaymentDetails:{
		amount_plus_fee:"String",
		amount_without_fee:"String",
		data:"String",
		fact_fee_percent:"Float",
		fee_amount:"String",
		fee_percent:"Float",
		tolerance_percent:"Float"
	},
	PaymentMethod:{
		created_at:"DateTime",
		data:"PaymentMethodData",
		is_default:"Boolean",
		method_id:"String",
		method_type:"String",
		updated_at:"DateTime",
		username:"String"
	},
	PaymentMethodData:{
		"...on BankAccount":"BankAccount",
		"...on SbpAccount":"SbpAccount"
	},
	PaymentMethodPaginationResult:{
		currentPage:"Int",
		items:"PaymentMethod",
		totalCount:"Int",
		totalPages:"Int"
	},
	PaymentPaginationResult:{
		currentPage:"Int",
		items:"Payment",
		totalCount:"Int",
		totalPages:"Int"
	},
	Permission:{
		parent:"String",
		perm_name:"String",
		required_auth:"Authority"
	},
	PermissionLevel:{
		actor:"String",
		permission:"String"
	},
	PermissionLevelWeight:{
		permission:"PermissionLevel",
		weight:"Int"
	},
	ProjectFreeDecisionDocument:{
		binary:"String",
		full_title:"String",
		hash:"String",
		html:"String",
		meta:"ProjectFreeDecisionMetaDocumentOutput"
	},
	ProjectFreeDecisionMetaDocumentOutput:{
		block_num:"Int",
		coopname:"String",
		created_at:"String",
		generator:"String",
		lang:"LangType",
		links:"String",
		project_id:"String",
		registry_id:"Int",
		timezone:"String",
		title:"String",
		username:"String",
		version:"String"
	},
	PublicChairman:{
		first_name:"String",
		last_name:"String",
		middle_name:"String"
	},
	Query:{
		getAccount:"Account",
		getAccounts:"AccountsPaginationResult",
		getAgenda:"AgendaWithDocuments",
		getBranches:"Branch",
		getDocuments:"DocumentsPaginationResult",
		getExtensions:"Extension",
		getPaymentMethods:"PaymentMethodPaginationResult",
		getPayments:"PaymentPaginationResult",
		getSystemInfo:"SystemInfo"
	},
	RefundRequest:{
		cpu_amount:"String",
		net_amount:"String",
		owner:"String",
		request_time:"String"
	},
	RegisteredAccount:{
		account:"Account",
		tokens:"Tokens"
	},
	RepresentedBy:{
		based_on:"String",
		first_name:"String",
		last_name:"String",
		middle_name:"String",
		position:"String"
	},
	ResourceDelegationDTO:{
		cpu_weight:"String",
		from:"String",
		net_weight:"String",
		to:"String"
	},
	ResourceOverview:{
		cpu_weight:"String",
		net_weight:"String",
		owner:"String",
		ram_bytes:"Int"
	},
	SbpAccount:{
		phone:"String"
	},
	SelectBranchDocument:{
		binary:"String",
		full_title:"String",
		hash:"String",
		html:"String",
		meta:"SelectBranchMetaDocumentOutput"
	},
	SelectBranchMetaDocumentOutput:{
		block_num:"Int",
		braname:"String",
		coopname:"String",
		created_at:"String",
		generator:"String",
		lang:"LangType",
		links:"String",
		registry_id:"Int",
		timezone:"String",
		title:"String",
		username:"String",
		version:"String"
	},
	SignedBlockchainDocument:{
		hash:"String",
		meta:"String",
		public_key:"String",
		signature:"String"
	},
	StatementDetail:{
		action:"ExtendedBlockchainAction",
		document:"StatementDocumentUnion"
	},
	StatementDocumentUnion:{
		"...on ParticipantApplicationDocument":"ParticipantApplicationDocument",
		"...on ProjectFreeDecisionDocument":"ProjectFreeDecisionDocument"
	},
	SystemInfo:{
		blockchain_account:"BlockchainAccount",
		blockchain_info:"BlockchainInfoDTO",
		contacts:"ContactsDTO",
		cooperator_account:"CooperativeOperatorAccount",
		coopname:"String",
		system_status:"SystemStatus",
		vars:"Vars"
	},
	Token:{
		expires:"DateTime",
		token:"String"
	},
	Tokens:{
		access:"Token",
		refresh:"Token"
	},
	UserAccount:{
		meta:"String",
		referer:"String",
		registered_at:"String",
		registrator:"String",
		status:"String",
		storages:"String",
		type:"String",
		username:"String",
		verifications:"Verification"
	},
	UserDataUnion:{
		"...on Entrepreneur":"Entrepreneur",
		"...on Individual":"Individual",
		"...on Organization":"Organization"
	},
	Vars:{
		confidential_email:"String",
		confidential_link:"String",
		contact_email:"String",
		coopenomics_agreement:"AgreementVar",
		coopname:"String",
		full_abbr:"String",
		full_abbr_dative:"String",
		full_abbr_genitive:"String",
		name:"String",
		participant_application:"AgreementVar",
		passport_request:"String",
		privacy_agreement:"AgreementVar",
		short_abbr:"String",
		signature_agreement:"AgreementVar",
		user_agreement:"AgreementVar",
		wallet_agreement:"AgreementVar",
		website:"String"
	},
	Verification:{
		created_at:"String",
		is_verified:"Boolean",
		last_update:"String",
		notice:"String",
		procedure:"String",
		verificator:"String"
	},
	WaitWeight:{
		wait_sec:"Int",
		weight:"Int"
	}
}

export const Ops = {
query: "Query" as const,
	mutation: "Mutation" as const
}