site_name: Цифровой Кооператив
extra_javascript:
  - js/metrika.js
  
theme:
  name: material
  custom_dir: overrides
  palette:
    - scheme: default
      toggle:
        icon: material/brightness-7 
        name: Switch to dark mode
      primary: black
      accent: teal

    - scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
      primary: black
      accent: teal
  font:
    text: Roboto Mono
    
  logo: assets/logo-white.png
  icon:
    repo: fontawesome/brands/github
    tag:
      chairman: fontawesome/solid/user-tie
      member: fontawesome/solid/users
      user: fontawesome/solid/user
      dev: fontawesome/solid/code
  
  language: ru
  features:
    - content.code.copy
    - navigation.path
    # - navigation.tabs
    # - navigation.sections
    - navigation.instant
    - navigation.instant.prefetch
    # - navigation.expand
    - navigation.indexes
    - toc.follow
    # - toc.integrate
    - search.share
    - navigation.top
    - navigation.footer
    
repo_url: https://github.com/coopenomics/mono

plugins:
  - search
  - macros
  - section-index
  - tags
  # - awesome-pages
  # - table-reader
  # - social:https://squidfunk.github.io/mkdocs-material/
  #   cards_layout: default

extra_css:
  - css/extra.css
  
extra:
  generator: false
  tags:
    Председатель: chairman
    Член совета: member
    Пайщик: user
    Разработчик: dev
  # social:
  #   - icon: fontawesome/brands/telegram
  #     link: https://twitter.com/your-profile

copyright: ПК «ВОСХОД» &copy; 2025

markdown_extensions:
  - admonition
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.details
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format

  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - md_in_html
  - toc:
      permalink: true
  - pymdownx.tabbed:
      alternate_style: true
nav:
  - Введение: index.md
  - Лицензия: new/installation/index.md          # Главная страница раздела
  - Облачная поставка: new/connection/index.md
  - Установка: new/installation/chairman.md
  - Дашборд подключения: new/connection/dashboard.md
  - Разработчикам:
    - new/installation/dev.md
    - Быстрый старт: new/installation/dev/quick-start.md
    - Язык API: new/installation/dev/graphql.md
    - SDK: new/installation/dev/sdk.md
    - Аутентификация: new/installation/dev/auth.md
    - Подробный старт: new/installation/dev/init.md
    
  - Регистрация пайщика: 
    - new/registration/index.md
    - Вступить в пайщики: new/registration/join.md
    - Принять пайщика: new/registration/accept.md
    - Разработчикам: new/registration/dev.md

  - Вход в систему:
    - Вход пайщика: new/auth/signin.md

  - Аккаунты:
    - new/accounts/index.md

  - Электронная подпись:
    - new/signature/index.md
  
  - Фабрика документов:
    - new/factory/index.md

  - Блокчейн:
    - new/blockchain/index.md
    
  - Смарт-контракты:
    - new/contracts/index.md
    
  - Навигатор: new/navigator/index.md

  - Стол пайщика:
      - Кошелёк:
          - Обзор: new/participant/wallet.md
          - Паевой взнос: new/participant/wallet-topup.md
          - Возврат взноса: new/participant/wallet-refund.md
      - Удостоверение: new/participant/profile.md
      - Реквизиты: new/participant/requisites.md
      - Документы: new/participant/documents.md
      - Платежи: new/participant/payments.md
      - Собрания: new/participant/meetings.md
      - Контакты: new/participant/contacts.md

  - Стол совета:
      - Повестка совета: new/council/agenda.md
      - Реестр пайщиков: new/council/participants.md
      - Реестр документов: new/council/documents.md
      - Реестр платежей: new/council/payments.md
      - Реестр собраний: new/council/meetings.md
      - Реестр кошельков: new/council/wallets.md
    
  - Стол председателя:
    - Запросы одобрений: new/chairman/approval-requests.md
    - Магазин приложений: new/chairman/app-store.md
    - Стартовые страницы: new/chairman/start-pages.md
    - Члены совета: new/chairman/board-members.md
    - Кооперативные участки: new/chairman/cooperative-branches.md
    - Регистрационные взносы: new/chairman/registration-fees.md
    - Ключ кооператива: new/chairman/cooperative-key.md
    - Контакты кооператива: new/chairman/cooperative-contacts.md
  
  - Стол вычислительных ресурсов:
    - Аренда квот ресурсов: new/resources/quotas.md
    - Монитор ресурсов: new/resources/monitor.md
    - Настройки аренды ресурсов: new/resources/settings.md
    - Лог ресурсов: new/resources/log.md
    
  - Общие собрания: new/meet/index.md
  - Бухгалтерия: new/buh/index.md

  - Благорост:
    - Адаптация: new/blagorost/adaptation.md
    - Профиль: new/blagorost/profile.md
    - Кошельки: new/blagorost/wallets.md
    - Мастерская: new/blagorost/projects-list.md
    - Получение допуска: new/blagorost/clearance.md
    - Жизненный цикл компонента: new/blagorost/lifecycle.md
    - Моё время: new/blagorost/commits.md
    - Голосование: new/blagorost/voting.md
    - Результат и получение доли: new/blagorost/results.md
    - Создание проекта и компонента: new/blagorost/project-create.md
    - Назначение мастера и план: new/blagorost/master-and-plan.md
    - Артефакты: new/blagorost/artifacts.md
    - Результат интеллектуальной деятельности: new/blagorost/intellectual-property.md
    - Инвестирование: new/blagorost/investments.md
  
