name: Publish Docs

on:
  push:
    branches:
      - dev
      - main
      - testnet
      
jobs:
  build-and-publish-docs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install pnpm
        run: npm install -g pnpm

      - name: Install Python requirements
        run: |
          python -m venv venv
          source venv/bin/activate
          pip install mkdocs-material mkdocs-macros-plugin mkdocs-section-index pymdown-extensions
        working-directory: ./components/docs
        
      - name: Install Node.js dependencies
        run: pnpm install
        working-directory: ./components/docs

      - name: Patch spectaql-config.yml for CI
        run: |
          sed -i.bak "0,/url:.*/s|url:.*|url: 'https://testnet.coopenomics.world/backend/v1/graphql'|" spectaql-config.yml
        working-directory: ./components/controller

      - name: Show patched spectaql-config.yml
        run: cat spectaql-config.yml
        working-directory: ./components/controller

      - name: Build cooptypes
        run: pnpm run build
        working-directory: ./components/cooptypes

      - name: Generate controller docs
        run: pnpm run docs
        working-directory: ./components/controller

      - name: Copy controller docs
        run: |
          mkdir -p ./components/docs/docs/graphql
          cp -r ./components/controller/docs/* ./components/docs/docs/graphql/

      - name: Generate sdk docs
        run: pnpm run docs
        working-directory: ./components/sdk

      - name: Copy sdk docs
        run: |
          mkdir -p ./components/docs/docs/sdk
          cp -r ./components/sdk/docs/* ./components/docs/docs/sdk/

      - name: Generate cooptypes docs
        run: pnpm run docs
        working-directory: ./components/cooptypes

      - name: Copy cooptypes docs
        run: |
          mkdir -p ./components/docs/docs/cooptypes
          cp -r ./components/cooptypes/docs/* ./components/docs/docs/cooptypes/

      - name: Publish to GitHub Pages
        run: npx gh-pages --nojekyll -d site --repo git@github.com:coopenomics/mono.git
        working-directory: ./components/docs
        env:
          GIT_AUTHOR_NAME: github-actions
          GIT_AUTHOR_EMAIL: github-actions@github.com
          GIT_COMMITTER_NAME: github-actions
          GIT_COMMITTER_EMAIL: github-actions@github.com
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

