// Generated by eosio-abi2ts 1.2.2 - eosio::abi/1.2

export type IName = string
export type IUint64 = number | string

export interface IAddtrusted {
  coopname: IName
  braname: IName
  trusted: IName
}

export interface IBranchstat {
  coopname: IName
  count: IUint64
}

export interface ICoobranch {
  braname: IName
  trustee: IName
  trusted: IName[]
}

export interface ICreatebranch {
  coopname: IName
  braname: IName
  trustee: IName
}

export interface IDeletebranch {
  coopname: IName
  braname: IName
}

export interface IDeltrusted {
  coopname: IName
  braname: IName
  trusted: IName
}

export interface IEditbranch {
  coopname: IName
  braname: IName
  trustee: IName
}

export interface IInit {
}

export interface IMigrate {
}
