// Generated by eosio-abi2ts 1.2.2 - eosio::abi/1.2

export type IAsset = string
export type IName = string
export type IChecksum256 = string
export type IPublicKey = string
export type ISignature = string
export type ITimePointSec = string
export type IInt64 = number | string
export type IUint64 = number | string

export interface IAccumulate {
  coopname: IName
  amount: IAsset
}

export interface IAddauthor {
  coopname: IName
  application: IName
  project_hash: IChecksum256
  author: IName
  shares: IUint64
}

export interface IAllocate {
  coopname: IName
  application: IName
  project_hash: IChecksum256
  result_hash: IChecksum256
  amount: IAsset
}

export interface IApprovecmmt {
  coopname: IName
  application: IName
  approver: IName
  commit_hash: IChecksum256
  approved_specification: IDocument
}

export interface IApproveinvst {
  coopname: IName
  application: IName
  approver: IName
  invest_hash: IChecksum256
  approved_statement: IDocument
}

export interface IApprovereg {
  coopname: IName
  application: IName
  approver: IName
  project_hash: IChecksum256
  username: IName
  approved_agreement: IDocument
}

export interface IAuthor {
  id: IUint64
  project_hash: IChecksum256
  username: IName
  shares: IUint64
}

export interface IAuthorize {
  coopname: IName
  claim_id: IUint64
  decision: IDocument
}

export interface IAuthwithdraw {
  coopname: IName
  withdraw_hash: IChecksum256
}

export interface ICapauthinvst {
  coopname: IName
  invest_id: IUint64
  authorization: IDocument
}

export interface ICapauthwthdc {
  coopname: IName
  withdraw_id: IUint64
  authorization: IDocument
}

export interface ICapauthwthdr {
  coopname: IName
  withdraw_id: IUint64
  authorization: IDocument
}

export interface ICapregcontr {
  coopname: IName
  contributor_id: IUint64
  authorization: IDocument
}

export interface IClaim {
  id: IUint64
  claim_hash: IChecksum256
  project_hash: IChecksum256
  result_hash: IChecksum256
  coopname: IName
  owner: IName
  type: IName
  status: IName
  created_at: ITimePointSec
  amount: IAsset
  statement: IDocument
  decision: IDocument
  act1: IDocument
  act2: IDocument
}

export interface ICommit {
  id: IUint64
  coopname: IName
  application: IName
  username: IName
  status: IName
  project_hash: IChecksum256
  result_hash: IChecksum256
  commit_hash: IChecksum256
  spended: IAsset
  specification: IDocument
  approved_specification: IDocument
  authorization: IDocument
  created_at: ITimePointSec
}

export interface IContributor {
  id: IUint64
  coopname: IName
  username: IName
  project_hash: IChecksum256
  status: IName
  created_at: ITimePointSec
  agreement: IDocument
  approved_agreement: IDocument
  authorization: IDocument
  invested: IAsset
  spended: IAsset
  available: IAsset
  withdrawed: IAsset
  converted: IAsset
}

export interface ICreateclaim {
  coopname: IName
  application: IName
  owner: IName
  result_hash: IChecksum256
  claim_hash: IChecksum256
}

export interface ICreatecmmt {
  coopname: IName
  application: IName
  creator: IName
  result_hash: IChecksum256
  commit_hash: IChecksum256
  spended: IAsset
  specification: IDocument
}

export interface ICreateinvest {
  coopname: IName
  application: IName
  username: IName
  project_hash: IChecksum256
  invest_hash: IChecksum256
  amount: IAsset
  statement: IDocument
}

export interface ICreateproj {
  project_hash: IChecksum256
  coopname: IName
  application: IName
  title: string
  description: string
  terms: string
  subject: string
}

export interface ICreateresult {
  coopname: IName
  application: IName
  project_hash: IChecksum256
  result_hash: IChecksum256
}

export interface ICreatewthd1 {
  coopname: IName
  application: IName
  username: IName
  result_hash: IChecksum256
  withdraw_hash: IChecksum256
  commit_hashes: IChecksum256[]
  contribution_statement: IDocument
  return_statement: IDocument
}

export interface ICreator {
  id: IUint64
  project_hash: IChecksum256
  result_hash: IChecksum256
  username: IName
  spended: IAsset
}

export interface IDocument {
  hash: IChecksum256
  public_key: IPublicKey
  signature: ISignature
  meta: string
}

export interface IGlobalState {
  coopname: IName
  program_id: IUint64
  total_shares: IAsset
  total_contributions: IAsset
  total_rewards_distributed: IAsset
  total_withdrawed: IAsset
  total_intellectual_contributions: IAsset
  total_property_contributions: IAsset
  accumulated_amount: IAsset
  cumulative_reward_per_share: IInt64
}

export interface IInit {
  coopname: IName
  initiator: IName
  program_id: IUint64
}

export interface IInvest {
  id: IUint64
  coopname: IName
  application: IName
  username: IName
  invest_hash: IChecksum256
  project_hash: IChecksum256
  amount: IAsset
  status: IName
  invested_at: ITimePointSec
  statement: IDocument
  approved_statement: IDocument
}

export interface IProject {
  id: IUint64
  project_hash: IChecksum256
  coopname: IName
  application: IName
  status: IName
  title: string
  description: string
  terms: string
  subject: string
  authors_count: IUint64
  authors_shares: IUint64
  target: IAsset
  invested: IAsset
  available: IAsset
  generated: IAsset
  expenses: IAsset
  aid_with_return: IAsset
  aid_without_return: IAsset
  total_spent: IAsset
  created_at: ITimePointSec
}

export interface IRefresh {
  coopname: IName
  username: IName
}

export interface IRegcontrib {
  coopname: IName
  application: IName
  username: IName
  project_hash: IChecksum256
  created_at: ITimePointSec
  agreement: IDocument
}

export interface IResult {
  id: IUint64
  result_hash: IChecksum256
  project_hash: IChecksum256
  status: IName
  coopname: IName
  created_at: ITimePointSec
  expired_at: ITimePointSec
  authors_shares: IUint64
  authors_count: IUint64
  commits_count: IUint64
  allocated: IAsset
  available: IAsset
  spended: IAsset
  creators_amount: IAsset
  creators_bonus: IAsset
  authors_bonus: IAsset
  generated_amount: IAsset
  participants_bonus: IAsset
  total_amount: IAsset
  participants_bonus_remain: IAsset
}

export interface IResultAuthor {
  id: IUint64
  project_hash: IChecksum256
  result_hash: IChecksum256
  username: IName
  shares: IUint64
}

export interface ISetact1 {
  coopname: IName
  application: IName
  owner: IName
  claim_hash: IChecksum256
  act: IDocument
}

export interface ISetact2 {
  coopname: IName
  application: IName
  owner: IName
  result_hash: IChecksum256
  act: IDocument
}

export interface ISetstatement {
  coopname: IName
  application: IName
  owner: IName
  result_hash: IChecksum256
  statement: IDocument
}

export interface IStartdistrbn {
  coopname: IName
  application: IName
  result_hash: IChecksum256
}

export interface IWithdraw {
  id: IUint64
  coopname: IName
  project_hash: IChecksum256
  result_hash: IChecksum256
  withdraw_hash: IChecksum256
  username: IName
  status: IName
  commit_hashes: IChecksum256[]
  amount: IAsset
  contribution_statement: IDocument
  return_statement: IDocument
  approved_contribution_statement: IDocument
  approved_return_statement: IDocument
  authorized_contribution_statement: IDocument
  authorized_return_statement: IDocument
  created_at: ITimePointSec
}
