// Generated by eosio-abi2ts 1.2.2 - eosio::abi/1.2

export type IName = string
export type IUint64 = number | string

export interface ICounts extends ICountsBase {
}

export interface ICountsBase {
  key: IName
  secondary_key: IName
  value: IUint64
}

export interface ICreatedraft {
  scope: IName
  username: IName
  registry_id: IUint64
  lang: IName
  title: string
  description: string
  context: string
  model: string
  translation_data: string
}

export interface ICreatetrans {
  scope: IName
  username: IName
  draft_id: IUint64
  lang: IName
  data: string
}

export interface IDeldraft {
  scope: IName
  username: IName
  draft_id: IUint64
}

export interface IDeltrans {
  scope: IName
  username: IName
  translate_id: IUint64
}

export interface IEdittrans {
  scope: IName
  username: IName
  translate_id: IUint64
  data: string
}

export interface IMigrate {
}

export interface INewid {
  scope: IName
  id: IUint64
}

export interface IOnedraft {
  id: IUint64
  registry_id: IUint64
  version: IUint64
  default_translation_id: IUint64
  title: string
  description: string
  context: string
  model: string
}

export interface ITranslation {
  id: IUint64
  draft_id: IUint64
  lang: IName
  data: string
}
