// Generated by eosio-abi2ts 1.2.2 - eosio::abi/1.2
// Источник правды: components/contracts/build/contracts/marketplace/marketplace.abi
// (паевая модель «Стола заказов», компонент 68: canonical actions трёх процессов
// p.mkt.supply / p.mkt.return / p.mkt.wroff поверх Ledger2::apply; правится вручную
// синхронно с ABI — генератор abi2ts в репозитории не установлен).
// Выплата поставщику разделена на три action'а вокруг контракта gateway
// (E11 техдолг 598-16, Locked Decision L12):
//   - payout      — backend инициирует исходящий платёж (inline → gateway::createoutpay);
//   - payconfirm  — callback gateway::outcomplete (auth=_gateway), здесь Дт 76 / Кт 51;
//   - paydecline  — callback gateway::outdecline (auth=_gateway), без ledger-движения.

export type IAsset = string
export type IName = string
export type IChecksum256 = string
export type IPublicKey = string
export type ISignature = string
export type ITimePointSec = string
export type IUint32 = number
export type IUint64 = number | string
export type IBool = boolean

// ── Базовые структуры (импортируются из других контрактов через ABI) ─────

export interface ISignatureInfo {
  id: IUint32
  signed_hash: IChecksum256
  signer: IName
  public_key: IPublicKey
  signature: ISignature
  signed_at: ITimePointSec
  meta: string
}

export interface IDocument2 {
  version: string
  hash: IChecksum256
  doc_hash: IChecksum256
  meta_hash: IChecksum256
  meta: string
  signatures: ISignatureInfo[]
}

// ── p.mkt.supply: actions ────────────────────────────────────────────────

export interface ICreateOrder {
  coopname: IName
  orderer: IName
  order_hash: IChecksum256
  offer_hash: IChecksum256
  offerer: IName
  delivery_braname: IName
  quantity: IAsset
  unit_price: IAsset
  package_size: IAsset
  warranty_period_secs: IUint32
  batch_hash: IChecksum256
}

/**
 * Адресат перевода по заявлению 1110: заказ и его доля членской части.
 * Заявление одно на всё оформление, а нитка процесса ведётся по заказу —
 * контракт эмитит `o.mkt.conv` на каждый адресат с `process_hash = order_hash`.
 */
export interface IConvertTarget {
  /** Хэш заказа, который оплачивает эта часть перевода (заказа ещё нет). */
  order_hash: IChecksum256
  /** Членская часть перевода под этот заказ. */
  amount: IAsset
}

export interface IConvert {
  coopname: IName
  orderer: IName
  /** Разбивка членской части перевода по заказам; пустой список — только публикация заявления. */
  targets: IConvertTarget[]
  convert_statement: IDocument2
}

export interface IStockOrder {
  coopname: IName
  orderer: IName
  order_hash: IChecksum256
  offer_hash: IChecksum256
  delivery_braname: IName
  quantity: IAsset
  unit_price: IAsset
  package_size: IAsset
  warranty_period_secs: IUint32
  batch_hash: IChecksum256
}

export interface IMarkdown {
  coopname: IName
  order_hash: IChecksum256
  amount: IAsset
}

export interface ISetFee {
  coopname: IName
  membership_fee_percent: IUint64
}

export interface IMktConfig {
  membership_fee_percent: IUint64
}

export interface ICancelOrder {
  coopname: IName
  orderer: IName
  order_hash: IChecksum256
}

export interface IExpireOrder {
  coopname: IName
  order_hash: IChecksum256
}

export interface ICloseOrder {
  coopname: IName
  order_hash: IChecksum256
}

export interface IAcceptOrder {
  coopname: IName
  offerer: IName
  order_hash: IChecksum256
}

export interface IDeclineOrder {
  coopname: IName
  offerer: IName
  order_hash: IChecksum256
}

export interface ISignSupp {
  coopname: IName
  offerer: IName
  order_hash: IChecksum256
  accept_braname: IName
  act: IDocument2
}

export interface ISignChair {
  coopname: IName
  signer: IName
  order_hash: IChecksum256
  actual_quantity: IAsset
  actual_unit_price: IAsset
  act: IDocument2
}

export interface IPayout {
  coopname: IName
  order_hash: IChecksum256
}

export interface IPayConfirm {
  coopname: IName
  outcome_hash: IChecksum256
}

export interface IPayDecline {
  coopname: IName
  outcome_hash: IChecksum256
  reason: string
}

export interface IReadyIssue {
  coopname: IName
  signer: IName
  order_hash: IChecksum256
}

export interface IIssueStmt {
  coopname: IName
  orderer: IName
  order_hash: IChecksum256
  actual_quantity: IAsset
  actual_unit_price: IAsset
  statement: IDocument2
  meta: string
}

export interface IOnMktIsAuth {
  coopname: IName
  hash: IChecksum256
  authorization: IDocument2
}

export interface IOnMktIsDecl {
  coopname: IName
  hash: IChecksum256
  reason: string
}

export interface IIssueAct1 {
  coopname: IName
  orderer: IName
  order_hash: IChecksum256
  act: IDocument2
}

export interface IIssueAct2 {
  coopname: IName
  delivery_signer: IName
  order_hash: IChecksum256
  act: IDocument2
}

export interface ICancelIssue {
  coopname: IName
  signer: IName
  order_hash: IChecksum256
}

// ── p.mkt.return: actions ────────────────────────────────────────────────

export interface ISubmRetrn {
  coopname: IName
  orderer: IName
  request_hash: IChecksum256
  original_order_hash: IChecksum256
  actual_quantity: IAsset
  reason_text: string
  photos: IChecksum256[]
  statement: IDocument2
}

export interface IAprRetRem {
  coopname: IName
  signer: IName
  braname: IName
  request_hash: IChecksum256
}

export interface IRejRetRem {
  coopname: IName
  signer: IName
  braname: IName
  request_hash: IChecksum256
  reason: string
}

export interface IAccRetrn {
  coopname: IName
  signer: IName
  braname: IName
  request_hash: IChecksum256
  /** Заявление оператора участка в совет об отмене сделки (1116), подпись оператора. */
  statement: IDocument2
  meta: string
  /** Рекламация пайщика (1106) со второй подписью оператора — уйдёт поставщику как претензия. */
  reclamation: IDocument2
}

export interface IAdmitClaim {
  coopname: IName
  supplier: IName
  claim_hash: IChecksum256
}

/** Гарантийная претензия поставщику — таблица `claims`, анкер процесса p.mkt.claim. */
export interface IWarrantyClaim {
  id: IUint64
  hash: IChecksum256
  coopname: IName
  supplier: IName
  orderer: IName
  original_order_id: IUint64
  original_order_hash: IChecksum256
  actual_quantity: IAsset
  amount: IAsset
  reason_text: string
  photos: IChecksum256[]
  reclamation: IDocument2
  status: IName
  created_at: ITimePointSec
  decided_at: ITimePointSec
}

export interface IRejRetrn {
  coopname: IName
  signer: IName
  braname: IName
  request_hash: IChecksum256
  reason: string
}

export interface IOnMktRtAuth {
  coopname: IName
  hash: IChecksum256
  authorization: IDocument2
}

export interface IOnMktRtDecl {
  coopname: IName
  hash: IChecksum256
  reason: string
}

export interface IHandBack {
  coopname: IName
  signer: IName
  braname: IName
  request_hash: IChecksum256
}

export interface IPayRetFee {
  coopname: IName
  request_hash: IChecksum256
}

// ── p.mkt.wroff: actions ─────────────────────────────────────────────────

export interface IPropWroff {
  coopname: IName
  proposed_by: IName
  proposal_hash: IChecksum256
  items: IWroffItem[]
  statement: IDocument2
  meta: string
}

export interface IExecWroff {
  coopname: IName
  signer: IName
  proposal_hash: IChecksum256
  item_index: IUint64
}

/**
 * Председатель кооперативного участка подтверждает фактическое списание со
 * склада своего КУ по авторизованному советом проекту. Один вызов закрывает
 * все неисполненные позиции одного КУ (`braname`); `memo` — подписанная
 * Служебная записка о списании (registry 1111). Авторизация — `coopname`;
 * `signer` должен быть авторизован для `braname` через
 * Branch::is_user_authorized.
 */
export interface IConfirmWroff {
  coopname: IName
  signer: IName
  proposal_hash: IChecksum256
  braname: IName
  memo: IDocument2
}

/**
 * Callback от `soviet::exec` после авторизации Протокола Совета о
 * списании скоропорта (Story 8.4). Сигнатура `(coopname, hash, authorization)`
 * совпадает с AUTHORIZE_CALLBACK_SIGNATURE в soviet.hpp. Контракт `soviet`
 * вызывает action от своего имени (require_auth(_soviet)).
 */
export interface IOnMktWoAuth {
  coopname: IName
  hash: IChecksum256
  authorization: IDocument2
}

/**
 * Callback от `soviet::cancelexprd` (повестка просрочена) или decline-
 * эффекта в soviet. Сигнатура `(coopname, hash, reason)` совпадает с
 * DECLINE_CALLBACK_SIGNATURE в soviet.hpp.
 */
export interface IOnMktWoDecl {
  coopname: IName
  hash: IChecksum256
  reason: string
}

// ── Service action ───────────────────────────────────────────────────────

export interface IMigrate {
}

// ── Tables ───────────────────────────────────────────────────────────────

export interface IOrder {
  id: IUint64
  hash: IChecksum256
  coopname: IName
  orderer: IName
  offerer: IName
  offer_hash: IChecksum256
  delivery_braname: IName
  accept_braname: IName
  current_warehouse_braname: IName
  quantity: IAsset
  actual_quantity: IAsset
  package_size: IAsset
  unit_price: IAsset
  total_cost: IAsset
  fact_cost: IAsset
  warranty_period_secs: IUint32
  warranty_until: ITimePointSec
  status: IName
  batch_hash: IChecksum256
  acceptance_act_signsupp: IDocument2
  acceptance_act_signchair: IDocument2
  /** binary_extension: у заказов, созданных до паевой модели, поля нет. */
  issue_statement?: IDocument2
  /** binary_extension: у заказов, созданных до паевой модели, поля нет. */
  issue_protocol?: IDocument2
  /** Удержанная в счёт признанного гарантийного долга поставщика часть выплаты; binary_extension. */
  payout_withheld?: IAsset
  /**
   * Принятая стоимость по закрывающей подписи акта приёмки — база долга поставщику
   * (Дт 10 / Кт 76) и суммы выплаты; заявление о выдаче её не меняет. binary_extension:
   * у заказов, принятых до появления поля, значения нет — контракт читает `fact_cost`.
   */
  accepted_cost?: IAsset
  issue_act1: IDocument2
  issue_act2: IDocument2
  payout_status: IName
  payout_decline_reason: string
  return_request_id: IUint64
  /** Списанная уценка по заказу из остатка кооператива; ноль — уценка не списывалась. */
  markdown_cost: IAsset
  /** Членский взнос по заказу (requirement b6); ноль — взнос не начислялся. */
  membership_fee: IAsset
}

export interface IReturnRequest {
  id: IUint64
  hash: IChecksum256
  coopname: IName
  orderer: IName
  original_order_id: IUint64
  original_order_hash: IChecksum256
  original_consume_op_id: IChecksum256
  actual_quantity: IAsset
  fact_cost: IAsset
  /** Возвращаемая доля членского взноса; ноль — взнос не возвращается. */
  fee_refund: IAsset
  reason_text: string
  photos: IChecksum256[]
  status: IName
  /** Рекламация пайщика — Заявление о гарантийном возврате имущества (1106). */
  statement: IDocument2
  /** binary_extension: у заявок, созданных до паевой модели, поля нет. */
  accepted_at?: ITimePointSec
  /** Заявление оператора участка в совет об отмене сделки (1116); binary_extension: у заявок до задачи 99D-12 поля нет. */
  cancel_statement?: IDocument2
}

export interface IWroffItem {
  source_order_id: IUint64
  braname: IName
  amount: IAsset
  meta: string
  executed: IBool
}

export interface IWriteoffProposal {
  id: IUint64
  hash: IChecksum256
  coopname: IName
  proposed_by: IName
  decided_by: IName
  items: IWroffItem[]
  total_amount: IAsset
  status: IName
  protocol: IDocument2
}

export interface IAcceptorder {
  coopname: IName
  offerer: IName
  order_hash: IChecksum256
}

export interface IAccretrn {
  coopname: IName
  signer: IName
  braname: IName
  request_hash: IChecksum256
  statement: IDocument2
  meta: string
}

export interface IAprretrem {
  coopname: IName
  signer: IName
  braname: IName
  request_hash: IChecksum256
}

export interface ICancelorder {
  coopname: IName
  orderer: IName
  order_hash: IChecksum256
}

export interface ICloseorder {
  coopname: IName
  order_hash: IChecksum256
}

export interface IConfirmwroff {
  coopname: IName
  signer: IName
  proposal_hash: IChecksum256
  braname: IName
  memo: IDocument2
}

export interface ICreateorder {
  coopname: IName
  orderer: IName
  order_hash: IChecksum256
  offer_hash: IChecksum256
  offerer: IName
  delivery_braname: IName
  quantity: IAsset
  unit_price: IAsset
  package_size: IAsset
  warranty_period_secs: IUint32
  batch_hash: IChecksum256
}

export interface IDeclineorder {
  coopname: IName
  offerer: IName
  order_hash: IChecksum256
}

export interface IExecwroff {
  coopname: IName
  signer: IName
  proposal_hash: IChecksum256
  item_index: IUint64
}

export interface IExpireorder {
  coopname: IName
  order_hash: IChecksum256
}

export interface IOnmktwoauth {
  coopname: IName
  hash: IChecksum256
  authorization: IDocument2
}

export interface IOnmktwodecl {
  coopname: IName
  hash: IChecksum256
  reason: string
}

export interface IPayconfirm {
  coopname: IName
  outcome_hash: IChecksum256
}

export interface IPaydecline {
  coopname: IName
  outcome_hash: IChecksum256
  reason: string
}

export interface IPropwroff {
  coopname: IName
  proposed_by: IName
  proposal_hash: IChecksum256
  items: IWroffItem[]
  statement: IDocument2
  meta: string
}

export interface IRejretrem {
  coopname: IName
  signer: IName
  braname: IName
  request_hash: IChecksum256
  reason: string
}

export interface IRejretrn {
  coopname: IName
  signer: IName
  braname: IName
  request_hash: IChecksum256
  reason: string
}

export interface ISetfee {
  coopname: IName
  membership_fee_percent: IUint64
}

export interface ISignchair {
  coopname: IName
  signer: IName
  order_hash: IChecksum256
  actual_quantity: IAsset
  actual_unit_price: IAsset
  act: IDocument2
}

export interface ISignsupp {
  coopname: IName
  offerer: IName
  order_hash: IChecksum256
  accept_braname: IName
  act: IDocument2
}

export interface IStockorder {
  coopname: IName
  orderer: IName
  order_hash: IChecksum256
  offer_hash: IChecksum256
  delivery_braname: IName
  quantity: IAsset
  unit_price: IAsset
  package_size: IAsset
  warranty_period_secs: IUint32
  batch_hash: IChecksum256
}

export interface ISubmretrn {
  coopname: IName
  orderer: IName
  request_hash: IChecksum256
  original_order_hash: IChecksum256
  actual_quantity: IAsset
  reason_text: string
  photos: IChecksum256[]
  statement: IDocument2
}
