// Generated by eosio-abi2ts 1.2.2 - eosio::abi/1.2

export type IAsset = string
export type IName = string
export type IChecksum256 = string
export type IPublicKey = string
export type ISignature = string
export type ITimePointSec = string
export type IUint32 = number
export type IUint64 = number | string

export interface IApprovewthd {
  coopname: IName
  withdraw_hash: IChecksum256
  approved_statement: IDocument2
}

export interface IAuthwthd {
  coopname: IName
  withdraw_hash: IChecksum256
}

export interface ICompletedpst {
  coopname: IName
  deposit_hash: IChecksum256
}

export interface ICompletewthd {
  coopname: IName
  withdraw_hash: IChecksum256
  memo: string
}

export interface ICreatedpst {
  coopname: IName
  username: IName
  deposit_hash: IChecksum256
  quantity: IAsset
}

export interface ICreatewthd {
  coopname: IName
  username: IName
  withdraw_hash: IChecksum256
  quantity: IAsset
  statement: IDocument2
}

export interface IDeclinedpst {
  coopname: IName
  deposit_hash: IChecksum256
  reason: string
}

export interface IDeclinewthd {
  coopname: IName
  withdraw_hash: IChecksum256
  reason: string
}

export interface IDeposit {
  id: IUint64
  coopname: IName
  username: IName
  deposit_hash: IChecksum256
  quantity: IAsset
  status: IName
  created_at: ITimePointSec
}

export interface IDocument2 {
  version: string
  hash: IChecksum256
  doc_hash: IChecksum256
  meta_hash: IChecksum256
  meta: string
  signatures: ISignatureInfo[]
}

export interface IMigrate {
}

// ── Программные соглашения (Эпик 2 / story 2.1) ────────────────────────

/**
 * Запись в `wallet::users.programs[]`. Только хэш и метаданные документа;
 * полный текст лежит в action data `signagree` (audit trail).
 */
export interface IProgramAgreement {
  program_id: IUint64
  doc_hash: IChecksum256
  version: number
  draft_id: IUint64
  signed_at: string
}

/**
 * Строка таблицы `users` контракта wallet (owner программных соглашений).
 * Source: `table_wallet_users.hpp`. Scope = coopname.
 */
export interface IUser {
  username: IName
  programs: IProgramAgreement[]
}

/**
 * signagree — подписание программного соглашения пайщиком (auth: coopname@active).
 * Document — в action data, не в state.
 */
export interface ISignagree {
  coopname: IName
  username: IName
  program_id: IUint64
  document: IDocument2
  draft_id: IUint64
}

/**
 * revokeagree — расторжение программного соглашения (auth: coopname@active).
 * Удаляет программу из `users[username].programs[]`; пустой vector → erase.
 */
export interface IRevokeagree {
  coopname: IName
  username: IName
  program_id: IUint64
}

/**
 * migrate3 (wallet) — идемпотентная per-record миграция программного
 * соглашения из `soviet::agreements3` (auth: coopname@active).
 * Не путать с `ledger2::migrate3` (миграция L3-балансов).
 */
export interface IWalletMigrate3 {
  coopname: IName
  username: IName
  program_id: IUint64
  doc_hash: IChecksum256
  version: number
  draft_id: IUint64
  signed_at: string
}

export interface ISignatureInfo {
  id: IUint32
  signed_hash: IChecksum256
  signer: IName
  public_key: IPublicKey
  signature: ISignature
  signed_at: ITimePointSec
  meta: string
}

export interface IWithdraw {
  id: IUint64
  username: IName
  coopname: IName
  withdraw_hash: IChecksum256
  status: IName
  quantity: IAsset
  statement: IDocument2
  approved_statement: IDocument2
  authorization: IDocument2
  created_at: ITimePointSec
}
